repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-illegal-windows-names
    - id: check-json
    - id: check-shebang-scripts-are-executable
    - id: check-xml
      exclude: ^TOOLS/mpv-osd-symbols.sfdir/font.props$
    - id: check-yaml
    - id: end-of-file-fixer
      exclude: ^TOOLS/osxbundle/mpv.app/Contents/PkgInfo$
    - id: fix-byte-order-marker
    - id: mixed-line-ending
    - id: trailing-whitespace
- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
    - id: codespell
      args: ["--ignore-words-list", "datas,DNE,enew,HDA,numer,ontop,optionA,Paeth,pathc,inout"]
      exclude: ^misc/language.c$
