
/* -------- Generated by ./configure ----------- */

/* Define this to enable avg. byte/sec-based AVI sync method by default:
   (use -bps or -nobps commandline option for run-time method selection)    */
#undef AVI_SYNC_BPS

/* Undefine this if you want soundcard-only timing by default:
   You can still change this with the -alsa or -noalsa command-line option!
   (This function was originally impemented to solve ALSA driver's big
   buffer problems, but it seems to be useful for every soundcard drivers) */
#define ALSA_TIMER

/* Undefine this if your soundcard driver has no working select().
   If you have kernel Oops, player hangups, or just no audio, you should
   try to recompile MPlayer with this option disabled! */
#define HAVE_AUDIO_SELECT

/* You have a choice for MP3 decoding: mp3lib(mpg123) or Win32(l3codeca.acm)
   #define this if you prefer mpg123 (with 3Dnow! support) than l3codeca.acm
   (with mmx/sse optimizations)
   You can still change it runtime using -afm 1 (mpg123) or -afm 4 (l3codeca)*/
#undef DEFAULT_MPG123

/* XMMP support: (test code) */
#undef USE_XMMP_AUDIO
#define LIBDIR "/usr/local/lib"
#define PLUGINDIR LIBDIR "/xmmp/Plugins"
#define XMMP_AUDIO_DRIVER PLUGINDIR "/Sound/oss.so"

/* LIRC (remote control, see www.lirc.org) support: */
#undef HAVE_LIRC

/* Define if your processor stores words with the most significant
   byte first (like Motorola and SPARC, unlike Intel and VAX).  */
/* #define WORDS_BIGENDIAN */

#define ARCH_X86

/////////////////////////////////////////////////////////////////////////////
//
// NOTE: Instead of modifying these here, use the --enable/--disable options
//       of the ./configure script! See ./configure --help for details.
//
/////////////////////////////////////////////////////////////////////////////

/* termcap flag for getch2.c */
#define USE_TERMCAP

/* Extension defines */
#undef HAVE_MLIB     // available only on solaris
#undef HAVE_3DNOW   // only define if you have 3DNOW (AMD k6-2, AMD Athlon, iDT WinChip, etc.)
#define HAVE_MMX      // only define if you have MMX
#define HAVE_SSE     // only define if you have SSE (Intel Pentium III or Celeron II)

/* libvo options */
#define SCREEN_SIZE_X 1
#define SCREEN_SIZE_Y 1
#define HAVE_X11
#undef HAVE_XV
#define HAVE_GL
#undef HAVE_SDL
#undef HAVE_3DFX
#define HAVE_MGA
#define HAVE_SYNCFB

#if defined(HAVE_GL)||defined(HAVE_X11)|defined(HAVE_XV)
#define X11_FULLSCREEN
#endif

