
# -------- Generated by ./configure -----------

AR=ar
CC=gcc
# OPTFLAGS=-O4 -march=i686 -mcpu=i686 -pipe -fomit-frame-pointer -ffast-math
OPTFLAGS=-O4 -march=i686 -mcpu=i686 -pipe -ffast-math
# LIBS=-L/usr/lib -L/usr/local/lib -L/usr/X11R6/lib -lGL  -lX11 -lXext 
X_LIBS=-L/usr/X11R6/lib -lGL  -lX11 -lXext 
TERMCAP_LIB=-ltermcap
XMM_LIBS = 
LIRC_LIBS = 
WIN32_PATH=-DWIN32_PATH=\"/usr/lib/win32\"

