static char* banner_text=
"\n\n"
"MPlayer v0.10 [AVI parser]  (C) 2000. Arpad Gereoffy <arpi@esp-team.scene.hu>\n"
"\n";

static char* help_text=
"Usage:   aviparse [options] [path/]name\n"
"\n"
"  Options:\n"
//"    -o <driver>     select output driver (see '-o help' for driver list)\n"
//"    -vcd <track>    play video cd track from device instead of plain file\n"
//"    -bg             play in background (X11 only!)\n"
//"    -sb <bytepos>   seek to byte position\n"
//"    -ss <timepos>   seek to second position (with timestamp)\n"
//"    -nosound        don't play sound\n"
//"    -abs <bytes>    audio buffer size (in bytes, default: measuring)\n"
//"    -delay <secs>   audio delay in seconds (may be +/- float value)\n"
//"    -alsa           enable timing code (works better with ALSA)\n"
"    -aid <1-99>     select audio channel\n"
"    -afile <name>   dump raw audio data to file\n"
"    -vfile <name>   dump raw video data to file\n"
//"    -vid <0-15>     select video channel\n"
//"    -fps <value>    force frame rate (if value is wrong in mpeg header)\n"
//"    -mc <s/5f>      maximum sync correction per 5 frames (in seconds)\n"
//"    -afm <1-3>      force audio format  1:MPEG 2:PCM 3:AC3 4:Win32\n"
//"\n"
//"  Keys:\n"
//"    <-  or  ->      seek backward/forward  10 seconds\n"
//"    up or down      seek backward/forward   1 minute\n"
//"    p or SPACE      pause movie (press any key to continue)\n"
//"    q  or  ^C       stop playing and quit program\n"
"\n";
