// Translated by:  Daniel Beòa, benad@centrum.cz
// Translated files should be uploaded to ftp://mplayerhq.hu/MPlayer/incoming

// ========================= MPlayer help ===========================

#ifdef HELP_MP_DEFINE_STATIC
static char* banner_text=
"\n\n"
"MPlayer " VERSION "(C) 2000-2002 Arpad Gereoffy (viï DOCS!)\n"
"\n";

// Preklad do slovenèiny 

static char help_text[]=
"Pou¾itie:   mplayer [prepínaèe] [url|cesta/]menosúboru\n"
"\n"
"Prepínaèe:\n"
" -vo <drv[:dev]> výber výstup. video ovládaèa&zariadenia (-vo help pre zoznam)\n"
" -ao <drv[:dev]> výber výstup. audio ovládaèa&zariadenia (-ao help pre zoznam)\n"
" -vcd <trackno>  prehra» VCD (video cd) stopu zo zariadenia namiesto zo súboru\n"
#ifdef HAVE_LIBCSS
" -dvdauth <dev>  urèenie DVD zariadenia pre overenie autenticity (pre kódované disky)\n"
#endif
#ifdef USE_DVDREAD
" -dvd <titleno>  prehra» DVD titul/stopu zo zariadenia (mechaniky) namiesto súboru\n"
" -alang/-slang   vybra» jazyk DVD zvuku/titulkov (pomocou 2-miest. kódu krajiny)\n"
#endif
" -ss <timepos>   posun na pozíciu (sekundy alebo hh:mm:ss)\n"
" -nosound        prehráva» bez zvuku\n"
" -fs -vm -zoom   voµby pre prehrávanie na celú obrazovku (celá obrazovka\n                 meni» videore¾im, softvérový zoom)\n"
" -x <x> -y <y>   zvet¹enie obrazu na rozmer <x>*<y> (pokiaµ to vie -vo ovládaè!)\n"
" -sub <file>     voµba súboru s titulkami (viï tie¾ -subfps, -subdelay)\n"
" -playlist <file> urèenie súboru so zoznamom prehrávaných súborov\n"
" -vid x -aid y   výber èísla video (x) a audio (y) prúdu pre prehrávanie\n"
" -fps x -srate y voµba pre zmenu video (x fps) a audio (y Hz) frekvencie\n"
" -pp <quality>   aktivácia postprocesing filtra (0-4 pre DivX, 0-63 pre mpegy)\n"
" -framedrop      povoli» zahadzovanie snímkov (pre pomalé stroje)\n"
"\n"
"Zákl. klávesy:   (pre kompl. pozrite aj man stránku a input.conf)\n"
" <-  alebo  ->   posun vzad/vpred o 10 sekund\n"
" hore / dole     posun vzad/vpred o  1 minútu\n"
" pgup alebo pgdown  posun vzad/vpred o 10 minút\n"
" < alebo >       posun vzad/vpred v zozname prehrávaných súborov\n"
" p al. medzerník pauza pri prehrávaní (pokraèovaní stlaèením niektorej klávesy)\n"
" q alebo ESC     koniec prehrávania a ukonèenie programu\n"
" + alebo -       upravi» spozdenie zvuku v krokoch +/- 0.1 sekundy\n"
" o               cyklická zmena re¾imu OSD:  niè / pozícia / pozícia+èas\n"
" * alebo /       prida» alebo ubra» hlasitos» (stlaèením 'm' výber master/pcm)\n"
" z alebo x       upravi» spozdenie titulkov v krokoch +/- 0.1 sekundy\n"
" r alebo t       upravi» pozíciu titulkov hore/dole, pozrite tie¾ -vop !\n"
"\n"
" * * * * PREÈÍTAJTE SI MAN STRÁNKU PRE DETAILY (ÏAL©IE VO¥BY A KLÁVESY)! * * * *\n"
"\n";
#endif

// ========================= MPlayer messages ===========================
// mplayer.c:

#define MSGTR_Exiting "\nKonèím... (%s)\n"
#define MSGTR_Exit_eof "Koniec súboru"
#define MSGTR_Exit_error "Záva¾ná chyba"
#define MSGTR_IntBySignal "\nMPlayer preru¹ený signálom %d v module: %s \n"
#define MSGTR_NoHomeDir "Nemô¾em najs» domáci (HOME) adresár\n"
#define MSGTR_GetpathProblem "get_path(\"config\") problém\n"
#define MSGTR_CreatingCfgFile "Vytváram konfiguraèný súbor: %s\n"
#define MSGTR_InvalidVOdriver "Neplatné meno výstupného videoovládaèa: %s\nPou¾ite '-vo help' pre zoznam dostupných ovládaèov.\n"
#define MSGTR_InvalidAOdriver "Neplatné meno výstupného audioovládaèa: %s\nPou¾ite '-ao help' pre zoznam dostupných ovládaèov.\n"
#define MSGTR_CopyCodecsConf "(copy/ln etc/codecs.conf (zo zdrojových kódov MPlayeru) do ~/.mplayer/codecs.conf)\n"
#define MSGTR_CantLoadFont "Nemô¾em naèíta» font: %s\n"
#define MSGTR_CantLoadSub "Nemô¾em naèíta» titulky: %s\n"
#define MSGTR_ErrorDVDkey "Chyba pri spracovaní kµúèa DVD.\n"
#define MSGTR_CmdlineDVDkey "DVD kµúè po¾adovaný na príkazovom riadku je uschovaný pre rozkódovanie.\n"
#define MSGTR_DVDauthOk "DVD sekvencia overenia autenticity vypadá v poriadku.\n"
#define MSGTR_DumpSelectedSteramMissing "dump: FATAL: po¾adovaný prúd chýba!\n"
#define MSGTR_CantOpenDumpfile "Nejde otvori» súbor pre dump!!!\n"
#define MSGTR_CoreDumped "jadro vypísané :)\n"
#define MSGTR_FPSnotspecified "V hlavièke súboru nie je udané (alebo je zlé) FPS! Pou¾ite voµbu -fps !\n"
#define MSGTR_TryForceAudioFmt "Pokú¹am sa vynúti» rodinu audiokodeku %d ...\n"
#define MSGTR_CantFindAfmtFallback "Nemô¾em nájs» audio kodek pre po¾adovanú rodinu, pou¾ijem ostatné.\n"
#define MSGTR_CantFindAudioCodec "Nemô¾em nájs» kodek pre audio formát 0x%X !\n"
#define MSGTR_TryUpgradeCodecsConfOrRTFM "*** Pokúste sa upgradova» %s z etc/codecs.conf\n*** Pokiaµ problém pretrvá, preèítajte si DOCS/CODECS!\n"
#define MSGTR_CouldntInitAudioCodec "Nejde inicializova» audio kodek! -> bez zvuku\n"
#define MSGTR_TryForceVideoFmt "Pokú¹am se vnúti» rodinu videokodeku %d ...\n"
#define MSGTR_CantFindVideoCodec "Nemô¾em najs» kodek pre video formát 0x%X !\n"
#define MSGTR_VOincompCodec "®iaµ, vybrané video_out zariadenie je nekompatibilné s týmto kodekom.\n"
#define MSGTR_CannotInitVO "FATAL: Nemô¾em inicializova» video driver!\n"
#define MSGTR_CannotInitAO "nemô¾em otvori»/inicializova» audio driver -> TICHO\n"
#define MSGTR_StartPlaying "Zaèínam prehráva»...\n"

#define MSGTR_SystemTooSlow "\n\n"\
"         ***********************************************************\n"\
"         ****  Na prehratie tohoto je vá¹ systém príli¹ POMALÝ!  ****\n"\
"         ***********************************************************\n"\
"!!! Mo¾né príèiny, problémy a rie¹enia:\n"\
"- Nejèastej¹ie: nesprávny/chybný _zvukový_ ovládaè. Rie¹enie: skúste -ao sdl al. pou¾ite\n"\
"  ALSA 0.5 alebo oss emuláciu z ALSA 0.9. viac tipov sa dozviete v DOCS/sound.html!\n"\
"- Pomalý video výstup. Skúste iný -vo ovládaè (pre zoznam: -vo help) alebo skúste\n"\
"  s voµbou -framedrop !  Tipy pre ladenie/zrýchlenie videa sú v DOCS/video.html\n"\
"- Pomalý cpu. Neskú¹ajte prehráva» veµké dvd/divx na pomalom cpu! Skúste -hardframedrop\n"\
"- Po¹kodený súbor. Skúste rôzne kombinácie týchto volieb: -nobps  -ni  -mc 0  -forceidx\n"\
"- Pou¾ívate -cache na prehrávanie non-interleaved súboru? skúste -nocache\n"\
"Pokiaµ niè z toho nie je pravda, preèítajte si DOCS/bugreports.html !\n\n"

#define MSGTR_NoGui "MPlayer bol prelo¾ený BEZ podpory GUI!\n"
#define MSGTR_GuiNeedsX "MPlayer GUI vy¾aduje X11!\n"
#define MSGTR_Playing "Prehrávam %s\n"
#define MSGTR_NoSound "Audio: bez zvuku!!!\n"
#define MSGTR_FPSforced "FPS vnútené na hodnotu %5.3f  (ftime: %5.3f)\n"
#define MSGTR_CompiledWithRuntimeDetection "Skompilovné s RUNTIME CPU Detection - varovanie, nie je to optimálne! Na získanie max. výkonu, rekompilujte mplayer zo zdrojakov s --disable-runtime-cpudetection\n"
#define MSGTR_CompiledWithCPUExtensions "Skompilované pre x86 CPU s roz¹íreniami:"
#define MSGTR_AvailableVideoOutputPlugins "Dostupné video výstupné pluginy:\n"
#define MSGTR_AvailableVideoOutputDrivers "Dostupné video výstupné ovládaèe:\n"
#define MSGTR_AvailableAudioOutputDrivers "Dostupné audio výstupné ovládaèe:\n"
#define MSGTR_AvailableAudioCodecs "Dostupné audio kodeky:\n"
#define MSGTR_AvailableVideoCodecs "Dostupné video kodeky:\n"
#define MSGTR_AvailableAudioFm "\nDostupné (vkompilované) audio rodiny kodekov/ovládaèe:\n"
#define MSGTR_AvailableVideoFm "\nDostupné (vkompilované) video rodiny kodekov/ovládaèe:\n"
#define MSGTR_UsingRTCTiming "Pou¾ívam Linuxové hardvérové RTC èasovanie (%ldHz)\n"
#define MSGTR_CannotReadVideoPropertiers "Video: nemô¾em èíta» vlastnosti\n"
#define MSGTR_NoStreamFound "Nenájdený prúd\n"
#define MSGTR_InitializingAudioCodec "Initializujem audio kodek...\n"
#define MSGTR_ErrorInitializingVODevice "Chyba pri otváraní/inicializácii vybraných video_out (-vo) zariadení!\n"
#define MSGTR_ForcedVideoCodec "Vnútený video kodek: %s\n"
#define MSGTR_AODescription_AOAuthor "AO: Popis: %s\nAO: Autor: %s\n"
#define MSGTR_AOComment "AO: Komentár: %s\n"
#define MSGTR_Video_NoVideo "Video: ¾iadne video!!!\n"
#define MSGTR_NotInitializeVOPorVO "\nFATAL: Nemô¾em inicializova» video filtre (-vop) alebo video výstup (-vo) !\n"
#define MSGTR_Paused "\n------ PAUZA -------\r"
#define MSGTR_PlaylistLoadUnable "\nNemô¾em naèíta» playlist %s\n"

// mencoder.c:

#define MSGTR_MEncoderCopyright "(C) 2000-2002 Arpad Gereoffy (viï. DOCS!)\n"
#define MSGTR_UsingPass3ControllFile "Pou¾ívam pass3 ovládací súbor: %s\n"
#define MSGTR_MissingFilename "\nChýbajúce meno súboru!\n\n"
#define MSGTR_CannotOpenFile_Device "Nemô¾em otvori» súbor/zariadenie\n"
#define MSGTR_ErrorDVDAuth "Chyba v DVD auth...\n"
#define MSGTR_CannotOpenDemuxer "Nemô¾em otvori» demuxer\n"
#define MSGTR_NoAudioEncoderSelected "\n®iaden encoder (-oac) vybraný! Vyberte jeden alebo -nosound. Pou¾ite -oac help !\n"
#define MSGTR_NoVideoEncoderSelected "\n®iaden encoder (-ovc) vybraný! Vyberte jeden, pou¾ite -ovc help !\n"
#define MSGTR_InitializingAudioCodec "Inicializujem audio kodek...\n"
#define MSGTR_CannotOpenOutputFile "Nemô¾em otvori» súbor '%s'\n"
#define MSGTR_EncoderOpenFailed "Zlyhal to open the encoder\n"
#define MSGTR_ForcingOutputFourcc "Forcing output fourcc to %x [%.4s]\n"
#define MSGTR_WritingAVIHeader "Writing AVI header...\n"
#define MSGTR_DuplicateFrames "\nduplicate %d frame(s)!!!    \n"
#define MSGTR_SkipFrame "\nskip frame!!!    \n"
#define MSGTR_ErrorWritingFile "%s: error writing file.\n"
#define MSGTR_WritingAVIIndex "\nWriting AVI index...\n"
#define MSGTR_FixupAVIHeader "Fixup AVI header...\n"
#define MSGTR_RecommendedVideoBitrate "Recommended video bitrate for %s CD: %d\n"
#define MSGTR_VideoStreamResult "\nVideo stream: %8.3f kbit/s  (%d bps)  size: %d bytes  %5.3f secs  %d frames\n"
#define MSGTR_AudioStreamResult "\nAudio stream: %8.3f kbit/s  (%d bps)  size: %d bytes  %5.3f secs\n"

// open.c, stream.c:
#define MSGTR_CdDevNotfound "CD-ROM zariadenie '%s' nenájdené!\n"
#define MSGTR_ErrTrackSelect "Chyba pri výbere VCD stopy!"
#define MSGTR_ReadSTDIN "Èítam z stdin...\n"
#define MSGTR_UnableOpenURL "Nejde otvori» URL: %s\n"
#define MSGTR_ConnToServer "Pripojený k servru: %s\n"
#define MSGTR_FileNotFound "Súbor nenájdený: '%s'\n"

#define MSGTR_CantOpenDVD "Nejde otvori» DVD zariadenie: %s\n"
#define MSGTR_DVDwait "Èítam ¹truktúru disku, prosím èakajte...\n"
#define MSGTR_DVDnumTitles "Na tomto DVD je %d titulov.\n"
#define MSGTR_DVDinvalidTitle "Neplatné èíslo DVD titulu: %d\n"
#define MSGTR_DVDnumChapters "Na tomto DVD je %d kapitol.\n"
#define MSGTR_DVDinvalidChapter "Neplatné èíslo kapitoly DVD: %d\n"
#define MSGTR_DVDnumAngles "Na tomto DVD je %d úhlov pohµadov.\n"
#define MSGTR_DVDinvalidAngle "Neplatné èíslo uhlu pohµadu DVD: %d\n"
#define MSGTR_DVDnoIFO "Nemô¾em otvori» súbor IFO pre DVD titul %d.\n"
#define MSGTR_DVDnoVOBs "Nemô¾em otvori» VOB súbor (VTS_%02d_1.VOB).\n"
#define MSGTR_DVDopenOk "DVD úspe¹ne otvorené!\n"

// demuxer.c, demux_*.c:
#define MSGTR_AudioStreamRedefined "Upozornenie! Hlavièka audio prúdu %d predefinovaná!\n"
#define MSGTR_VideoStreamRedefined "Upozornenie! Hlavièka video prúdu %d predefinovaná!\n"
#define MSGTR_TooManyAudioInBuffer "\nDEMUXER: Príli¹ mnoho (%d v %d bajtech) audio paketov v bufferi!\n"
#define MSGTR_TooManyVideoInBuffer "\nDEMUXER: Príli¹ mnoho (%d v %d bajtech) video paketov v bufferi!\n"
#define MSGTR_MaybeNI "(mo¾no prehrávate neprekladaný prúd/súbor alebo kodek zlyhal)\n" \
		      "Pre .AVI súbory skúste vynúti» neprekladaný mód voµbou -ni\n"
#define MSGTR_SwitchToNi "\nDetekovaný zle prekladaný .AVI - prepnite -ni mód!\n"
#define MSGTR_DetectedFILMfile "Detekovaný FILM formát súboru!\n"
#define MSGTR_DetectedFLIfile "Detekovaný FLI formát súboru!\n"
#define MSGTR_DetectedROQfile "Detekovaný ROQ formát súboru!\n"
#define MSGTR_DetectedREALfile "Detekovaný REAL formát súboru!\n"
#define MSGTR_DetectedAVIfile "Detekovaný AVI formát súboru!\n"
#define MSGTR_DetectedASFfile "Detekovaný ASF formát súboru!\n"
#define MSGTR_DetectedMPEGPESfile "Detekovaný MPEG-PES formát súboru!\n"
#define MSGTR_DetectedMPEGPSfile "Detekovaný MPEG-PS formát súboru!\n"
#define MSGTR_DetectedMPEGESfile "Detekovaný MPEG-ES formát súboru!\n"
#define MSGTR_DetectedQTMOVfile "Detekovaný QuickTime/MOV formát súboru!\n"
#define MSGTR_DetectedYUV4MPEG2file "Detekovaný YUV4MPEG2 formát súboru!\n"
#define MSGTR_DetectedNuppelVideofile "Detekovaný NuppelVideo formát súboru!\n"
#define MSGTR_DetectedVIVOfile "Detekovaný VIVO formát súboru!\n"
#define MSGTR_DetectedBMPfile "Detekovaný BMP formát súboru!\n"
#define MSGTR_DetectedOGGfile "Detekovaný OGG formát súboru!\n"
#define MSGTR_DetectedRAWDVfile "Detekovaný RAWDV formát súboru!\n"
#define MSGTR_DetectedAudiofile "Detekovaný audio súbor!\n"
#define MSGTR_NotSystemStream "Nie je to MPEG System Stream formát... (mo¾no Transport Stream?)\n"
#define MSGTR_InvalidMPEGES "Neplatný MPEG-ES prúd??? kontaktujte autora, mo¾no je to chyba (bug) :(\n"
#define MSGTR_FormatNotRecognized "========== ®iaµ, tento formát súboru nie je rozpoznaný/podporovaný =======\n"\
				  "==== Pokiaµ je tento súbor AVI, ASF alebo MPEG prúd, kontaktujte autora! ====\n"
#define MSGTR_MissingVideoStream "®iadny video prúd nenájdený!\n"
#define MSGTR_MissingAudioStream "®iadny audio prúd nenájdený...  -> bez zvuku\n"
#define MSGTR_MissingVideoStreamBug "Chýbajúci video prúd!? Kontaktujte autora, mo¾no to je chyba (bug) :(\n"

#define MSGTR_DoesntContainSelectedStream "demux: súbor neobsahuje vybraný audio alebo video prúd\n"

#define MSGTR_NI_Forced "Vnútený"
#define MSGTR_NI_Detected "Detekovaný"
#define MSGTR_NI_Message "%s NEPREKLADANÝ formát súboru AVI!\n"

#define MSGTR_UsingNINI "Pou¾ívam NEPREKLADANÝ po¹kodený formát súboru AVI!\n" 
#define MSGTR_CouldntDetFNo "Nemô¾em urèi» poèet snímkov (pre absolútny posun)  \n"
#define MSGTR_CantSeekRawAVI "Nemô¾em sa posúva» v surových (raw) .AVI prúdoch! (Potrebujem index, zkuste pou¾í» voµbu -idx !)  \n"
#define MSGTR_CantSeekFile "Nemô¾em sa posúva» v tomto súbore!  \n"

#define MSGTR_EncryptedVOB "Kódovaný VOB súbor (prelo¾ené bez podpory libcss)! Preèítajte si DOCS/DVD\n"
#define MSGTR_EncryptedVOBauth "Zakódovaný prúd, ale overenie autenticity ste nepo¾adovali!!\n"

#define MSGTR_MOVcomprhdr "MOV: Komprimované hlavièky nie sú (e¹te) podporované!\n"
#define MSGTR_MOVvariableFourCC "MOV: Upozornenie! premenná FOURCC detekovaná!?\n"
#define MSGTR_MOVtooManyTrk "MOV: Upozornenie! Príli¹ veµa stôp!"
#define MSGTR_FoundAudioStream "==> Nájdený audio prúd: %d\n"
#define MSGTR_FoundVideoStream "==> Nájdený video prúd: %d\n"
#define MSGTR_DetectedTV "TV detekovaný ! ;-)\n"
#define MSGTR_ErrorOpeningOGGDemuxer "Nemô¾em otvori» ogg demuxer\n"
#define MSGTR_ASFSearchingForAudioStream "ASF: Hµadám audio prúd (id:%d)\n"
#define MSGTR_CannotOpenAudioStream "Nemô¾em otvori» audio prúd: %s\n"
#define MSGTR_CannotOpenSubtitlesStream "Nemô¾em otvori» prúd titulkov: %s\n"
#define MSGTR_OpeningAudioDemuxerFailed "Nemô¾em otvori» audio demuxer: %s\n"
#define MSGTR_OpeningSubtitlesDemuxerFailed "Nemô¾em otvori» demuxer titulkov: %s\n"
#define MSGTR_TVInputNotSeekable "v TV vstupe nie je mo¾né sa pohybova»! (mo¾no posun bude na zmenu kanálov ;)\n"
#define MSGTR_DemuxerInfoAlreadyPresent "Demuxer info %s u¾ prítomné\n!"
#define MSGTR_ClipInfo "Clip info: \n"

// dec_video.c & dec_audio.c:
#define MSGTR_CantOpenCodec "nemô¾em otvori» kodek\n"
#define MSGTR_CantCloseCodec "nemô¾em uzavie» kodek\n"

#define MSGTR_MissingDLLcodec "CHYBA: Nemô¾em otvori» potrebný DirectShow kodek: %s\n"
#define MSGTR_ACMiniterror "Nemô¾em naèíta»/inicializova» Win32/ACM AUDIO kodek (chýbajúci súbor DLL?)\n"
#define MSGTR_MissingLAVCcodec "Nemô¾em najs» kodek '%s' v libavcodec...\n"

#define MSGTR_MpegNoSequHdr "MPEG: FATAL: EOF - koniec súboru v priebehu vyhµadávania hlavièky sekvencie\n"
#define MSGTR_CannotReadMpegSequHdr "FATAL: Nemô¾em preèíta» hlavièku sekvencie!\n"
#define MSGTR_CannotReadMpegSequHdrEx "FATAL: Nemô¾em preèíta» roz¹írenie hlavièky sekvencie!\n"
#define MSGTR_BadMpegSequHdr "MPEG: Zlá hlavièka sekvencie!\n"
#define MSGTR_BadMpegSequHdrEx "MPEG: Zlé roz¹írenie hlavièky sekvencie!\n"

#define MSGTR_ShMemAllocFail "Nemô¾em alokova» zdieµanú pamä»\n"
#define MSGTR_CantAllocAudioBuf "Nemô¾em alokova» pamä» pre výstupný audio buffer\n"

#define MSGTR_UnknownAudio "Neznámy/chýbajúci audio formát -> bez zvuku\n"

#define MSGTR_UsingExternalPP "[PP] Pou¾ívam externý postprocessing filter, max q = %d\n"
#define MSGTR_UsingCodecPP "[PP] Po¾ívam postprocessing z kodeku, max q = %d\n"
#define MSGTR_VideoAttributeNotSupportedByVO_VD "Video atribút '%s' nie je podporovaný výberom vo & vd! \n"
#define MSGTR_VideoCodecFamilyNotAvailableStr "Po¾adovaná rodina video kodekov [%s] (vfm=%s) nie je dostupná (zapnite ju pri kompilácii!)\n"
#define MSGTR_AudioCodecFamilyNotAvailableStr "Po¾adovaná rodina audio kodekov [%s] (afm=%s) nie je dostupná (zapnite ju pri kompilácii!)\n"
#define MSGTR_OpeningVideoDecoder "Otváram video dekóder: [%s] %s\n"
#define MSGTR_OpeningAudioDecoder "Otváram audio dekóder: [%s] %s\n"
#define MSGTR_UninitVideoStr "uninit video: %s  \n"
#define MSGTR_UninitAudioStr "uninit audio: %s  \n"
#define MSGTR_VDecoderInitFailed "VDecoder init zlyhal :(\n"
#define MSGTR_ADecoderInitFailed "ADecoder init zlyhal :(\n"
#define MSGTR_ADecoderPreinitFailed "ADecoder preinit zlyhal :(\n"
#define MSGTR_AllocatingBytesForInputBuffer "dec_audio: Alokujem %d bytov pre vstupný buffer\n"
#define MSGTR_AllocatingBytesForOutputBuffer "dec_audio: Alokujem %d + %d = %d bytov pre výstupný buffer\n"
			 
// LIRC:
#define MSGTR_SettingUpLIRC "Nastavujem podporu lirc ...\n"
#define MSGTR_LIRCdisabled "Nebudete môc» pou¾íva» diaµkový ovládaè.\n"
#define MSGTR_LIRCopenfailed "Zlyhal pokus o otvorenie podpory LIRC!\n"
#define MSGTR_LIRCcfgerr "Zlyhalo èítanie konfiguraèného súboru LIRC %s !\n"

// vf.c
#define MSGTR_CouldNotFindVideoFilter "Nemô¾em nájs» video filter '%s'\n"
#define MSGTR_CouldNotOpenVideoFilter "Nemô¾em otvori» video filter '%s'\n"
#define MSGTR_OpeningVideoFilter "Otváram video filter: "
#define MSGTR_CannotFindColorspace "Nemô¾em nájs» be¾ný priestor farieb, ani vlo¾ením 'scale' :(\n"

// vd.c
#define MSGTR_CodecDidNotSet "VDec: kodek nenastavil sh->disp_w a sh->disp_h, skú¹am to obís»!\n"
#define MSGTR_VoConfigRequest "VDec: vo konfiguraèná po¾iadavka - %d x %d (preferovaný csp: %s)\n"
#define MSGTR_CouldNotFindColorspace "Nemô¾em nájs» zhodný priestor farieb - skú¹am znova s -vop scale...\n"
#define MSGTR_MovieAspectIsSet "Movie-Aspect je %.2f:1 - mením rozmery na správne.\n"
#define MSGTR_MovieAspectUndefined "Movie-Aspect je nedefinovný - nemenia sa rozmery.\n"


// ====================== GUI messages/buttons ========================

#ifdef HAVE_NEW_GUI

// --- labels ---
#define MSGTR_About "O aplikácii"
#define MSGTR_FileSelect "Vybra» súbor ..."
#define MSGTR_SubtitleSelect "Vybra» titulky ..."
#define MSGTR_OtherSelect "Vybra» ..."
#define MSGTR_AudioFileSelect "Vybra» externý audio kanál ..."
#define MSGTR_FontSelect "Vybra» font ..."
#define MSGTR_PlayList "PlayList"
#define MSGTR_Equalizer "Equalizer"
#define MSGTR_SkinBrowser "Prehliadaè tém"
#define MSGTR_Network "Sie»ové prehrávanie (streaming) ..."
#define MSGTR_Preferences "Preferencie"
#define MSGTR_OSSPreferences "konfigurácia OSS ovládaèa"
#define MSGTR_NoMediaOpened "¾iadne médium otvorené"
#define MSGTR_VCDTrack "VCD track %d"
#define MSGTR_NoChapter "¾iadna kapitola"
#define MSGTR_Chapter "kapitola %d"
#define MSGTR_NoFileLoaded "nenahraný ¾iaden súbor"

// --- buttons ---
#define MSGTR_Ok "Ok"
#define MSGTR_Cancel "Zru¹i»"
#define MSGTR_Add "Prida»"
#define MSGTR_Remove "Odobra»"
#define MSGTR_Clear "Vyèisti»"
#define MSGTR_Config "Konfigurácia"
#define MSGTR_ConfigDriver "Konfigurova» ovládaè"
#define MSGTR_Browse "Prehliada»"


// --- error messages ---
#define MSGTR_NEMDB "®iaµ, nedostatok pamäte pre buffer na kreslenie."
#define MSGTR_NEMFMR "®iaµ, nedostatok pamäte pre vytváranie menu."
#define MSGTR_IDFGCVD "®iaµ, nemô¾em nájs» gui kompatibilný ovládaè video výstupu."
#define MSGTR_NEEDLAVCFAME "®iaµ, nemô¾ete prehráva» nie mpeg súbory s DXR3/H+ zariadením bez prekódovania.\nProsím zapnite lavc alebo fame v DXR3/H+ konfig. okne."


// --- skin loader error messages
#define MSGTR_SKIN_ERRORMESSAGE "[témy] chyba v konfiguraènom súbore tém %d: %s"
#define MSGTR_SKIN_WARNING1 "[témy] v konfiguraènom súbore tém na riadku %d: widget najdený ale pred  \"section\" nenájdený ( %s )"
#define MSGTR_SKIN_WARNING2 "[témy] v konfiguraènom súbore tém na riadku %d: widget najdený ale pred \"subsection\" nenájdený (%s)"
#define MSGTR_SKIN_BITMAP_16bit  "bitmapa s håbkou 16 bit a menej je nepodporovaná ( %s ).\n"
#define MSGTR_SKIN_BITMAP_FileNotFound  "súbor nenájdený ( %s )\n"
#define MSGTR_SKIN_BITMAP_BMPReadError "chyba èítania bmp ( %s )\n"
#define MSGTR_SKIN_BITMAP_TGAReadError "chyba èítania tga ( %s )\n"
#define MSGTR_SKIN_BITMAP_PNGReadError "chyba èítania png ( %s )\n"
#define MSGTR_SKIN_BITMAP_RLENotSupported "formát RLE packed tga nepodporovaný ( %s )\n"
#define MSGTR_SKIN_BITMAP_UnknownFileType "neznámy typ súboru ( %s )\n"
#define MSGTR_SKIN_BITMAP_ConvertError "chyba konverzie z 24 bit do 32 bit ( %s )\n"
#define MSGTR_SKIN_BITMAP_UnknownMessage "neznáma správa: %s\n"
#define MSGTR_SKIN_FONT_NotEnoughtMemory "nedostatok pamäte\n"
#define MSGTR_SKIN_FONT_TooManyFontsDeclared "príli¹ mnoho fontov deklarovaných\n"
#define MSGTR_SKIN_FONT_FontFileNotFound "súbor fontov nenájdený\n"
#define MSGTR_SKIN_FONT_FontImageNotFound "súbor obrazov fontu nenájdený\n"
#define MSGTR_SKIN_FONT_NonExistentFontID "neexistujúci identifikátor fontu ( %s )\n"
#define MSGTR_SKIN_UnknownParameter "neznámy parameter ( %s )\n"
#define MSGTR_SKINBROWSER_NotEnoughMemory "[prehliadaè tém] nedostatok pamäte.\n"
#define MSGTR_SKIN_SKINCFG_SkinNotFound "Skin nenájdený ( %s ).\n"
#define MSGTR_SKIN_SKINCFG_SkinCfgReadError "Chyba pri èítaní konfiguraèného súboru tém ( %s ).\n"
#define MSGTR_SKIN_LABEL "Témy:"

// --- gtk menus
#define MSGTR_MENU_AboutMPlayer "O aplikácii MPlayer"
#define MSGTR_MENU_Open "Otvori» ..."
#define MSGTR_MENU_PlayFile "Prehra» súbor ..."
#define MSGTR_MENU_PlayVCD "Prehra» VCD ..."
#define MSGTR_MENU_PlayDVD "Prehra» DVD ..."
#define MSGTR_MENU_PlayURL "Prehra» URL ..."
#define MSGTR_MENU_LoadSubtitle "Naèíta» titulky ..."
#define MSGTR_MENU_DropSubtitle "Zahodi» titulky ..."
#define MSGTR_MENU_LoadExternAudioFile "Naèíta» externý audio súbor ..."
#define MSGTR_MENU_Playing "Prehrávam"
#define MSGTR_MENU_Play "Prehra»"
#define MSGTR_MENU_Pause "Pauza"
#define MSGTR_MENU_Stop "Zastavi»"
#define MSGTR_MENU_NextStream "Ïal¹í prúd"
#define MSGTR_MENU_PrevStream "Predchádzajúci prúd"
#define MSGTR_MENU_Size "Veµkos»"
#define MSGTR_MENU_NormalSize "Normálna veµkos»"
#define MSGTR_MENU_DoubleSize "Dvojnásobná veµkos»"
#define MSGTR_MENU_FullScreen "Celá obrazovka"
#define MSGTR_MENU_DVD "DVD"
#define MSGTR_MENU_VCD "VCD"
#define MSGTR_MENU_PlayDisc "Prehra» disk ..."
#define MSGTR_MENU_ShowDVDMenu "Zobrazi» DVD menu"
#define MSGTR_MENU_Titles "Tituly"
#define MSGTR_MENU_Title "Titul %2d"
#define MSGTR_MENU_None "(niè)"
#define MSGTR_MENU_Chapters "Kapitoly"
#define MSGTR_MENU_Chapter "Kapitola %2d"
#define MSGTR_MENU_AudioLanguages "Jazyk zvuku"
#define MSGTR_MENU_SubtitleLanguages "Jazyk titulkov"
#define MSGTR_MENU_PlayList "Playlist"
#define MSGTR_MENU_SkinBrowser "Prehliadaè tém"
#define MSGTR_MENU_Preferences "Predvoµby"
#define MSGTR_MENU_Exit "Koniec ..."


// --- equalizer
#define MSGTR_EQU_Audio "Audio"
#define MSGTR_EQU_Video "Video"
#define MSGTR_EQU_Contrast "Kontrast: "
#define MSGTR_EQU_Brightness "Jas: "
#define MSGTR_EQU_Hue "Odtieò: "
#define MSGTR_EQU_Saturation "Nasýtenie: "
#define MSGTR_EQU_Front_Left "Predný ¥avý"
#define MSGTR_EQU_Front_Right "Predný Pravý"
#define MSGTR_EQU_Back_Left "Zadný ¥avý"
#define MSGTR_EQU_Back_Right "Zadný Pravý"
#define MSGTR_EQU_Center "Center"
#define MSGTR_EQU_Bass "Bass"
#define MSGTR_EQU_All "V¹etko"

// --- playlist
#define MSGTR_PLAYLIST_Path "Cesta"
#define MSGTR_PLAYLIST_Selected "Vybrané súbory"
#define MSGTR_PLAYLIST_Files "Súbory"
#define MSGTR_PLAYLIST_DirectoryTree "Adresárový strom"

// --- preferences
#define MSGTR_PREFERENCES_None "Niè"
#define MSGTR_PREFERENCES_AvailableDrivers "Dostupné ovládaèe:"
#define MSGTR_PREFERENCES_DoNotPlaySound "Nehra» zvuk"
#define MSGTR_PREFERENCES_NormalizeSound "Normalizova» zvuk"
#define MSGTR_PREFERENCES_EnEqualizer "Zapnú» equalizer"
#define MSGTR_PREFERENCES_ExtraStereo "Zapnú» extra stereo"
#define MSGTR_PREFERENCES_Coefficient "Koeficient:"
#define MSGTR_PREFERENCES_AudioDelay "Audio oneskorenie"
#define MSGTR_PREFERENCES_Audio "Audio"
#define MSGTR_PREFERENCES_DoubleBuffer "Zapnú» dvojtý buffering"
#define MSGTR_PREFERENCES_DirectRender "Zapnú» direct rendering"
#define MSGTR_PREFERENCES_FrameDrop "Povoli» zahadzovanie rámcov"
#define MSGTR_PREFERENCES_HFrameDrop "Povoli» TVRDÉ zahadzovanie rámcov (nebezpeèné)"
#define MSGTR_PREFERENCES_Flip "prehodi» obraz horná strana-dole"
#define MSGTR_PREFERENCES_Panscan "Panscan: "
#define MSGTR_PREFERENCES_Video "Video"
#define MSGTR_PREFERENCES_OSDTimer "Èasovaè a indikátor"
#define MSGTR_PREFERENCES_OSDProgress "Iba ukazovateµ priebehu"
#define MSGTR_PREFERENCES_Subtitle "Titulky:"
#define MSGTR_PREFERENCES_SUB_Delay "Oneskorenie: "
#define MSGTR_PREFERENCES_SUB_FPS "FPS:"
#define MSGTR_PREFERENCES_SUB_POS "Pozícia: "
#define MSGTR_PREFERENCES_SUB_AutoLoad "Zakáza» automatické nahrávanie titulkov"
#define MSGTR_PREFERENCES_SUB_Unicode "Titulky v Unicode"
#define MSGTR_PREFERENCES_SUB_MPSUB "Konvertova» dané titulky do MPlayer formátu"
#define MSGTR_PREFERENCES_SUB_SRT "Konvertova» dané titulky do èasovo-urèeného SubViewer (SRT) formátu"
#define MSGTR_PREFERENCES_Font "Font:"
#define MSGTR_PREFERENCES_FontFactor "Font faktor:"
#define MSGTR_PREFERENCES_PostProcess "Zapnú» postprocess"
#define MSGTR_PREFERENCES_AutoQuality "Automatická qualita: "
#define MSGTR_PREFERENCES_NI "Pou¾i» neprekladaný AVI parser"
#define MSGTR_PREFERENCES_IDX "Obnovi» index tabulku, ak je potrebné"
#define MSGTR_PREFERENCES_VideoCodecFamily "Rodina video kodekov:"
#define MSGTR_PREFERENCES_AudioCodecFamily "Rodina audeo kodekov:"
#define MSGTR_PREFERENCES_FRAME_OSD_Level "OSD úroveò"
#define MSGTR_PREFERENCES_FRAME_Subtitle "Titulky"
#define MSGTR_PREFERENCES_FRAME_Font "Font"
#define MSGTR_PREFERENCES_FRAME_PostProcess "Postprocess"
#define MSGTR_PREFERENCES_FRAME_CodecDemuxer "Kodek & demuxer"
#define MSGTR_PREFERENCES_OSS_Device "Zariadenie:"
#define MSGTR_PREFERENCES_OSS_Mixer "Mixer:"
#define MSGTR_PREFERENCES_Message "Prosím pamätajte, nietoré voµby potrebujú re¹tart prehrávania!"
#define MSGTR_PREFERENCES_DXR3_VENC "Video encoder:"
#define MSGTR_PREFERENCES_DXR3_LAVC "Pou¾i» LAVC (ffmpeg)"
#define MSGTR_PREFERENCES_DXR3_FAME "Pou¾i» FAME"
#define MSGTR_PREFERENCES_FontEncoding1 "Unicode"
#define MSGTR_PREFERENCES_FontEncoding2 "Western European Languages (ISO-8859-1)"
#define MSGTR_PREFERENCES_FontEncoding3 "Western European Languages with Euro (ISO-8859-15)"
#define MSGTR_PREFERENCES_FontEncoding4 "Slavic/Central European Languages (ISO-8859-2)"
#define MSGTR_PREFERENCES_FontEncoding5 "Esperanto, Galician, Maltese, Turkish (ISO-8859-3)"
#define MSGTR_PREFERENCES_FontEncoding6 "Old Baltic charset (ISO-8859-4)"
#define MSGTR_PREFERENCES_FontEncoding7 "Cyrillic (ISO-8859-5)"
#define MSGTR_PREFERENCES_FontEncoding8 "Arabic (ISO-8859-6)"
#define MSGTR_PREFERENCES_FontEncoding9 "Modern Greek (ISO-8859-7)"
#define MSGTR_PREFERENCES_FontEncoding10 "Turkish (ISO-8859-9)"
#define MSGTR_PREFERENCES_FontEncoding11 "Baltic (ISO-8859-13)"
#define MSGTR_PREFERENCES_FontEncoding12 "Celtic (ISO-8859-14)"
#define MSGTR_PREFERENCES_FontEncoding13 "Hebrew charsets (ISO-8859-8)"
#define MSGTR_PREFERENCES_FontEncoding14 "Russian (KOI8-R)"
#define MSGTR_PREFERENCES_FontEncoding15 "Ukrainian, Belarusian (KOI8-U/RU)"
#define MSGTR_PREFERENCES_FontEncoding16 "Simplified Chinese charset (CP936)"
#define MSGTR_PREFERENCES_FontEncoding17 "Traditional Chinese charset (BIG5)"
#define MSGTR_PREFERENCES_FontEncoding18 "Japanese charsets (SHIFT-JIS)"
#define MSGTR_PREFERENCES_FontEncoding19 "Korean charset (CP949)"
#define MSGTR_PREFERENCES_FontEncoding20 "Thai charset (CP874)"
#define MSGTR_PREFERENCES_FontNoAutoScale "Nemeni» rozmery"
#define MSGTR_PREFERENCES_FontPropWidth "Proporcionálne k ¹írke filmu"
#define MSGTR_PREFERENCES_FontPropHeight "Proporcionálne k vý¹ke filmu"
#define MSGTR_PREFERENCES_FontPropDiagonal "Proporcionálne k diagonále filmu"
#define MSGTR_PREFERENCES_FontEncoding "Kódovanie:"
#define MSGTR_PREFERENCES_FontBlur "Rozmazanie:"
#define MSGTR_PREFERENCES_FontOutLine "Obrys:"
#define MSGTR_PREFERENCES_FontTextScale "Mierka textu:"
#define MSGTR_PREFERENCES_FontOSDScale "OSD mierka:"
#define MSGTR_PREFERENCES_SubtitleOSD "Titulky & OSD"

// --- messagebox
#define MSGTR_MSGBOX_LABEL_FatalError "fatálna chyba ..."
#define MSGTR_MSGBOX_LABEL_Error "chyba ..."
#define MSGTR_MSGBOX_LABEL_Warning "upozornenie ..."

#endif


