#Playback

SPACE cycle pause

LEFT seek -5
RIGHT seek 30

#Volume 

UP add volume 10
DOWN add volume -5

M cycle mute


#Player

F cycle fullscreen

C screenshot

Q quit

#Media

S subtitle
A Audio

#Help

H Keyboard help





