#!/usr/bin/ruby

class TravisDepsBuilder
  def self.make(name)
    info = build_map[name]
    raise "unrecognized dependency identifier '#{name}'" unless info
    instance = new(name, info[:url], info[:action])
    instance.deps
    instance.build
  end

  attr_reader :name, :url, :action

  def initialize(name, url=nil, action=nil)
    @name, @url, @action = name, url, action
  end

  def build
    send(@action)
  end

  def deps; end

  private
  def git
    sh "git clone --depth=1 #{url} #{name}"
    compile name
  end

  def stable
    filename = File.basename(url)
    sh "wget #{url}"
    sh "tar -xzvf #{filename}"
    dirname  = File.basename(url, ".tar.gz"  )
    compile dirname
  end

  def compile(dirname)
    sh "cd #{dirname} && ./configure && make && sudo make install"
    sh "cd $TRAVIS_BUILD_DIR"
  end

  def sh(command)
    `#{command}`
  end
end

class Libav < TravisDepsBuilder
  def self.build_map
    {
      "libav-stable" => {
        :action => :stable,
        :url    => 'http://libav.org/releases/libav-9.6.tar.gz'
      },
      "libav-git" => {
        :action => :git,
        :url    => "git://git.libav.org/libav.git"
      },
      "ffmpeg-stable" => {
        :action => :stable,
        :url    => 'http://www.ffmpeg.org/releases/ffmpeg-1.2.1.tar.gz'
      },
      "ffmpeg-git" => {
        :action => :git,
        :url    => "git://github.com/FFmpeg/FFmpeg.git"
      }
    }
  end
end

class Libass < TravisDepsBuilder
  def self.build_map
    {
      "libass-stable" => {
        :action => :stable,
        :url    => 'http://libass.googlecode.com/files/libass-0.10.1.tar.gz'
      }
    }
  end
end

class Dependencies < TravisDepsBuilder
  def deps
    sh "sudo apt-get update -y"
    sh "sudo apt-get install pkg-config fontconfig libfribidi-dev yasm -y"
  end
end

Dependencies.new(:deps).deps

Libass.make(ARGV[0])
Libav.make(ARGV[1])
