#!/usr/bin/env bash
# MPlayer mirroring script
# $Id$

PATH=<set_path_if_necessary>
LOCK=<path_to_lockfile>
MIRROR_ROOT=<path_to_mirror_root>
MAILADR=<report_mail_to_adr>

#TMPDIR = /tmp
#export TMPDIR

TMPFILE=`mktemp -t mplayer.XXXXXXXXXXX`

# Check to see if another sync is in progress
if lockfile -! -l 43200 -r 0 "$LOCK"; then
  echo Unable to start mirroring MPlayer, lock file exists.
  exit 1
fi
trap "rm -f $LOCK > /dev/null 2>&1" exit

cd $MIRROR_ROOT

echo "************ rsyncing homepage ************" >> $TMPFILE
rsync -pxlrHtWv --delete --delete-after rsync.mplayerhq.hu::homepage/ \
      homepage >> $TMPFILE 2>&1

echo "************ rsyncing MPlayer ************" >> $TMPFILE
rsync -pxlrHtWv --delete --delete-after --exclude '/benchmark' \
      --exclude '/old_stuff' --exclude '/tests' rsync.mplayerhq.hu::ftp/ \
      MPlayer  >> $TMPFILE 2>&1

x=`wc -l $TMPFILE | awk '{print $1}'`
if [ "$x" -ne "10" ]
then
  mailx -s "MPlayer mirror" $MAILADR < $TMPFILE
fi
rm -f $TMPFILE

