#!/bin/bash

#unicode="--unicode"
#font=arial.ttf
#font=mints-mild.pcf
#font=/home/alex/artwiz-mints-mild-latin2.hex
font=$1
#font=verdana.ttf
encoding=iso-8859-2
fontsize=$2
symbolssize=$3
blur=2
outline=1.5

make || exit

./subfont $unicode --blur $blur --outline $outline "$encoding" $fontsize "$font" || exit
./subfont --append --blur $blur --outline $outline encodings/osd-mplayer $symbolssize osd/osd.pfb || exit

#cp font.desc *.raw ~/.mplayer/font/

exit

# display *.raw files
SIZE=`awk '/bitmap size:/ {print $NF; exit}' font.desc`+800
display -size $SIZE gray:$encoding-a.raw &
display -size $SIZE gray:$encoding-b.raw &
#convert -size $SIZE gray:$encoding-a.raw $encoding-a.png
#convert -size $SIZE gray:$encoding-b.raw $encoding-b.png
