install:
	gimptool --install-admin-bin mplayer_subfont || gimptool --install-bin mplayer_subfont

uninstall:
	gimptool --uninstall-admin-bin mplayer_subfont || true
	gimptool --uninstall-bin mplayer_subfont || true
