// sync'ed with help_mp-en.h 1.70 
// Updates & fixes by pl <p_l@gmx.fr> & n.le gaillart <n@tourmentine.com>
// Original transation by Firebird <firebird@chez.com>

// ========================= Aide MPlayer ===========================

#ifdef HELP_MP_DEFINE_STATIC
static char* banner_text=
"\n\n"
"MPlayer " VERSION "(C) 2000-2002 Arpad Gereoffy (voir les DOCS)\n"
"\n";

static char help_text[]=
"Utilisation:      mplayer [options] [url|répertoire/]fichier\n"
"\n"
"Options de base:  (liste complète dans la page de man)\n"
" -vo <pil[:pér]>  sél. le pil. et le périph. vidéo ('-vo help' pour la liste)\n"
" -ao <pil[:pér]>  sél. le pil. et le périph. audio ('-ao help' pour la liste)\n"
#ifdef HAVE_VCD
" -vcd <n°piste>   lit une piste VCD (Video CD) plutôt qu'un fichier\n"
#endif
#ifdef HAVE_LIBCSS
" -dvdauth <pér>   précise le chemin du lecteur DVD (pour les DVD cryptés)\n"
#endif
#ifdef USE_DVDREAD
" -dvd <num titre> joue un titre DVD plutôt qu'un fichier\n"
" -alang/-slang    sélectionne la langue audio/sous-titres (code pays à 2 lettres)\n"
#endif
" -ss <temps>      démarre la lecture à 'temps' (temps en secondes ou hh:mm:ss)\n"
" -nosound         ne joue aucun son\n"
" -fs              lecture plein-écran (ou -vm, -zoom, détails dans la page de man)\n"
" -x <x> -y <y>    résolution de l'affichage (à utiliser avec -vm ou -zoom)\n"
" -sub <fich>      spécifie les sous-titres à utiliser (cf. -subfps, -subdelay)\n"
" -playlist <fich> spécifie la liste des fichiers à jouer\n"
" -vid x -aid y    spécifie les flux vidéo (x) et audio (y) à jouer\n"
" -fps x -srate y  options pour changer les fréq. vidéo (x fps) et audio (y Hz)\n"
" -pp <qualité>    active le filtre de postprocessing (détails dans la page de man)\n"
" -framedrop       saut d'images (pour les machines lentes)\n"
"\n"
"Fonctions au clavier: (liste complète dans la page de man, voir aussi input.conf)\n"
" <- ou ->         + / - 10 secondes\n"
" haut ou bas      + / - 1 minute\n"
" PgUp ou PgDown   + / - de 10 minutes\n"
" < ou >           fichier suivant / précédent dans la playlist\n"
" p ou ESPACE      pause (presser n'importe quelle touche pour continuer)\n"
" q ou ESC         arrète la lecture et quitte le programme\n"
" + ou -           synchro audio / vidéo: +/- 0.1 seconde\n"
" o                change l'OSD: rien / barre de recherche / barre rech. + temps\n"
" * ou /           augmente/diminue le volume PCM\n"
" z ou x           synchro des sous-titres: +/- 0.1 seconde\n"
" r ou t           pos. des sous-titres: plus haut/plus bas, voir aussi -vop expand\n"
"\n"
" * * * VOIR LA PAGE MAN POUR LES DETAILS ET LES AUTRES OPTIONS ET TOUCHES (AVANCEES) * * *\n"
"\n";
#endif

// ========================= Messages MPlayer ===========================

// mplayer.c: 

#define MSGTR_Exiting "\nSortie... (%s)\n"
#define MSGTR_Exit_quit "Fin"
#define MSGTR_Exit_eof "Fin du fichier"
#define MSGTR_Exit_error "Erreur fatale"
#define MSGTR_IntBySignal "\nMPlayer interrompu par le signal %d dans le module: %s\n"
#define MSGTR_NoHomeDir "Ne peut trouver répertoire HOME\n"
#define MSGTR_GetpathProblem "Problème get_path(\"config\")\n"
#define MSGTR_CreatingCfgFile "Création du fichier de config: %s\n"
#define MSGTR_InvalidVOdriver "Nom du pilote de sortie vidéo invalide: %s\nUtilisez '-vo help' pour avoir une liste des pilotes disponibles.\n"
#define MSGTR_InvalidAOdriver "Nom du pilote de sortie audio invalide: %s\nUtilisez '-ao help' pour avoir une liste des pilotes disponibles.\n"
#define MSGTR_CopyCodecsConf "Copiez/liez etc/codecs.conf depuis le source de MPlayer vers ~/.mplayer/codecs.conf)\n"
#define MSGTR_CantLoadFont "Ne peut charger la police: %s\n"
#define MSGTR_CantLoadSub "Ne peut charger les sous-titres: %s\n"
#define MSGTR_ErrorDVDkey "Erreur avec la clé du DVD.\n"
#define MSGTR_CmdlineDVDkey "La clé DVD demandée sera utilisée pour le décryptage.\n"
#define MSGTR_DVDauthOk "La séquence d'authentification DVD semble OK.\n"
#define MSGTR_DumpSelectedStreamMissing "dump: FATAL: le flux sélectionné est manquant!\n"
#define MSGTR_CantOpenDumpfile "Impossible d'ouvrir le fichier dump!!!\n"
#define MSGTR_CoreDumped "Core dumped :)\n"
#define MSGTR_FPSnotspecified "FPS non spécifié ou invalide dans l'entête! Utilisez l'option -fps.\n"
#define MSGTR_TryForceAudioFmtStr "Tente de forcer la famille de pilotes %s du codec audio ...\n"
#define MSGTR_CantFindAfmtFallback "Ne peut trouver de codec audio pour la famille de pilotes imposée, utilisation d'autres.\n"
#define MSGTR_CantFindAudioCodec "Ne peut trouver de codec pour le format audio 0x%X !\n"
#define MSGTR_TryUpgradeCodecsConfOrRTFM "*** Tentez de mettre à jour %s à partir de etc/codecs.conf\n*** Si ce n'est toujours pas bon, alors lisez DOCS/codecs.html ou DOCS/fr/codecs.html !\n"
#define MSGTR_CouldntInitAudioCodec "Impossible d'initialiser le codec audio -> pas de son\n"
#define MSGTR_TryForceVideoFmtStr "Tente de forcer famille de pilotes %s du codec vidéo %s ...\n"
#define MSGTR_CantFindVideoCodec "Ne peut trouver codec pour format vidéo 0x%X !\n"
#define MSGTR_VOincompCodec "Le pilote de sortie vidéo choisi n'est pas compatible avec ce codec.\n"
#define MSGTR_CannotInitVO "FATAL: Ne peut initialiser le pilote vidéo.\n"
#define MSGTR_CannotInitAO "Ne peut ouvrir/initialiser le périphérique audio -> aucun son\n"
#define MSGTR_StartPlaying "Démarre la lecture...\n"

#define MSGTR_SystemTooSlow "\n\n"\
"         ************************************************************\n"\
"         **** Votre système est trop LENT pour jouer ce fichier! ****\n"\
"         ************************************************************\n"\
"!!! Raisons possibles, problèmes, solutions:\n"\
"- Le plus courant: pilote _audio_ cassé/bogué: Essayez -ao sdl ou utilisez\n"\
"  ALSA 0.5 ou l'émulation OSS d'ALSA 0.9. Lisez DOCS/sound.html pour plus d'astuces!\n"\
"  Essayez aussi avec -autosync 30 ou d'autres valeurs.\n"\
"- Vidéo lente. Essayez avec un pilotes -vo différent (-vo help pour la liste) ou\n"\
"  esssayez avec -framedrop! lisez DOCS/video.html pour les astuces de réglage.\n"\
"- CPU lent. Evitez de lire de gros DVD/DivX sur un CPU lent! essayez -hardframedrop.\n"\
"- Fichier corrompu => essayez des mélanges de: -nobps -ni -mc 0 -forceidx\n"\
"- Pour jouer depuis un média lent (nfs/smb, DVD, VCD, etc.), essayez avec -cache 8192\n"\
"- -cache est utilisé avec un fichier AVI mal multiplexé? Essayez avec -nocache\n"\
"Si rien de tout cela ne résout le problème, lisez DOCS/bugreports.html.\n\n"

#define MSGTR_NoGui "MPlayer a été compilé SANS support GUI!\n"
#define MSGTR_GuiNeedsX "MPlayer GUI a besoin de X11!\n"
#define MSGTR_Playing "Joue %s\n"
#define MSGTR_NoSound "Audio: aucun son!!!\n"
#define MSGTR_FPSforced "FPS forcé à %5.3f  (ftime: %5.3f)\n"
#define MSGTR_CompiledWithRuntimeDetection "Compilé avec détection du CPU à l'exécution - ATTENTION, ce n'est pas optimal! Pour de meilleures performances, recompilez MPlayer avec l'option --disable-runtime-cpudetection\n"
#define MSGTR_CompiledWithCPUExtensions "Compilé pour CPU x86 avec les extensions:"
#define MSGTR_AvailableVideoOutputPlugins "Plugins de sortie vidéo disponibles:\n"
#define MSGTR_AvailableVideoOutputDrivers "Pilotes de sortie vidéo disponibles:\n"
#define MSGTR_AvailableAudioOutputDrivers "Pilotes de sortie audio disponibles::\n"
#define MSGTR_AvailableAudioCodecs "Codecs audio disponibles:\n"
#define MSGTR_AvailableVideoCodecs "Codecs vidéo disponibles:\n"
#define MSGTR_AvailableAudioFm "\nFamilles/pilotes de codecs audio disponibles (inclus à la compilation):\n"
#define MSGTR_AvailableVideoFm "\nFamilles/pilotes de codecs vidéo disponibles (inclus à la compilation):\n"
#define MSGTR_UsingRTCTiming "Utilisation de la synchronisation matérielle par RTC (%ldHz)\n"
#define MSGTR_CannotReadVideoProperties "Vidéo: ne pas pas lire les propriétés\n"
#define MSGTR_NoStreamFound "Pas de flux trouvé\n"
#define MSGTR_InitializingAudioCodec "Initialisation des codecs audio...\n"
#define MSGTR_ErrorInitializingVODevice "Erreur à l'ouverture/initialisation de la sortie vidéo choisie (-vo)!\n"
#define MSGTR_ForcedVideoCodec "Codec vidéo forcé: %s\n"
#define MSGTR_ForcedAudioCodec "Codec audio forcé: %s\n"
#define MSGTR_AODescription_AOAuthor "AO: Description: %s\nAO: Auteur: %s\n"
#define MSGTR_AOComment "AO: Commentaire: %s\n"
#define MSGTR_Video_NoVideo "Vidéo: Pas de vidéo!!!\n"
#define MSGTR_NotInitializeVOPorVO "\nFATAL: n'a pas pu initialiser les filtres vidéo (-vop) ou la sortie vidéo (-vo).\n"
#define MSGTR_Paused "\n================= PAUSE =================\r"
#define MSGTR_PlaylistLoadUnable "\nNe peut pas charger la liste de lecture %s.\n"

// mencoder.c

#define MSGTR_MEncoderCopyright "(C) 2000-2002 Arpad Gereoffy (voir les DOCS)\n"
#define MSGTR_UsingPass3ControllFile "Utilisation du fichier de contrôle de la passe 3\n"
#define MSGTR_MissingFilename "\nNom de fichier manquant!\n\n"
#define MSGTR_CannotOpenFile_Device "Ne peut pas ouvrir le fichier/périph.\n"
#define MSGTR_ErrorDVDAuth "Erreur dans l'authentification du DVD.\n"
#define MSGTR_CannotOpenDemuxer "Ne peut pas ouvrir le démultiplexeur\n"
#define MSGTR_NoAudioEncoderSelected "\nPas d'encodeur audio (-oac) choisi! Choisissez en un ou utilisez -nosound. Essayez -oac help !\n"
#define MSGTR_NoVideoEncoderSelected "\nPas d'encodeur vidéo (-ovc) choisi! Choisissez-en un, essayez -ovc help !\n"
#define MSGTR_CannotOpenOutputFile "Ne peut pas ouvrir le fichier de sortie '%s'\n"
#define MSGTR_EncoderOpenFailed "N'a pas pu ouvrir l'encodeur\n"
#define MSGTR_ForcingOutputFourcc "Code fourcc de sortie forcé à %x [%.4s]\n"
#define MSGTR_WritingAVIHeader "Ecriture de l'entête AVI...\n"
#define MSGTR_DuplicateFrames "\n%d trame(s) dupliquée(s)!!!\n"
#define MSGTR_SkipFrame "\nTrame supprimée!!!    \n"
#define MSGTR_ErrorWritingFile "%s: Erreur durant l'écriture du fichier.\n"
#define MSGTR_WritingAVIIndex "\nEcriture de l'index AVI...\n"
#define MSGTR_FixupAVIHeader "Correction de l'entête AVI...\n"
#define MSGTR_RecommendedVideoBitrate "Bitrate vidéo recommandé pour %s CD: %d\n"
#define MSGTR_VideoStreamResult "\nFlux vidéo: %8.3f kbit/s  (%d bps)  taille: %d octets  %5.3f secs  %d trames\n"
#define MSGTR_AudioStreamResult "\nFlux audio: %8.3f kbit/s  (%d bps)  taille: %d octets  %5.3f secs\n"

// open.c, stream.c:
#define MSGTR_CdDevNotfound "Lecteur CD-ROM '%s' non trouvé!\n"
#define MSGTR_ErrTrackSelect "Erreur lors du choix de la piste VCD.\n"
#define MSGTR_ReadSTDIN "Lecture depuis stdin...\n"
#define MSGTR_UnableOpenURL "Ne peut ouvrir l'URL: %s\n"
#define MSGTR_ConnToServer "Connecté au serveur: %s\n"
#define MSGTR_FileNotFound "Fichier non trouvé: '%s'\n"

#define MSGTR_SMBInitError "Ne peut pas initialiser libsmbclient: %d\n"
#define MSGTR_SMBFileNotFound "Ne peut pas ouvrir depuis le réseau: '%s'\n"
#define MSGTR_SMBNotCompiled "MPlayer n'a pas été compilé avec le support SMB.\n"

#define MSGTR_CantOpenDVD "Ne peut ouvrir le lecteur DVD: %s\n"
#define MSGTR_DVDwait "Lecture de la structure du disque, veuillez patienter...\n"
#define MSGTR_DVDnumTitles "Il y a %d titres sur ce DVD.\n"
#define MSGTR_DVDinvalidTitle "Numéro de titre DVD invalide: %d\n"
#define MSGTR_DVDnumChapters "Il y a %d chapitres sur ce titre DVD.\n"
#define MSGTR_DVDinvalidChapter "Numéro de chapitre DVD invalide: %d\n"
#define MSGTR_DVDnumAngles "Il y a %d séquences sur ce titre DVD.\n"
#define MSGTR_DVDinvalidAngle "Numéro de séquence DVD invalide: %d\n"
#define MSGTR_DVDnoIFO "Ne peut ouvrir le fichier IFO pour le titre DVD %d.\n"
#define MSGTR_DVDnoVOBs "Ne peut ouvrir titre VOBS (VTS_%02d_1.VOB).\n"
#define MSGTR_DVDopenOk "DVD ouvert avec succès.\n"

// demuxer.c, demux_*.c:
#define MSGTR_AudioStreamRedefined "ATTENTION: Entête du flux audio %d redéfini.\n"
#define MSGTR_VideoStreamRedefined "ATTENTION: Entête du flux vidéo %d redéfini.\n"
#define MSGTR_TooManyAudioInBuffer "\nDEMUXER: Trop (%d dans %d octets) de paquets audio dans le tampon!\n"
#define MSGTR_TooManyVideoInBuffer "\nDEMUXER: Trop (%d dans %d octets) de paquets vidéo dans le tampon!\n"
#define MSGTR_MaybeNI "Peut-être que vous jouez un flux/fichier mal multiplexé, ou qu le codec a échoué?\n"\
                      "Pour les fichier .AVI, essayez de forcer le mode non-entrelaçé avec l'option -ni.\n"
#define MSGTR_SwitchToNi "\nFichier .AVI non entrelaçé - passage en mode -ni...\n"
#define MSGTR_Detected_XXX_FileFormat "Fichier de type %s détecté.\n"
#define MSGTR_DetectedAudiofile "Fichier audio détecté.\n"
#define MSGTR_NotSystemStream "Pas un flux de type MPEG System... (peut-être un Flux de Transport?)\n"
#define MSGTR_InvalidMPEGES "Flux MPEG-ES invalide??? Contactez l'auteur, c'est peut-être un bug :(\n"
#define MSGTR_FormatNotRecognized "========== Désolé, ce format de fichier n'est pas reconnu/supporté ===========\n"\
                                  "== Si ce fichier est un flux AVI, ASF ou MPEG, merci de contacter l'auteur! ==\n"
#define MSGTR_MissingVideoStream "Aucun flux vidéo trouvé.\n"
#define MSGTR_MissingAudioStream "Aucun flux audio trouvé -> pas de son\n"
#define MSGTR_MissingVideoStreamBug "Flux vidéo manquant!? Contactez l'auteur, c'est peut-être un bug :(\n"

#define MSGTR_DoesntContainSelectedStream "demux: le fichier ne contient pas le flux audio ou vidéo sélectionné.\n"

#define MSGTR_NI_Forced "Forcé"
#define MSGTR_NI_Detected "Détecté"
#define MSGTR_NI_Message "%s format de fichier AVI NON-ENTRELACE.\n"

#define MSGTR_UsingNINI "Utilise le support des fichiers AVI mal multiplexés!\n"
#define MSGTR_CouldntDetFNo "Ne peut déterminer le nombre de trames (pour recherche absolue)\n"
#define MSGTR_CantSeekRawAVI "Ne peut chercher dans un flux .AVI brut! (Index requis, essayez l'option -idx!)\n"
#define MSGTR_CantSeekFile "Ne peut chercher dans ce fichier!  \n"

#define MSGTR_EncryptedVOB "Fichier VOB crypté (support libcss non compilé!) Lire DOCS/cd-dvd.html\n"
#define MSGTR_EncryptedVOBauth "Flux crypté mais vous n'avez pas demandé d'authentification!!\n"

#define MSGTR_MOVcomprhdr "MOV: Les entêtes compressées ne sont pas (encore) supportées!\n"
#define MSGTR_MOVvariableFourCC "MOV: ATTENTION: Variable FOURCC détectée!?\n"
#define MSGTR_MOVtooManyTrk "MOV: ATTENTION: Trop de pistes!"
#define MSGTR_FoundAudioStream "==> Flux audio trouvé: %d\n"
#define MSGTR_FoundVideoStream "==> Flux vidéo trouvé: %d\n"
#define MSGTR_DetectedTV "TV détectée! ;-)\n"
#define MSGTR_ErrorOpeningOGGDemuxer "Ne peut pas ouvrir le demuxer ogg\n"
#define MSGTR_ASFSearchingForAudioStream "ASF: recherche du flux audio (id:%d)\n"
#define MSGTR_CannotOpenAudioStream "Ne peut pas ouvrir le flux audio: %s\n"
#define MSGTR_CannotOpenSubtitlesStream "Ne peut pas ouvrir le flux des sous-titres: %s\n"
#define MSGTR_OpeningAudioDemuxerFailed "N'a pas pu ouvrir le demuxer audio: %s\n"
#define MSGTR_OpeningSubtitlesDemuxerFailed "N'a pas pu ouvrir le demuxer de sous-titres: %s\n"
#define MSGTR_TVInputNotSeekable "Impossible de rechercher sur l'entrée TV! (cette opération correspondra surement à un changement de chaînes ;)\n"
#define MSGTR_DemuxerInfoAlreadyPresent "Info du demuxer %s déjà présentes!\n"
#define MSGTR_ClipInfo "Information sur le clip: \n"

// dec_video.c & dec_audio.c:
#define MSGTR_CantOpenCodec "Ne peut ouvrir le codec\n"
#define MSGTR_CantCloseCodec "Ne peut fermer le codec\n"

#define MSGTR_MissingDLLcodec "ERREUR: Ne peut trouver le codec DirectShow nécessaire: %s\n"
#define MSGTR_ACMiniterror "Ne peut charger/initialiser le codec AUDIO Win32/ACM (fichier DLL manquant?)\n"
#define MSGTR_MissingLAVCcodec "Ne peut trouver le codec '%s' de libavcodec...\n"

#define MSGTR_MpegNoSequHdr "MPEG: FATAL: Fin du fichier lors de la recherche d'entête de séquence\n"
#define MSGTR_CannotReadMpegSequHdr "FATAL: Ne peut lire l'entête de séquence!\n"
#define MSGTR_CannotReadMpegSequHdrEx "FATAL: Ne peut lire l'extension d'entête de séquence!\n"
#define MSGTR_BadMpegSequHdr "MPEG: Mauvais entête de séquence!\n"
#define MSGTR_BadMpegSequHdrEx "MPEG: Mauvaise extension d'entête de séquence!\n"

#define MSGTR_ShMemAllocFail "Ne peut allouer de mémoire partagée\n"
#define MSGTR_CantAllocAudioBuf "Ne peut allouer de tampon de sortie audio\n"

#define MSGTR_UnknownAudio "Format audio inconnu/manquant -> pas de son\n"

#define MSGTR_UsingExternalPP "[PP] Utilisation de filtres de postprocessing externes, max q = %d\n"
#define MSGTR_UsingCodecPP "[PP] Utilisation du postprocessing du codec, max q = %d\n"
#define MSGTR_VideoAttributeNotSupportedByVO_VD "L'attribut vidéo '%s' n'est pas supporté par ce vo & ce vd! \n"
#define MSGTR_VideoCodecFamilyNotAvailableStr "Famille de codecs vidéo demandée [%s] (vfm=%s) non disponible (activez-les à la compilation!)\n"
#define MSGTR_AudioCodecFamilyNotAvailableStr "Famille de codecs audio demandée [%s] (afm=%s) non disponible (activez-les à la compilation!)\n"
#define MSGTR_OpeningVideoDecoder "Ouverture du décodeur vidéo: [%s] %s\n"
#define MSGTR_OpeningAudioDecoder "Ouverture du décodeur audio: [%s] %s\n"
#define MSGTR_UninitVideoStr "Désinitialisation vidéo: %s  \n"
#define MSGTR_UninitAudioStr "Désinitialistion audio: %s  \n"
#define MSGTR_VDecoderInitFailed "Echec de l'initialisation du VDecoder :(\n"
#define MSGTR_ADecoderInitFailed "Echec de l'initialisation de l'ADecoder :(\n"
#define MSGTR_ADecoderPreinitFailed "Echec de la pré-initialisation de l'ADecoder :(\n"
#define MSGTR_AllocatingBytesForInputBuffer "dec_audio: allocation de %d bytes comme tampon d'entrée\n"
#define MSGTR_AllocatingBytesForOutputBuffer "dec_audio: allocation %d + %d = %d octets comme tampon de sortie\n"

// LIRC:
#define MSGTR_SettingUpLIRC "Mise en place du support LIRC...\n"
#define MSGTR_LIRCdisabled "Vous ne pourrez pas utiliser votre télécommande\n"
#define MSGTR_LIRCopenfailed "Impossible d'activer le support LIRC.\n"
#define MSGTR_LIRCcfgerr "Impossible de lire le fichier de config de LIRC %s.\n"

// vf.c
#define MSGTR_CouldNotFindVideoFilter "N'a pas pu trouver le filtre vidéo '%s'\n"
#define MSGTR_CouldNotOpenVideoFilter "N'a pas pu ouvrir le filtre vidéo '%s'\n"
#define MSGTR_OpeningVideoFilter "Ouverture du filtre vidéo: "
#define MSGTR_CannotFindColorspace "Ne peut pas trouver d'espace de couleurs commun, même en utilisant 'scale' :(\n"

// vd.c
#define MSGTR_CodecDidNotSet "VDec: le codec n'a pas défini sh->disp_w et sh->disp_h, essai de contournement!\n"
#define MSGTR_VoConfigRequest "VDec: requête de configuration du vo - %d x %d (csp préferé: %s)\n"
#define MSGTR_CouldNotFindColorspace "N'a pas pu trouver d'espace de couleur correspondant - nouvel essai avec -vop scale...\n"
#define MSGTR_MovieAspectIsSet "L'aspect du film est %.2f:1 - pré-redimensionnement à l'aspect correct.\n"
#define MSGTR_MovieAspectUndefined "L'aspect du film est indéfini - pas de pré-redimensionnement appliqué.\n"

// ====================== messages/boutons GUI ========================

#ifdef HAVE_NEW_GUI

// --- labels ---
#define MSGTR_About "À propos ..."
#define MSGTR_FileSelect "Choisir un fichier ..."
#define MSGTR_SubtitleSelect "Choisir un sous-titre ..."
#define MSGTR_OtherSelect "Choisir ..."
#define MSGTR_AudioFileSelect "Choisir une source audio extérieure ..."
#define MSGTR_FontSelect "Choisir une police ..."
#define MSGTR_PlayList "Liste de lecture"
#define MSGTR_Equalizer "Equaliseur"
#define MSGTR_SkinBrowser "Navigateur de skins"
#define MSGTR_Network "Streaming sur le réseau ..."
#define MSGTR_Preferences "Préférences"
#define MSGTR_OSSPreferences "Configuration du pilote OSS"
#define MSGTR_NoMediaOpened "pas de média ouvert"
#define MSGTR_VCDTrack "Piste du VCD %d"
#define MSGTR_NoChapter "Pas de chapitre"
#define MSGTR_Chapter "Chapitre %d"
#define MSGTR_NoFileLoaded "Pas de fichier chargé"

// --- boutons ---
#define MSGTR_Ok "Ok"
#define MSGTR_Cancel "Annuler"
#define MSGTR_Add "Ajouter"
#define MSGTR_Remove "Supprimer"
#define MSGTR_Clear "Effacer"
#define MSGTR_Config "Configurer"
#define MSGTR_ConfigDriver "Configuration du pilote"
#define MSGTR_Browse "Browser"

// --- messages d'erreur ---
#define MSGTR_NEMDB "Désolé, pas assez de mémoire pour le tampon de dessin."
#define MSGTR_NEMFMR "Désolé, pas assez de mémoire pour le rendu des menus."
#define MSGTR_IDFGCVD "Désolé, pas de pilote de sortie vidéo compatible avec la GUI."
#define MSGTR_NEEDLAVCFAME "Désolé, vous ne pouvez pas jouer de fichier non-MPEG avec votre périphérique DXR3/H+ sans réencodage\nVeuillez activer lavc ou fame dans la boîte de configuration DXR3/H+."

// --- messages d'erreurs du chargement de skin ---
#define MSGTR_SKIN_ERRORMESSAGE "[Skin] Erreur à la ligne %d du fichier de config de skin: %s" 
#define MSGTR_SKIN_WARNING1 "[Skin] Attention à la ligne %d du fichier de config de skin: Widget trouvé mais \"section\" n'a pas été trouvé avant (%s)"
#define MSGTR_SKIN_WARNING2 "[Skin] Attention à la ligne %d du fichier de config de skin: Widget trouvé mais \"subsection\" n'a pas été trouvé avant (%s)"
#define MSGTR_SKIN_BITMAP_16bit  "Bitmaps de 16 bits ou moins ne sont pas supportés ( %s ).\n"
#define MSGTR_SKIN_BITMAP_FileNotFound  "Fichier non trouvé ( %s )\n"
#define MSGTR_SKIN_BITMAP_BMPReadError "Erreur de lecture BMP ( %s )\n"
#define MSGTR_SKIN_BITMAP_TGAReadError "Erreur de lecture TGA ( %s )\n"
#define MSGTR_SKIN_BITMAP_PNGReadError "Erreur de lecture PNG ( %s )\n"
#define MSGTR_SKIN_BITMAP_RLENotSupported "tga compacté en RLE non supportés ( %s )\n"
#define MSGTR_SKIN_BITMAP_UnknownFileType "format de fichier inconnu ( %s )\n"
#define MSGTR_SKIN_BITMAP_ConvertError "erreur de conversion de 24 bit à 32 bit ( %s )\n"
#define MSGTR_SKIN_BITMAP_UnknownMessage "Message inconnu: %s\n"
#define MSGTR_SKIN_FONT_NotEnoughtMemory "pas assez de mémoire\n"
#define MSGTR_SKIN_FONT_TooManyFontsDeclared "trop de polices déclarées\n"
#define MSGTR_SKIN_FONT_FontFileNotFound "fichier de police introuvable\n"
#define MSGTR_SKIN_FONT_FontImageNotFound "fichier d'image de police introuvable\n"
#define MSGTR_SKIN_FONT_NonExistentFontID "identificateur de fonte inexistant ( %s )\n"
#define MSGTR_SKIN_UnknownParameter "paramètre inconnu ( %s )\n"
#define MSGTR_SKINBROWSER_NotEnoughMemory "[Browser de skins] pas assez de mémoire.\n"
#define MSGTR_SKIN_SKINCFG_SkinNotFound "Skin non trouvé ( %s ).\n"
#define MSGTR_SKIN_SKINCFG_SkinCfgReadError "Erreur de lecture du fichier de configuration du skin ( %s ).\n"
#define MSGTR_SKIN_LABEL "Skins:"

// --- menus gtk
#define MSGTR_MENU_AboutMPlayer "À propos de MPlayer"
#define MSGTR_MENU_Open "Ouvrir ..."
#define MSGTR_MENU_PlayFile "Lire un fichier ..."
#define MSGTR_MENU_PlayVCD "Lire un VCD ..."
#define MSGTR_MENU_PlayDVD "Lire un DVD ..."
#define MSGTR_MENU_PlayURL "Lire une URL ..."
#define MSGTR_MENU_LoadSubtitle "Charger un sous-titre ..."
#define MSGTR_MENU_DropSubtitle "Laisser tomber un sous-titre ..."
#define MSGTR_MENU_LoadExternAudioFile "Chargement d'un fichier audio externe ..."
#define MSGTR_MENU_Playing "En cours de lecture"
#define MSGTR_MENU_Play "Lecture"
#define MSGTR_MENU_Pause "Pause"
#define MSGTR_MENU_Stop "Arrêt"
#define MSGTR_MENU_NextStream "Flux suivant"
#define MSGTR_MENU_PrevStream "Flux précédent"
#define MSGTR_MENU_Size "Taille"
#define MSGTR_MENU_NormalSize "Taille normale"
#define MSGTR_MENU_DoubleSize "Taille double"
#define MSGTR_MENU_FullScreen "Plein écran"
#define MSGTR_MENU_DVD "DVD"
#define MSGTR_MENU_VCD "VCD"
#define MSGTR_MENU_PlayDisc "Lire un disque..."
#define MSGTR_MENU_ShowDVDMenu "Afficher le menu DVD"
#define MSGTR_MENU_Titles "Titres"
#define MSGTR_MENU_Title "Titre %2d"
#define MSGTR_MENU_None "(aucun)"
#define MSGTR_MENU_Chapters "Chapitres"
#define MSGTR_MENU_Chapter "Chapitre %2d"
#define MSGTR_MENU_AudioLanguages "Langues (audio)"
#define MSGTR_MENU_SubtitleLanguages "Langues (sous-titres)"
#define MSGTR_MENU_PlayList "Playlist"
#define MSGTR_MENU_SkinBrowser "Browser de skins"
#define MSGTR_MENU_Preferences "Préférences"
#define MSGTR_MENU_Exit "Quitter ..."
#define MSGTR_MENU_Mute "Silence"
#define MSGTR_MENU_Original "Original"
#define MSGTR_MENU_AspectRatio "Aspect (ratio)"
#define MSGTR_MENU_AudioTrack "Piste audio"
#define MSGTR_MENU_Track "Piste %d"
#define MSGTR_MENU_VideoTrack "Piste Vidéo"
  
// --- equalizer
#define MSGTR_EQU_Audio "Audio"
#define MSGTR_EQU_Video "Vidéo"
#define MSGTR_EQU_Contrast "Contraste: "
#define MSGTR_EQU_Brightness "Luminosité: "
#define MSGTR_EQU_Hue "Hue: "
#define MSGTR_EQU_Saturation "Saturation: "
#define MSGTR_EQU_Front_Left "Avant Gauche"
#define MSGTR_EQU_Front_Right "Avant Droit"
#define MSGTR_EQU_Back_Left "Arrière Gauche"
#define MSGTR_EQU_Back_Right "Arrière Droit"
#define MSGTR_EQU_Center "Centre"
#define MSGTR_EQU_Bass "Basses"
#define MSGTR_EQU_All "Tout"

// --- playlist
#define MSGTR_PLAYLIST_Path "Chemin"
#define MSGTR_PLAYLIST_Selected "Fichiers choisis"
#define MSGTR_PLAYLIST_Files "Fichiers"
#define MSGTR_PLAYLIST_DirectoryTree "Hiérarchie des dossiers"

// --- preferences
#define MSGTR_PREFERENCES_Audio "Audio"
#define MSGTR_PREFERENCES_Video "Vidéo"
#define MSGTR_PREFERENCES_SubtitleOSD "Sous-titre & OSD"
#define MSGTR_PREFERENCES_Misc "Divers"

#define MSGTR_PREFERENCES_None "Aucun"
#define MSGTR_PREFERENCES_AvailableDrivers "Pilotes disponibles:"
#define MSGTR_PREFERENCES_DoNotPlaySound "Ne pas jouer le son"
#define MSGTR_PREFERENCES_NormalizeSound "Normaliser le son"
#define MSGTR_PREFERENCES_EnEqualizer "Activer l'équaliseur"
#define MSGTR_PREFERENCES_ExtraStereo "Activer l'extra-stéréo"
#define MSGTR_PREFERENCES_Coefficient "Coefficient:"
#define MSGTR_PREFERENCES_AudioDelay "Retard audio"
#define MSGTR_PREFERENCES_DoubleBuffer "Activer le double-buffering"
#define MSGTR_PREFERENCES_DirectRender "Activer le rendu direct"
#define MSGTR_PREFERENCES_FrameDrop "Activer le saut de trame"
#define MSGTR_PREFERENCES_HFrameDrop "Activer le saut de trame VIOLENT (dangereux)"
#define MSGTR_PREFERENCES_Flip "Mirroir vertical"
#define MSGTR_PREFERENCES_Panscan "Panscan: "
#define MSGTR_PREFERENCES_OSDTimer "Minuteur et indicateurs"
#define MSGTR_PREFERENCES_OSDProgress "Barres de progression seulement"
#define MSGTR_PREFERENCES_Subtitle "Sous-titre:"
#define MSGTR_PREFERENCES_SUB_Delay "Delay: "
#define MSGTR_PREFERENCES_SUB_FPS "FPS:"
#define MSGTR_PREFERENCES_SUB_POS "Position: "
#define MSGTR_PREFERENCES_SUB_AutoLoad "Désactiver le chargement automatique des sous-titres"
#define MSGTR_PREFERENCES_SUB_Unicode "Sous-titre en Unicode"
#define MSGTR_PREFERENCES_SUB_MPSUB "Convertit le sous-titre dans le format MPlayer"
#define MSGTR_PREFERENCES_SUB_SRT "Convertit le sous-titre vers le format SubViewer (SRT) basé sur le temps"
#define MSGTR_PREFERENCES_Font "Police:"
#define MSGTR_PREFERENCES_FontFactor "Font factor:"
#define MSGTR_PREFERENCES_PostProcess "Activer le postprocessing"
#define MSGTR_PREFERENCES_AutoQuality "Qualité auto.: "
#define MSGTR_PREFERENCES_NI "Utiliser le parseur d'AVI mal multiplexés"
#define MSGTR_PREFERENCES_IDX "Reconstruire l'index, si nécessaire"
#define MSGTR_PREFERENCES_VideoCodecFamily "Famille de codecs vidéo:"
#define MSGTR_PREFERENCES_AudioCodecFamily "Famille de codecs audio:"
#define MSGTR_PREFERENCES_FRAME_OSD_Level "Niveau OSD"
#define MSGTR_PREFERENCES_FRAME_Subtitle "Sous-titre"
#define MSGTR_PREFERENCES_FRAME_Font "Police"
#define MSGTR_PREFERENCES_FRAME_PostProcess "Postprocessing"
#define MSGTR_PREFERENCES_FRAME_CodecDemuxer "Codec & demuxer"
#define MSGTR_PREFERENCES_FRAME_Cache "Cache"
#define MSGTR_PREFERENCES_FRAME_Misc "Divers"
#define MSGTR_PREFERENCES_OSS_Device "Device:"
#define MSGTR_PREFERENCES_OSS_Mixer "Mixer:"
#define MSGTR_PREFERENCES_Message "ATTENTION: certaines options requièrent un redémarrage de la lecture!"
#define MSGTR_PREFERENCES_DXR3_VENC "Encodeur vidéo:"
#define MSGTR_PREFERENCES_DXR3_LAVC "Utiliser LAVC (ffmpeg)"
#define MSGTR_PREFERENCES_DXR3_FAME "Utiliser FAME"
#define MSGTR_PREFERENCES_FontEncoding1 "Unicode"
#define MSGTR_PREFERENCES_FontEncoding2 "Langues Européennes Occidentales (ISO-8859-1)"
#define MSGTR_PREFERENCES_FontEncoding3 "Langues Européeenes Occidentales avec Euro (ISO-8859-15)"
#define MSGTR_PREFERENCES_FontEncoding4 "Langues Européeenes Slaves/Centrales (ISO-8859-2)"
#define MSGTR_PREFERENCES_FontEncoding5 "Esperanto, Galicien, Maltais, Turc (ISO-8859-3)"
#define MSGTR_PREFERENCES_FontEncoding6 "Caractères Old Baltic (ISO-8859-4)"
#define MSGTR_PREFERENCES_FontEncoding7 "Cyrillique (ISO-8859-5)"
#define MSGTR_PREFERENCES_FontEncoding8 "Arabe (ISO-8859-6)"
#define MSGTR_PREFERENCES_FontEncoding9 "Grec Moderne (ISO-8859-7)"
#define MSGTR_PREFERENCES_FontEncoding10 "Turc (ISO-8859-9)"
#define MSGTR_PREFERENCES_FontEncoding11 "Balte (ISO-8859-13)"
#define MSGTR_PREFERENCES_FontEncoding12 "Celte (ISO-8859-14)"
#define MSGTR_PREFERENCES_FontEncoding13 "Hebreu (ISO-8859-8)"
#define MSGTR_PREFERENCES_FontEncoding14 "Russe (KOI8-R)"
#define MSGTR_PREFERENCES_FontEncoding15 "Ukrainien, Biélorusse (KOI8-U/RU)"
#define MSGTR_PREFERENCES_FontEncoding16 "Chinois Simplifié (CP936)"
#define MSGTR_PREFERENCES_FontEncoding17 "Chinois Traditionnel (BIG5)"
#define MSGTR_PREFERENCES_FontEncoding18 "Japonais (SHIFT-JIS)"
#define MSGTR_PREFERENCES_FontEncoding19 "Coréen (CP949)"
#define MSGTR_PREFERENCES_FontEncoding20 "Thaïlandais (CP874)"
#define MSGTR_PREFERENCES_FontEncoding21 "Cyrillique Windows (CP1251)"
#define MSGTR_PREFERENCES_FontNoAutoScale "Pas d'agrandissement auto"
#define MSGTR_PREFERENCES_FontPropWidth "Proportionnel à la largeur du film"
#define MSGTR_PREFERENCES_FontPropHeight "Proportionnel à la hauteur du film"
#define MSGTR_PREFERENCES_FontPropDiagonal "Proportionnel à la diagonale du film"
#define MSGTR_PREFERENCES_FontEncoding "Encodage:"
#define MSGTR_PREFERENCES_FontBlur "Flou:"
#define MSGTR_PREFERENCES_FontOutLine "Contour:"
#define MSGTR_PREFERENCES_FontTextScale "Echelle du texte:"
#define MSGTR_PREFERENCES_FontOSDScale "Echelle de l'OSD:"
#define MSGTR_PREFERENCES_Cache "Cache activé/désactivé"
#define MSGTR_PREFERENCES_LoadFullscreen "Démarrer en plein écran"
#define MSGTR_PREFERENCES_CacheSize "Taille du cache: "
#define MSGTR_PREFERENCES_XSCREENSAVER "Stopper XScreenSaver"
#define MSGTR_PREFERENCES_AutoSync "AutoSynchro on/off"
#define MSGTR_PREFERENCES_AutoSyncValue "Autosynchro: "
  
// --- messagebox
#define MSGTR_MSGBOX_LABEL_FatalError "Erreur fatale!"
#define MSGTR_MSGBOX_LABEL_Error "Erreur!"
#define MSGTR_MSGBOX_LABEL_Warning "Attention!"
  
#endif
