// MPlayer Turkish Translation
// Translated by: "heart_of_the_ocean" Murat ALKAN
// Also send a notify message to the mplayer-dev-eng mailing list.

// ========================= MPlayer help ===========================

#ifdef HELP_MP_DEFINE_STATIC
static char* banner_text=
"\n\n"
"MPlayer " VERSION "(C) 2000-2003 Arpad Gereoffy (Dokümanlara Bakýn)\n"
"\n";

static char help_text[]=
"Kullanim:   mplayer [options] [adres|yer/]dosyaismi\n"
"\n"
"Genel seçenekler: (Tüm seçenekleri görmek için man sayfalarýna bakýn)\n"
" -vo <drv[:aygýt]> video çýkýþ sürücüsünü & aygýtýný seçin ('-vo help' ile listeyi görebilirsiniz)\n"
" -ao <drv[:aygýt]> ses çýkýþ sürücüsünü & aygýtýný seçin ('-ao help' ile listeyi görebilirsiniz)\n"
#ifdef HAVE_VCD
" -vcd <trackno>  vcd yi Çalmaya baþlar. (Video CD) VCD track numarasýný girebilirsiniz\n"
#endif
#ifdef HAVE_LIBCSS
" -dvdauth <aygit>  Doðrulamak için bir DVD aygýtý seçin (Þifreli dvdler için)\n"
#endif
#ifdef USE_DVDREAD
" -dvd <baþlýkno>  DVD baþlýðý çal. Baþlýk numarasýný gireblirsiniz.\n"
" -alang/-slang    DVD dublaj/altyazi dili seçin (2-char country codu tarafýndan)\n"
#endif
" -ss <zamanpoz>   Verilmiþ pozisyonu ara (saniye yada hh:mm:ss)\n"
" -nosound         Sesleri çalmaz\n"
" -fs -vm -zoom   Tam ekran çalýþtýrma seçenekleri (fullscr,vidmode chg,softw.scale)\n"
" -x <x> -y <y>   Ekran çönürlülüðünü ayarlar (-vm veya -zoom kullanýmý için)\n"
" -sub <dosya>     Kullanmak için bir altyazi seçer (-subfps, -subdelay ada bakin)\n"
" -playlist <dosya> Playlist dosyasý seç\n"
" -vid x -aid y   Video seçmek için seçenekler (x) ve ses seçmek için seçenkler (y)\n"
" -fps x -srate y Video deðistirmek için seçenekler (x fps) ve ses (y Hz) oraný\n"
" -pp <kalite>    postprocessing filtresini aktifleþtirir (detaylar için man sayfalarýna bakýn)\n"
" -framedrop      frame dropping i aktifleþtirir (yavaþ bilgisayarlar için)\n"
"\n"
"Baþlica Tuþlar: (tüm liste için man sayfalarýna bakýn, input.conf'u kontrol edin)\n"
" <-  veya  ->       geri sar/ileri sar (10 saniye)\n"
" yukarý veya asaðý  geri sar/ileri sar  (1 dakika)\n"
" pgup veya pgdown   geri sar/ileri sar (10 dakika)\n"
" < veya >           Playlist te ileri sar/geri sar\n"
" p veya BOÞLUK      Çalmayý duraklat (devam ettirmek için bir tuþa basýn)\n"
" q veya ESC         Çalmayý durdur ve çýk\n"
" + veya -           Ses gecikmesini uygun hale getir  +/- 0.1 saniye\n"
" o                  OSD moduna geç:  none / seekbar / seekbar+timer\n"
" * veya /           Sesi yükselt yada alçat\n"
" z veya x           Altyazý gecikmesini uygun hale getir  +/- 0.1 saniye\n"
" r veya t           Altyazi pozisyonunu uygun hale getir ,-vop expand 'ada bakýn\n"
"\n"
" * * * DETAYLAR ÝÇÝN MAN SAYFALARINA BAKIN, GELIÞMIÞ TUÞLARI VE SEÇENEKLERÝ BULABÝLÝRSÝNÝZ * * *\n"
"\n";
#endif

// ========================= MPlayer messages ===========================

// mplayer.c: 

#define MSGTR_Exiting "\nÇýkýyor... (%s)\n"
#define MSGTR_Exit_quit "Çýkýþ"
#define MSGTR_Exit_eof "Dosyanýn Sonu"
#define MSGTR_Exit_error "Ölümcül Hata"
#define MSGTR_IntBySignal "\nMPlayer %s modülündeki %d hatasý ile kapandý\n"
#define MSGTR_NoHomeDir "ANADÝZÝN bulunumadý\n"
#define MSGTR_GetpathProblem "get_path(\"config\") problemi\n"
#define MSGTR_CreatingCfgFile "Ayar dosyasý oluþturuluyor: %s\n"
#define MSGTR_InvalidVOdriver "Yanlis Video çýkýþ sürücüsü adý: %s\n'-vo help' Komutunu kullanarak kullanýlabilir video çýkýþ sürücüleri görebilirsiniz.\n"
#define MSGTR_InvalidAOdriver "Yanliþ Ses çýkýþ sürücüsü adý: %s\n'-ao help' Komutunu kullanarak kullanýlabilir ses çýkýþ sürücüleri görebilirsiniz.\n"
#define MSGTR_CopyCodecsConf "(etc/codecs.conf'u (MPlayer kaynak aðacýndan) ~/.mplayer/codecs.conf a kopyalayýn/bað yapin)\n"
#define MSGTR_BuiltinCodecsConf "Gömülü codecs.conf dosyasý kullanýlýyor\n"
#define MSGTR_CantLoadFont "Yazýtipi açýlamadý: %s\n"
#define MSGTR_CantLoadSub "Altyazý açýlamadý: %s\n"
#define MSGTR_ErrorDVDkey "Yanliþ DVD ANAHTARI metodu.\n"
#define MSGTR_CmdlineDVDkey "Ýstenilen DVD Anahtarý  düzeltemek için kullanýldý.\n"
#define MSGTR_DVDauthOk "DVD Kabul sýrasý TAMAM gibi görünüyor.\n"
#define MSGTR_DumpSelectedStreamMissing "boþaltým: ÖLÜMCÜL:  seçili format hatalý!\n"
#define MSGTR_CantOpenDumpfile "dump(boþaltým) dosyasý açýlamadý!!!\n"
#define MSGTR_CoreDumped "Program kapandý :)\n"
#define MSGTR_FPSnotspecified "Baþlýktaki FPS seçili deðil (veya hatalý) ! -fps komutunu kullanýn!\n"
#define MSGTR_TryForceAudioFmtStr " Ses codecleri sürücü ailesi çalýþmaya zorlanýyor %s ...\n"
#define MSGTR_CantFindAfmtFallback "Zorlanan sürücü ailesi için ses codeci bulunamadý, diðer sürücülere dönülüyor\n"
#define MSGTR_CantFindAudioCodec " 0x%X! Ses formatý için codec bulunamadý\n"
#define MSGTR_TryUpgradeCodecsConfOrRTFM "*** %s dosyasýný etc/codecs.conf dan kopyalayýn.\n*** Çalýþmazsa, DOCS/codecs.html i gözden geçirin!\n"
#define MSGTR_CouldntInitAudioCodec "Ses codeci yüklenemedi! -> ses yok\n"
#define MSGTR_TryForceVideoFmtStr "Video codec sürücüsü zorlanmaya çalýþýlýyor %s ...\n"
#define MSGTR_CantFindVideoCodec "Seçilmiþ -vo sürücüsü ve video formatý 0x%X için Codec bulunamadý!\n"
#define MSGTR_VOincompCodec "Üzgünüz, seçili video_çýkýþ sürücüsü  bu codec ile çakýþýyor.\n"
#define MSGTR_CannotInitVO "ÖLÜMCÜL: Video sürücüsü yüklenemedi!\n"
#define MSGTR_CannotInitAO " Ses sürücüsü açýlamadý/çaliþmadý -> ses yok\n"
#define MSGTR_StartPlaying "Çalmaya baþlanýyor...\n"

#define MSGTR_SystemTooSlow "\n\n"\
"         ************************************************\n"\
"         ****      Sisteminiz bunu çalmak için çok YAVAÞ !     ****\n"\
"         ************************************************\n"\
"!!!  Muhtemel nedenler, problemler,Çözümleri: \n"\
"- En genel: bozuk/hatalý _ses_ kartý. Çözüm: -ao sdl veya baþka birþsey deneyin\n"\
"  ALSA 0.9 için ALSA 0.5 veya OSS emülasyonu.DOCS/sound.html dosyasýna gözatýn!\n"\
"  -autosync 30 veya baþka deðerlerle denemeler yapabilirsiniz.\n"\
"- Yavaþ Video çýkýþý.  -vo komutu ile baþka sürücü seçin(liste için: -vo help) veya\n"\
"  -framedrop ile deneyin!  DOCS/video.html dosyasýna video hýzlandýrma için gözatýn.\n"\
"- Yavaþ CPU. Büyük bir DVD/divx i yavaþ bir CPU ile çalýþtýrmayýn! -hardframedrop u\n"\
"kullanýn. -Bozuk Dosya. Çeþitli seçenekler deneyin: -nobps  -ni  -mc 0  -forceidx gibi.\n"\
"- Yavaþ sürücüden çalacaksanýz (nfs/smb aglarý, dvd, vcd v.b.) -cache 8192  i deneyin.\n"\
"-  -cache ile boþluklandýrýlmamiþ AVI dosyasýmý açýyorsunuz? -nocache ile kullanin.\n"\
"Bunlari yaptýðýnýzda birþey deðiþmiyorsa, DOCS/bugreports.html dosyasýna gözatýn!\n\n"

#define MSGTR_NoGui "MPlayer GRAFÝK ARABÝRÝMSÝZ seçeneðiyle oluþturulmuþ!\n"
#define MSGTR_GuiNeedsX "MPlayer GRAFÝK ARABÝRÝMÝ X11 i gerektirir!\n"
#define MSGTR_Playing "%s Çalýnýyor\n"
#define MSGTR_NoSound "Ses: ses yok!!!\n"
#define MSGTR_FPSforced "FPS  %5.3f  olmak zorunda(ftime: %5.3f)\n"
#define MSGTR_CompiledWithRuntimeDetection "MPlayer RUNTIME CPU Detection ile oluþturulmuþ. - dikkat, bu hýzlý deðildir! En iyi performansý alabilmek için, MPlayer ý -disable-runtime-cpudetection seçeneði ile tekrar compile edin.\n"
#define MSGTR_CompiledWithCPUExtensions "x86 CPU için eklerle oluþturulmuþ:"
#define MSGTR_AvailableVideoOutputDrivers "Video  Çýkýþ  sürücüleri kullanýlabilir:\n"
#define MSGTR_AvailableVideoOutputPlugins "Video  Çýkýþ  pluginleri kullanýlabilir:\n"
#define MSGTR_AvailableAudioOutputDrivers "Ses  Çýkýþ sürücüleri kullanilabilir:\n"
#define MSGTR_AvailableAudioCodecs "Ses codecleri kullanýlabilir:\n"
#define MSGTR_AvailableVideoCodecs "Video Codecleri kullanýlabilir:\n"
#define MSGTR_AvailableAudioFm "\nSes codec aileleri/sürücüleri (gömülü) kullanýlabilir:\n"
#define MSGTR_AvailableVideoFm "\nVideo codec aileleri/sürücüleri (gömülü) kullanýlabilir:\n"
#define MSGTR_UsingRTCTiming "Linux sürücü  RTC zamanlamasý kullanýlýyor(%ldHz)\n"
#define MSGTR_CannotReadVideoProperties "Video: özellikler okunamadi\n"
#define MSGTR_NoStreamFound "Biçim bulunamadi\n"
#define MSGTR_ErrorInitializingVODevice "Video çikis (-vo) sürücüsünü açarken/yüklerken hata!\n"
#define MSGTR_ForcedVideoCodec "Video codecine zorlandý: %s\n"
#define MSGTR_ForcedAudioCodec "Ses codecine zorlandý: %s\n"
#define MSGTR_AODescription_AOAuthor "AO: Açiklama: %s\nAO: Yapan: %s\n"
#define MSGTR_AOComment "AO: Yorum: %s\n"
#define MSGTR_Video_NoVideo "Video: video yok!!!\n"
#define MSGTR_NotInitializeVOPorVO "\nÖLÜMCÜL: Video Filtreleri (-vop) veya video çýkýþý (-vo) yüklenemedi!\n"
#define MSGTR_Paused "\n------ DURAKLADI -------\r"
#define MSGTR_PlaylistLoadUnable "\nPlaylist yüklenemedi %s\n"

// mencoder.c:

#define MSGTR_MEncoderCopyright "(C) 2000-2003 Arpad Gereoffy (BELGELERE Bakýn!)\n"
#define MSGTR_UsingPass3ControllFile "pass3 kontrol dosyasý kullanýlýyor: %s\n"
#define MSGTR_MissingFilename "\nHatalý dosyaadý!\n\n"
#define MSGTR_CannotOpenFile_Device "dosya/aygýt açýlamadý\n"
#define MSGTR_ErrorDVDAuth "DVD kabülünde hata...\n"
#define MSGTR_CannotOpenDemuxer "Ayrýþtýrýcý açýlamadý\n"
#define MSGTR_NoAudioEncoderSelected "\nSes çeviricisi (-oac) seçilmemis!  Birtane seçin yada -nosound u kullanýn. Yardým için: -oac help \n"
#define MSGTR_NoVideoEncoderSelected "\nVideo çeviricisi (-ovc) seçilmemis! Birtane seçin, Yardým için: -ovc help \n"
#define MSGTR_InitializingAudioCodec "Ses codec i yükleniyor...\n"
#define MSGTR_CannotOpenOutputFile "Çýkýþ dosyasý açýlamadý '%s'\n"
#define MSGTR_EncoderOpenFailed "Çevirici acýlamadý\n"
#define MSGTR_ForcingOutputFourcc "Çýkýþ zorlanýyor fourcc den %x [%.4s]'a\n"
#define MSGTR_WritingAVIHeader "AVI Baþlýðý yazýlýyor...\n"
#define MSGTR_DuplicateFrames "\ncift %d çerçevesi(leri)!!!    \n"
#define MSGTR_SkipFrame "\nÇerçeve atla!!!    \n"
#define MSGTR_ErrorWritingFile "%s: dosya yazarken hata.\n"
#define MSGTR_WritingAVIIndex "\nAVI içeriði yazýlýyor...\n"
#define MSGTR_FixupAVIHeader "AVI Baþlýðý düzeltiliyor...\n"
#define MSGTR_RecommendedVideoBitrate "%s CD si için tavsiye edilen video bitrate: %d\n"
#define MSGTR_VideoStreamResult "\nVideo biçimi: %8.3f kbit/s  (%d bps)  boyut: %d byte  %5.3f saniye  %d çerçeve\n"
#define MSGTR_AudioStreamResult "\nSes biçimi: %8.3f kbit/s  (%d bps)  boyut: %d byte    %5.3f saniye\n"

// open.c, stream.c:
#define MSGTR_CdDevNotfound "CD-ROM Sürücüsü '%s' bulunamadý!\n"
#define MSGTR_ErrTrackSelect "VCD Track i seçilirken hata!"
#define MSGTR_ReadSTDIN "stdin'den okunuyor...\n"
#define MSGTR_UnableOpenURL "URL açýlamadý: %s\n"
#define MSGTR_ConnToServer "Sunucuya baðlanýldý: %s\n"
#define MSGTR_FileNotFound "Dosya bulunamadý: '%s'\n"

#define MSGTR_SMBInitError "libsmbclient kütüphanesi çalýþtýrýlamadý: %d\n"
#define MSGTR_SMBFileNotFound "Aðdan açýlamadý: '%s'\n"
#define MSGTR_SMBNotCompiled "MPlayer SMB okuma desteði ile oluþturulmamiþ.\n"

#define MSGTR_CantOpenDVD "DVD sürücüsü açýlamadý: %s\n"
#define MSGTR_DVDwait "Disk yapýsý okunuyor, lütfen bekleyin...\n"
#define MSGTR_DVDnumTitles "Bu DVD de %d baþlýklarý var.\n"
#define MSGTR_DVDinvalidTitle "Yanlýþ DVD baþlýk numarasý: %d\n"
#define MSGTR_DVDnumChapters "Bu DVD Baþlýðýnda de %d bölümleri var.\n"
#define MSGTR_DVDinvalidChapter "Yanlýþ DVD bölüm numarasý: %d\n"
#define MSGTR_DVDnumAngles "Bu DVD  baþlýðýnda %d angles larý var.\n"
#define MSGTR_DVDinvalidAngle "Yanlýþ DVD angle numarasý: %d\n"
#define MSGTR_DVDnoIFO "DVD Baþlýðý için IFO dosyasý açýlamýyor %d.\n"
#define MSGTR_DVDnoVOBs " VOBS Baþlýðý açýlmadý (VTS_%02d_1.VOB).\n"
#define MSGTR_DVDopenOk "DVD baþarýyla açýldý!\n"

// demuxer.c, demux_*.c:
#define MSGTR_AudioStreamRedefined "Dikkat! Ses biçim baþlýðý %d tekrar atandý!\n"
#define MSGTR_VideoStreamRedefined "Dikkat! Video biçim baþlýðý %d tekrar atandý!\n"
#define MSGTR_TooManyAudioInBuffer "\nDEMUXER: Buffer da birçok (%d in %d bytes) ses paketi var!\n"
#define MSGTR_TooManyVideoInBuffer "\nDEMUXER: Buffer da birçok  (%d in %d bytes) video packeti var!\n"
#define MSGTR_MaybeNI "Belki boþluksuz biçim/dosya çalýyor olabilirsiniz veya codec hatalý?\n" \
		      "-ni opsiyonuyla .AVI dosyalarý için, boþluksuz çalmayý modunu zorlayýn.\n"
#define MSGTR_SwitchToNi "\nKötü boþluklandýrýlmýþ .AVI bulundu - -ni moduna geçiliyor!\n"
#define MSGTR_Detected_XXX_FileFormat "%s Dosya formatý bulundu!\n"
#define MSGTR_DetectedAudiofile "Ses dosyasý bulundu!\n"
#define MSGTR_NotSystemStream "MPEG Sistemi Biçimi deðil... (belki Transport Biçimi?)\n"
#define MSGTR_InvalidMPEGES "Invalid MPEG-ES stream??? Contact the author, it may be a bug :(\n"
#define MSGTR_FormatNotRecognized "============ Üzgünüm, bu dosya biçimi desteklenmiyor =============\n"\
				  "=== Eðer bu dosya bir AVI, ASF veta MPEG biçimi ise, program yazarlarýyla baðlantý kurun! ===\n"
#define MSGTR_MissingVideoStream "Video biçimi bulunamadý!\n"
#define MSGTR_MissingAudioStream "Ses biçimi bulunamadý...  ->  ses yok\n"
#define MSGTR_MissingVideoStreamBug "Missing video stream!? Contact the author, it may be a bug :(\n"

#define MSGTR_DoesntContainSelectedStream "demux: Dosya seçili video/ses i içermiyor.\n"

#define MSGTR_NI_Forced "Zorlandý"
#define MSGTR_NI_Detected "Bulundu"
#define MSGTR_NI_Message "%s BOÞLUKSUZ  dosya-biçimi!\n"

#define MSGTR_UsingNINI "BOÞLUKSUZ Bozulma AVI dosya-biçimi kullanýlýyor!\n"
#define MSGTR_CouldntDetFNo "Couldn't determine number of frames (for absolute seek)  \n"
#define MSGTR_CantSeekRawAVI "AVI Biçimleri Raw da aranamadý! (Index zorunlu, -idx  komutuyla deneyin!)  \n"
#define MSGTR_CantSeekFile "Bu dosyada aranamaz!  \n"

#define MSGTR_EncryptedVOB "Þifreli VOB dosyasý (libcss desteði olmadan oluþturulmuþ)! DOCS/cd-dvd.html ye göz atýn.\n"
#define MSGTR_EncryptedVOBauth "Encrypted stream but you did not request authentication!!\n"

#define MSGTR_MOVcomprhdr "MOV: Þýkýþtýrýlmýþ biçimler (þimdilik) deskteklenmiyor !\n"
#define MSGTR_MOVvariableFourCC "MOV: Dikkat! FOURCC bulundu!?\n"
#define MSGTR_MOVtooManyTrk "MOV: Dikkat! Çok fazla track!"
#define MSGTR_FoundAudioStream "==> Bulunan Ses Biçimi: %d\n"
#define MSGTR_FoundVideoStream "==> Bulunan Video Biçimi: %d\n"
#define MSGTR_DetectedTV "TV Bulundu! ;-)\n"
#define MSGTR_ErrorOpeningOGGDemuxer "ogg ayrýþtýrýcýsý açýlamadý\n"
#define MSGTR_ASFSearchingForAudioStream "ASF: Ses biçimi aranýyor (id:%d)\n"
#define MSGTR_CannotOpenAudioStream "Ses Biçimi açýlamadý: %s\n"
#define MSGTR_CannotOpenSubtitlesStream "Altyazý Biçimi Açýlamadý: %s\n"
#define MSGTR_OpeningAudioDemuxerFailed "Ses ayrýþtýrýcýsý açýlýrken hata oluþtu: %s\n"
#define MSGTR_OpeningSubtitlesDemuxerFailed "Altyazý Ayrýþtýrýcýsý açýlýrken hata oluþtu: %s\n"
#define MSGTR_TVInputNotSeekable "TV çýkýþý aranabilir deðil! (Muhtemelen arama kanal deðiþtirmek için olacak ;)\n"
#define MSGTR_DemuxerInfoAlreadyPresent "Ayrýþtýrýcý bilgisi %s önceden açýlmýþ!\n"
#define MSGTR_ClipInfo "Klip bilgisi: \n"

// dec_video.c & dec_audio.c:
#define MSGTR_CantOpenCodec "codec açýlamadý\n"
#define MSGTR_CantCloseCodec "codec kapatýlamadý\n"

#define MSGTR_MissingDLLcodec "HATA: Gerekli olan DirectShow codeci açýlamadý: %s\n"
#define MSGTR_ACMiniterror "Win32/ACM AUDIO codecleri yüklenemedi (DLL dosyasý eksik mi?)\n"
#define MSGTR_MissingLAVCcodec " '%s' codec i libavcodec de bulunamadý...\n"

#define MSGTR_MpegNoSequHdr "MPEG: ÖLÜMCÜL: Sýra baþlýðý için aranýrken EOF \n"
#define MSGTR_CannotReadMpegSequHdr "ÖLÜMCÜL: Sýra baþlýðý okunamadý!\n"
#define MSGTR_CannotReadMpegSequHdrEx "ÖLÜMCÜL: Sýra Baþlýðý eki okunamadý!\n"
#define MSGTR_BadMpegSequHdr "MPEG: Hatalý sýra baþlýðý!\n"
#define MSGTR_BadMpegSequHdrEx "MPEG: Hatalý sýra baþlýðý eki!\n"

#define MSGTR_ShMemAllocFail "Paylaþýlmýþ hafýza yerleþtirilemedi\n"
#define MSGTR_CantAllocAudioBuf "Ses çýkýþý buffer ý yerleþtirilemedi\n"

#define MSGTR_UnknownAudio "Bilinmeyen/hatalý ses biçimi -> ses yok\n"

#define MSGTR_UsingExternalPP "[PP] Using external postprocessing filter, max q = %d\n"
#define MSGTR_UsingCodecPP "[PP] Codeclerin postprocessing i kullanýlýyor, max q = %d\n"
#define MSGTR_VideoAttributeNotSupportedByVO_VD "Video Biçimi '%s' seçili vo & vd tarafýndan desteklenmýyor! \n"
#define MSGTR_VideoCodecFamilyNotAvailableStr "Ýstenilen video codec ailesi [%s] (vfm=%s) kullanýlabilir deðil (compile ederken açýn!)\n"
#define MSGTR_AudioCodecFamilyNotAvailableStr "Ýstenilen ses codec ailesi [%s] (afm=%s) kullanýlabilir deðil. (compile ederken açýn!)\n"
#define MSGTR_OpeningVideoDecoder "Video decoderi açýlýyor: [%s] %s\n"
#define MSGTR_OpeningAudioDecoder "Ses decoderi açýlýyor: [%s] %s\n"
#define MSGTR_UninitVideoStr "uninit video: %s  \n"
#define MSGTR_UninitAudioStr "uninit ses: %s  \n"
#define MSGTR_VDecoderInitFailed "VDecoder açýlýþý baýarýsýz :(\n"
#define MSGTR_ADecoderInitFailed "ADecoder açýlýþý basarýsýz :(\n"
#define MSGTR_ADecoderPreinitFailed "ADecoder önaçýlýþ baþarýsýz :(\n"
#define MSGTR_AllocatingBytesForInputBuffer "dec_audio: Tayin ediliyor: %d byte(giriþ için)\n"
#define MSGTR_AllocatingBytesForOutputBuffer "dec_audio: Tayin ediliyor %d + %d = %d byte  ( çýkýþ buffer i için )\n"
			 
// LIRC:
#define MSGTR_SettingUpLIRC "lirc desteði ayarlanýyor...\n"
#define MSGTR_LIRCdisabled "Uzaktan kontrol sistemini kullanamayacaksýnýz\n"
#define MSGTR_LIRCopenfailed "lirc desteði açýlamadý!\n"
#define MSGTR_LIRCcfgerr "LIRC ayar dosyasý okunamadý %s!\n"

// vf.c
#define MSGTR_CouldNotFindVideoFilter "Video filtresi bulunamadý '%s'\n"
#define MSGTR_CouldNotOpenVideoFilter "Video filtresi açýlamadý '%s'\n"
#define MSGTR_OpeningVideoFilter "Video filtresi açýlýyor: "
#define MSGTR_CannotFindColorspace "Cannot find common colorspace, even by inserting 'scale' :(\n"

// vd.c
#define MSGTR_CodecDidNotSet "VDec: codec ayarlanamadý: sh->disp_w ve sh->disp_h, çözülmeye çalýþýlýyor!\n"
#define MSGTR_VoConfigRequest "VDec: vo ayar isteði - %d x %d (preferred csp: %s)\n"
#define MSGTR_CouldNotFindColorspace "Couldn't find matching colorspace - retrying with -vop scale...\n"
#define MSGTR_MovieAspectIsSet "Movie-Görünümü: %.2f:1 - doðru movie görünüm için önderecelendirme.\n"
#define MSGTR_MovieAspectUndefined "Movie-Görünümü atanmamiþ - önderecelerndirme uygulanmadý.\n"
			 
// ====================== GUI messages/buttons ========================

#ifdef HAVE_NEW_GUI

// --- labels ---
#define MSGTR_About "Hakkýnda"
#define MSGTR_FileSelect "Dosya Seç ..."
#define MSGTR_SubtitleSelect "Altyazi Seç ..."
#define MSGTR_OtherSelect "Seç ..."
#define MSGTR_AudioFileSelect " Ek ses kanalý seç ..."
#define MSGTR_FontSelect "Yazýtipi Seç ..."
#define MSGTR_PlayList "PlayList"
#define MSGTR_Equalizer "Equalizer"
#define MSGTR_SkinBrowser "Skin Tarayýcý"
#define MSGTR_Network "Ag biçimleri ..."
#define MSGTR_Preferences "Seçenekler"
#define MSGTR_OSSPreferences "OSS sürcü ayarlarý"
#define MSGTR_NoMediaOpened "Medya açýlmadý"
#define MSGTR_VCDTrack "VCD track %d"
#define MSGTR_NoChapter "bölüm yok"
#define MSGTR_Chapter "bölüm %d"
#define MSGTR_NoFileLoaded "dosya yüklenmedi"

// --- buttons ---
#define MSGTR_Ok "Tamam"
#define MSGTR_Cancel "Ýptal"
#define MSGTR_Add "Ekle"
#define MSGTR_Remove "Sil"
#define MSGTR_Clear "Temizle"
#define MSGTR_Config "Ayarla"
#define MSGTR_ConfigDriver "Sürücüyü Ayarla"
#define MSGTR_Browse "Gözat"

// --- error messages ---
#define MSGTR_NEMDB "Üzgünüm, buffer için yeterli hafýza yok."
#define MSGTR_NEMFMR "Üzgünüm, menu iþlmesi için yeterli hafýza yok."
#define MSGTR_IDFGCVD "Üzgünüm, GUI ile uyumlu video çýkýþ sürücüsü bulunamadý."
#define MSGTR_NEEDLAVCFAME "Üzgünüm, MPEG olmayan dosyalarý DXR3/H+  aygýtýnýzla çalamazsýnýz. \nLütfen DXR3/H+ ayarkutusundaki lavc veya fame i etkinleþtirin."

// --- skin loader error messages
#define MSGTR_SKIN_ERRORMESSAGE "[skin] Hata : skin ayar dosyasý %d satýrý: %s" 
#define MSGTR_SKIN_WARNING1 "[skin] Dikkat: skin ayar dosyasý  %d satýrý: widget bulundu ama \"section\" bulunamadý ( %s )"
#define MSGTR_SKIN_WARNING2 "[skin] Dikkat: skin ayar dosyasý  %d satýrý: widget bulundu ama \"subsection\" bulunamadý (%s)"
#define MSGTR_SKIN_BITMAP_16bit  "16 bit veya daha az resim desteklenmiyor ( %s ).\n"
#define MSGTR_SKIN_BITMAP_FileNotFound  "dosya bulunamadý ( %s )\n"
#define MSGTR_SKIN_BITMAP_BMPReadError "bmp okuma hatasý ( %s )\n"
#define MSGTR_SKIN_BITMAP_TGAReadError "tga okuma hatasý ( %s )\n"
#define MSGTR_SKIN_BITMAP_PNGReadError "png okuma hatasý ( %s )\n"
#define MSGTR_SKIN_BITMAP_RLENotSupported "RLE paket tga desteklenmiyor ( %s )\n"
#define MSGTR_SKIN_BITMAP_UnknownFileType "bilinmeyen dosya tipi ( %s )\n"
#define MSGTR_SKIN_BITMAP_ConvertError "24 bit den 32 bit e çevirme hatasý ( %s )\n"
#define MSGTR_SKIN_BITMAP_UnknownMessage "Bilinmeyen mesaj: %s\n"
#define MSGTR_SKIN_FONT_NotEnoughtMemory "yetersiz hafýza\n"
#define MSGTR_SKIN_FONT_TooManyFontsDeclared "Çok fazla yazýtipi tanýtýldý\n"
#define MSGTR_SKIN_FONT_FontFileNotFound "yazýtipi dosyasý bulunamadý\n"
#define MSGTR_SKIN_FONT_FontImageNotFound "yazýtipi image dosyasý bulunamadý\n"
#define MSGTR_SKIN_FONT_NonExistentFontID "Varolmayan yazýtipi tanýtýcýsý ( %s )\n"
#define MSGTR_SKIN_UnknownParameter "bilinmeyen parametre ( %s )\n"
#define MSGTR_SKINBROWSER_NotEnoughMemory "[skintarayýcý] hafýza yetersiz.\n"
#define MSGTR_SKIN_SKINCFG_SkinNotFound "Skin bulunamadý ( %s ).\n"
#define MSGTR_SKIN_SKINCFG_SkinCfgReadError "Skin ayar dosyasý okuma hatasý ( %s ).\n"
#define MSGTR_SKIN_LABEL "Skinler:"

// --- gtk menus
#define MSGTR_MENU_AboutMPlayer "MPlayer Hakkýnda"
#define MSGTR_MENU_Open "Aç..."
#define MSGTR_MENU_PlayFile "Dosya Çal ..."
#define MSGTR_MENU_PlayVCD "VCD  Çal..."
#define MSGTR_MENU_PlayDVD "DVD Çal..."
#define MSGTR_MENU_PlayURL "URL Çal ..."
#define MSGTR_MENU_LoadSubtitle "Altyazý yükle ..."
#define MSGTR_MENU_DropSubtitle "Altyazý býrak ..."
#define MSGTR_MENU_LoadExternAudioFile "Ek ses dosyasý yükle ..."
#define MSGTR_MENU_Playing "Çalýnýyor"
#define MSGTR_MENU_Play "Çal"
#define MSGTR_MENU_Pause "Duraklat"
#define MSGTR_MENU_Stop "Dur"
#define MSGTR_MENU_NextStream "Sonraki biçim"
#define MSGTR_MENU_PrevStream "Önceki biçim"
#define MSGTR_MENU_Size "Boyut"
#define MSGTR_MENU_NormalSize "Normal boyut"
#define MSGTR_MENU_DoubleSize "Büyük boyut"
#define MSGTR_MENU_FullScreen "Tam Ekran"
#define MSGTR_MENU_DVD "DVD"
#define MSGTR_MENU_VCD "VCD"
#define MSGTR_MENU_PlayDisc "Çal ..."
#define MSGTR_MENU_ShowDVDMenu "DVD menüsünü göster"
#define MSGTR_MENU_Titles "Baþlýklar"
#define MSGTR_MENU_Title "Baþlýk %2d"
#define MSGTR_MENU_None "(yok)"
#define MSGTR_MENU_Chapters "Bölümler"
#define MSGTR_MENU_Chapter "Bölüm %2d"
#define MSGTR_MENU_AudioLanguages "Ses Dilleri"
#define MSGTR_MENU_SubtitleLanguages "Altyazý Dilleri"
#define MSGTR_MENU_PlayList "Playlist"
#define MSGTR_MENU_SkinBrowser "Skin seçici"
#define MSGTR_MENU_Preferences "Seçenekler"
#define MSGTR_MENU_Exit "Çýkýþ..."
#define MSGTR_MENU_Mute "Sesi Kýs"
#define MSGTR_MENU_Original "Orjinal"
#define MSGTR_MENU_AspectRatio "Görünüþ Oraný"
#define MSGTR_MENU_AudioTrack "Ses track"
#define MSGTR_MENU_Track "Track %d"
#define MSGTR_MENU_VideoTrack "Video track"

// --- equalizer
#define MSGTR_EQU_Audio "Ses"
#define MSGTR_EQU_Video "Video"
#define MSGTR_EQU_Contrast "Kontrast: "
#define MSGTR_EQU_Brightness "Açýklýk: "
#define MSGTR_EQU_Hue "Hue: "
#define MSGTR_EQU_Saturation "Saturation: "
#define MSGTR_EQU_Front_Left "Ön Sol"
#define MSGTR_EQU_Front_Right "Ön Sað"
#define MSGTR_EQU_Back_Left "Arka Sol"
#define MSGTR_EQU_Back_Right "Arka Sað"
#define MSGTR_EQU_Center "Merkez"
#define MSGTR_EQU_Bass "Bass"
#define MSGTR_EQU_All "Hepsi"

// --- playlist
#define MSGTR_PLAYLIST_Path "Yer"
#define MSGTR_PLAYLIST_Selected "Seçili dosyalar"
#define MSGTR_PLAYLIST_Files "Dosyalar"
#define MSGTR_PLAYLIST_DirectoryTree "Dizin Aðacý"

// --- preferences
#define MSGTR_PREFERENCES_Audio "Ses"
#define MSGTR_PREFERENCES_Video "Video"
#define MSGTR_PREFERENCES_SubtitleOSD "Altyazi & OSD"
#define MSGTR_PREFERENCES_Misc "Çeþitli"

#define MSGTR_PREFERENCES_None "Yok"
#define MSGTR_PREFERENCES_AvailableDrivers "Kullanýlabilir sürücüler:"
#define MSGTR_PREFERENCES_DoNotPlaySound "Sesleri çalma"
#define MSGTR_PREFERENCES_NormalizeSound "Sesi normalle"
#define MSGTR_PREFERENCES_EnEqualizer "Equalizer ý Aç"
#define MSGTR_PREFERENCES_ExtraStereo "Extra stereo yu aç"
#define MSGTR_PREFERENCES_Coefficient "Katsayý:"
#define MSGTR_PREFERENCES_AudioDelay "Ses Gecikmesi"
#define MSGTR_PREFERENCES_DoubleBuffer "Çifte buffering i aç"
#define MSGTR_PREFERENCES_DirectRender "Direkt iþlemeyý aç"
#define MSGTR_PREFERENCES_FrameDrop "frame býrakmasýný aç"
#define MSGTR_PREFERENCES_HFrameDrop "HARD frame býrakmasýný aç (tehlikeli)"
#define MSGTR_PREFERENCES_Flip "Flip image upside down"
#define MSGTR_PREFERENCES_Panscan "Panscan: "
#define MSGTR_PREFERENCES_OSDTimer "Zamanlayýcýlar ve Göstergeler"
#define MSGTR_PREFERENCES_OSDProgress "Sadece Progressbarlar"
#define MSGTR_PREFERENCES_Subtitle "Altyazý:"
#define MSGTR_PREFERENCES_SUB_Delay "Gecikme: "
#define MSGTR_PREFERENCES_SUB_FPS "FPS:"
#define MSGTR_PREFERENCES_SUB_POS "Posizyon: "
#define MSGTR_PREFERENCES_SUB_AutoLoad "Altyazý otomatik yüklemesini kapat"
#define MSGTR_PREFERENCES_SUB_Unicode "Unicode altyazý"
#define MSGTR_PREFERENCES_SUB_MPSUB "Mevcut altyazýyý MPlayer'ýn altyazý biçimine çevir"
#define MSGTR_PREFERENCES_SUB_SRT "Mevcut altyazýyý zaman tabanlý SubViewer (SRT) biçimine çevir"
#define MSGTR_PREFERENCES_Font "Yazýtipi:"
#define MSGTR_PREFERENCES_FontFactor "Yazýtipi Faktörü:"
#define MSGTR_PREFERENCES_PostProcess "postprocessing 'i aç"
#define MSGTR_PREFERENCES_AutoQuality "Otomatik Kalite: "
#define MSGTR_PREFERENCES_NI "Boþluksuz AVI yi kullan"
#define MSGTR_PREFERENCES_IDX "Gerekli ise index-tablosunu yeniden oluþturun"
#define MSGTR_PREFERENCES_VideoCodecFamily "Video codec ailesi:"
#define MSGTR_PREFERENCES_AudioCodecFamily "Ses codec ailesi:"
#define MSGTR_PREFERENCES_FRAME_OSD_Level "OSD seviyesi"
#define MSGTR_PREFERENCES_FRAME_Subtitle "Altyazý"
#define MSGTR_PREFERENCES_FRAME_Font "Yazýtipi"
#define MSGTR_PREFERENCES_FRAME_PostProcess "Postprocessing"
#define MSGTR_PREFERENCES_FRAME_CodecDemuxer "Codec & ayriþtýrýcý"
#define MSGTR_PREFERENCES_FRAME_Cache "Cache"
#define MSGTR_PREFERENCES_FRAME_Misc "Diðer"
#define MSGTR_PREFERENCES_OSS_Device "Sürücü:"
#define MSGTR_PREFERENCES_OSS_Mixer "Mixer:"
#define MSGTR_PREFERENCES_Message "Yaptýðýnýz deðiþikliklerin çalýþabilmesi için lütfen MPlayer i yeniden baþlatýn!"
#define MSGTR_PREFERENCES_DXR3_VENC "Video çeviricisi:"
#define MSGTR_PREFERENCES_DXR3_LAVC "LAVC kullan(ffmpeg)"
#define MSGTR_PREFERENCES_DXR3_FAME "FAME kullan"
#define MSGTR_PREFERENCES_FontEncoding1 "Unicode"
#define MSGTR_PREFERENCES_FontEncoding2 "Batý Avrupa Dilleri (ISO-8859-1)"
#define MSGTR_PREFERENCES_FontEncoding3 "Euro ile  Batý Avrupa  dilleri(ISO-8859-15)"
#define MSGTR_PREFERENCES_FontEncoding4 "Slavca/Orta avrupa dilleri (ISO-8859-2)"
#define MSGTR_PREFERENCES_FontEncoding5 "Esperanto, Galician, Maltese, Türkçe (ISO-8859-3)"
#define MSGTR_PREFERENCES_FontEncoding6 "Eski Baltik karakterseti (ISO-8859-4)"
#define MSGTR_PREFERENCES_FontEncoding7 "Cyrillic (ISO-8859-5)"
#define MSGTR_PREFERENCES_FontEncoding8 "Arapça (ISO-8859-6)"
#define MSGTR_PREFERENCES_FontEncoding9 "Modern Yunanca (ISO-8859-7)"
#define MSGTR_PREFERENCES_FontEncoding10 "Türkçe (ISO-8859-9)"
#define MSGTR_PREFERENCES_FontEncoding11 "Baltýk (ISO-8859-13)"
#define MSGTR_PREFERENCES_FontEncoding12 "Celtik (ISO-8859-14)"
#define MSGTR_PREFERENCES_FontEncoding13 "Hebrew karaktersetleri (ISO-8859-8)"
#define MSGTR_PREFERENCES_FontEncoding14 "Rusça (KOI8-R)"
#define MSGTR_PREFERENCES_FontEncoding15 "Ukraynaca, Belarusça (KOI8-U/RU)"
#define MSGTR_PREFERENCES_FontEncoding16 "Sade Çince karakterseti(CP936)"
#define MSGTR_PREFERENCES_FontEncoding17 "Geleneksel Çince karakterseti (BIG5)"
#define MSGTR_PREFERENCES_FontEncoding18 "Japonca karaktersetleri (SHIFT-JIS)"
#define MSGTR_PREFERENCES_FontEncoding19 "Korece karakter seti (CP949)"
#define MSGTR_PREFERENCES_FontEncoding20 "Thaice karakter seti (CP874)"
#define MSGTR_PREFERENCES_FontEncoding21 "Cyrillic Windows (CP1251)"
#define MSGTR_PREFERENCES_FontNoAutoScale "Otomatik Dereceleme Yapma"
#define MSGTR_PREFERENCES_FontPropWidth "Geniþliði orantýla"
#define MSGTR_PREFERENCES_FontPropHeight "Yüksekligi orantýla"
#define MSGTR_PREFERENCES_FontPropDiagonal "Köþegeni orantýla"
#define MSGTR_PREFERENCES_FontEncoding "Çevirme:"
#define MSGTR_PREFERENCES_FontBlur "Blur:"
#define MSGTR_PREFERENCES_FontOutLine "AltýÇizili:"
#define MSGTR_PREFERENCES_FontTextScale "Yazý derecesi:"
#define MSGTR_PREFERENCES_FontOSDScale "OSD derecesi:"
#define MSGTR_PREFERENCES_Cache "Cache açýk/kapalý"
#define MSGTR_PREFERENCES_LoadFullscreen "Tam Ekran olarak baþlat"
#define MSGTR_PREFERENCES_CacheSize "Cache boyutu: "
#define MSGTR_PREFERENCES_XSCREENSAVER "XekranKoruyucusunu Durdur"
#define MSGTR_PREFERENCES_AutoSync "AutoSync açýk/kapalý"
#define MSGTR_PREFERENCES_AutoSyncValue "Autosync: "

// --- messagebox
#define MSGTR_MSGBOX_LABEL_FatalError "Ölümcül hata!"
#define MSGTR_MSGBOX_LABEL_Error "Hata!"
#define MSGTR_MSGBOX_LABEL_Warning "Dikkat!" 

#endif





