name: "Report a macOS Issue"
description: "Create a report for a runtime related macOS Issue"
labels: ["os:mac"]
type: Bug
body:
- type: textarea
  attributes:
      label: "mpv Information"
      placeholder: |
          mpv v0.38.0-96-gf776be6af5 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
           built on May  5 2024 18:37:43
          libplacebo version: v7.349.0 (v6.338.0-120-g7b294350)
          FFmpeg version: 6.1.1
          FFmpeg library versions:
             libavutil       58.29.100
             libavcodec      60.31.102
             libavformat     60.16.100
             libswscale      7.5.100
             libavfilter     9.12.100
             libswresample   4.12.100
      description: |
          Provide the output of `mpv --version`.
      render: bash
  validations:
      required: false
- type: textarea
  attributes:
      label: "Other Information"
      description: >
          - macOS Version: `system_profiler SPSoftwareDataType | sed -rn 's/^ *System Version: (.*$)/\1/p'`
           - Source of the mpv binary or bundle
           - Latest version of mpv you know without the problem
           - The time when the problem started to happen (after updating mpv, system, driver, etc.)
           - Possible screenshot or video of visual glitches

          If you're not using git master or the latest release, update.
          Nightly builds from master can be found [here](https://github.com/mpv-player/mpv/actions/workflows/build.yml?query=branch%3Amaster+event%3Apush),
          click on the latest workflow run, scroll down to the Artifacts section and download the
          appropriate build. Packages and builds can be found [here](https://mpv.io/installation/).
      value: |-
          - macOS version:
          - Source of mpv:
          - Latest known working version:
          - Issue started after the following happened:
      render: text
  validations:
      required: true
- type: textarea
  attributes:
      label: "Reproduction Steps"
      description: >
          Try to reproduce your issue with `--no-config` first. If it isn't reproducible
          with `--no-config` try to find out which option or script causes your issue.


          If the issue is render performance-related, try to reproduce it with `--no-config
          --profile=fast`, which is designed to work on lower-end mobile devices.


          For decoding performance-related issues, additionally try to enable hardware
          decoding with `--hwdec=yes` or the `Ctrl+h` shortcut.


          Describe the reproduction steps as precise as possible. It's very likely that
          the bug you experience wasn't reproduced by the developer because the workflow
          differs from your own.
  validations:
      required: true
- type: textarea
  attributes:
      label: "Expected Behavior"
      placeholder: "What were you expecting?"
  validations:
      required: true
- type: textarea
  attributes:
      label: "Actual Behavior"
      placeholder: "What happened instead?"
  validations:
      required: true
- type: textarea
  attributes:
      label: "Log File"
      placeholder: "Drag and drop log file here (Don't paste content directly)"
      description: >
          Make a log file with `--gpu-debug  --log-file=output.txt`, which is our preferred way, and
          attach it to the issue. If you use the Bundle, a default log is created for your last run
          at `~/Library/Logs/mpv.log`. You can jump to that file via the `Help > Show log File…` menu.


          If you have trouble producing a log file, you can alternatively use `--gpu-debug --msg-time -v -v`,
          save the terminal output to a file, and attach it to the issue.


          In the case of a crash, please provide the macOS Crash Report or create a [backtrace](https://developer.apple.com/library/archive/documentation/General/Conceptual/lldb-guide/chapters/C5-Examining-The-Call-Stack.html)
          yourself.


          Without the log file, this issue will be closed for ignoring the issue template.


          Disclaimer: The log file may contain identifiable information, such as your username.
          Review the log file before sharing and redact any sensitive data if necessary.
  validations:
      required: true
- type: textarea
  attributes:
      label: "Sample Files"
      placeholder: "Drag and drop sample files here"
      description: >
          Please provide sample files for a minimal reproduction case, if the issue can't be
          reproduced without it or it is helpful to demonstrate the issue.


          Preferably files should be attached directly within the text field below. Due to GitHub's
          upload restriction, you may need to archive the sample file first and upload it as `.zip`
          file. If the sample file is too big to attach directly, use a solution that is easy to
          access with possible long-term retention. Possible services include, but are not limited
          to, the following:

          - [0x0.st](https://0x0.st/) (no long-term retention)
           - [Dropbox](https://www.dropbox.com)
           - [Google Drive](https://www.google.com/drive/)
           - [iCLoud Drive](https://www.icloud.com/iclouddrive/)
           - [MediaFire](https://www.mediafire.com/)
           - [OneDrive](https://onedrive.live.com/)
- type: checkboxes
  attributes:
      label: "I carefully read all instruction and confirm that I did the following:"
      options:
          - label: "I tested with the latest mpv version to validate that the issue is not already fixed."
            required: true
          - label: "I provided all required information including system and mpv version."
            required: true
          - label: >-
              I produced the log file with the exact same set of files, parameters, and conditions
              used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
            required: true
          - label: >-
              I produced the log file while the behaviors described in "Actual Behavior" were
              actively observed.
            required: true
          - label: "I attached the full, untruncated log file."
            required: true
          - label: "I attached the backtrace in the case of a crash."
            required: true
