// Generated from etc/input.conf

"# mpv keybindings\n"
"#\n"
"# Location of user-defined bindings: ~/.config/mpv/input.conf\n"
"#\n"
"# Lines starting with # are comments. Use SHARP to assign the # key.\n"
"# Copy this file and uncomment and edit the bindings you want to change.\n"
"#\n"
"# List of commands and further details: DOCS/man/input.rst\n"
"# List of special keys: --input-keylist\n"
"# Keybindings testing mode: mpv --input-test --force-window --idle\n"
"#\n"
"# Use 'ignore' to unbind a key fully (e.g. 'ctrl+a ignore').\n"
"#\n"
"# Strings need to be quoted and escaped:\n"
"#   KEY show-text \"This is a single backslash: \\\\ and a quote: \\\" !\"\n"
"#\n"
"# You can use modifier-key combinations like Shift+Left or Ctrl+Alt+x with\n"
"# the modifiers Shift, Ctrl, Alt and Meta (may not work on the terminal).\n"
"#\n"
"# The default keybindings are hardcoded into the mpv binary.\n"
"# You can disable them completely with: --no-input-default-bindings\n"
"\n"
"# Developer note:\n"
"# On compilation, this file is baked into the mpv binary, and all lines are\n"
"# uncommented (unless '#' is followed by a space) - thus this file defines the\n"
"# default key bindings.\n"
"\n"
"# If this is enabled, treat all the following bindings as default.\n"
"#default-bindings start\n"
"\n"
"#MBTN_LEFT     ignore              # don't do anything\n"
"#MBTN_LEFT_DBL cycle fullscreen    # toggle fullscreen on/off\n"
"#MBTN_RIGHT    cycle pause         # toggle pause on/off\n"
"\n"
"# Mouse wheels, touchpad or other input devices that have axes\n"
"# if the input devices supports precise scrolling it will also scale the\n"
"# numeric value accordingly\n"
"#WHEEL_UP      seek 10\n"
"#WHEEL_DOWN    seek -10\n"
"#WHEEL_LEFT    add volume -2\n"
"#WHEEL_RIGHT   add volume 2\n"
"\n"
"## Seek units are in seconds, but note that these are limited by keyframes\n"
"#RIGHT seek  5\n"
"#LEFT  seek -5\n"
"#UP    seek  60\n"
"#DOWN  seek -60\n"
"# Do smaller, always exact (non-keyframe-limited), seeks with shift.\n"
"# Don't show them on the OSD (no-osd).\n"
"#Shift+RIGHT no-osd seek  1 exact\n"
"#Shift+LEFT  no-osd seek -1 exact\n"
"#Shift+UP    no-osd seek  5 exact\n"
"#Shift+DOWN  no-osd seek -5 exact\n"
"# Skip to previous/next subtitle (subject to some restrictions; see manpage)\n"
"#Ctrl+LEFT   no-osd sub-seek -1\n"
"#Ctrl+RIGHT  no-osd sub-seek  1\n"
"#PGUP add chapter 1                     # skip to next chapter\n"
"#PGDWN add chapter -1                   # skip to previous chapter\n"
"#Shift+PGUP seek 600\n"
"#Shift+PGDWN seek -600\n"
"#[ multiply speed 0.9091                # scale playback speed\n"
"#] multiply speed 1.1\n"
"#{ multiply speed 0.5\n"
"#} multiply speed 2.0\n"
"#BS set speed 1.0                       # reset speed to normal\n"
"#q quit\n"
"#Q quit-watch-later\n"
"#q {encode} quit 4\n"
"#ESC set fullscreen no\n"
"#ESC {encode} quit 4\n"
"#p cycle pause                          # toggle pause/playback mode\n"
"#. frame-step                           # advance one frame and pause\n"
"#, frame-back-step                      # go back by one frame and pause\n"
"#SPACE cycle pause\n"
"#> playlist-next                        # skip to next file\n"
"#ENTER playlist-next                    # skip to next file\n"
"#< playlist-prev                        # skip to previous file\n"
"#O no-osd cycle-values osd-level 3 1    # cycle through OSD mode\n"
"#o show-progress\n"
"#P show-progress\n"
"#i script-binding stats/display-stats\n"
"#I script-binding stats/display-stats-toggle\n"
"#z add sub-delay -0.1                   # subtract 100 ms delay from subs\n"
"#x add sub-delay +0.1                   # add\n"
"#ctrl++ add audio-delay 0.100           # this changes audio/video sync\n"
"#ctrl+- add audio-delay -0.100\n"
"#9 add volume -2\n"
"#/ add volume -2\n"
"#0 add volume 2\n"
"#* add volume 2\n"
"#m cycle mute\n"
"#1 add contrast -1\n"
"#2 add contrast 1\n"
"#3 add brightness -1\n"
"#4 add brightness 1\n"
"#5 add gamma -1\n"
"#6 add gamma 1\n"
"#7 add saturation -1\n"
"#8 add saturation 1\n"
"#Alt+0 set window-scale 0.5\n"
"#Alt+1 set window-scale 1.0\n"
"#Alt+2 set window-scale 2.0\n"
"# toggle deinterlacer (automatically inserts or removes required filter)\n"
"#d cycle deinterlace\n"
"#r add sub-pos -1                       # move subtitles up\n"
"#t add sub-pos +1                       #                down\n"
"#v cycle sub-visibility\n"
"# stretch SSA/ASS subtitles with anamorphic videos to match historical\n"
"#V cycle sub-ass-vsfilter-aspect-compat\n"
"# switch between applying no style overrides to SSA/ASS subtitles, and\n"
"# overriding them almost completely with the normal subtitle style\n"
"#u cycle-values sub-ass-override \"force\" \"no\"\n"
"#j cycle sub                            # cycle through subtitles\n"
"#J cycle sub down                       # ...backwards\n"
"#SHARP cycle audio                      # switch audio streams\n"
"#_ cycle video\n"
"#T cycle ontop                          # toggle video window ontop of other windows\n"
"#f cycle fullscreen                     # toggle fullscreen\n"
"#s async screenshot                     # take a screenshot\n"
"#S async screenshot video               # ...without subtitles\n"
"#Ctrl+s async screenshot window         # ...with subtitles and OSD, and scaled\n"
"#Alt+s screenshot each-frame            # automatically screenshot every frame\n"
"#w add panscan -0.1                     # zoom out with -panscan 0 -fs\n"
"#e add panscan +0.1                     #      in\n"
"# cycle video aspect ratios; \"-1\" is the container aspect\n"
"#A cycle-values video-aspect \"16:9\" \"4:3\" \"2.35:1\" \"-1\"\n"
"#POWER quit\n"
"#PLAY cycle pause\n"
"#PAUSE cycle pause\n"
"#PLAYPAUSE cycle pause\n"
"#STOP quit\n"
"#FORWARD seek 60\n"
"#REWIND seek -60\n"
"#NEXT playlist-next\n"
"#PREV playlist-prev\n"
"#VOLUME_UP add volume 2\n"
"#VOLUME_DOWN add volume -2\n"
"#MUTE cycle mute\n"
"#CLOSE_WIN quit\n"
"#CLOSE_WIN {encode} quit 4\n"
"#E cycle edition                        # next edition\n"
"#l ab-loop                              # Set/clear A-B loop points\n"
"#L cycle-values loop-file \"inf\" \"no\"    # toggle infinite looping\n"
"#ctrl+c quit 4\n"
"#DEL script-binding osc/visibility      # cycle OSC display\n"
"\n"
"# Apple Remote section\n"
"#AR_PLAY cycle pause\n"
"#AR_PLAY_HOLD quit\n"
"#AR_CENTER cycle pause\n"
"#AR_CENTER_HOLD quit\n"
"#AR_NEXT seek 10\n"
"#AR_NEXT_HOLD seek 120\n"
"#AR_PREV seek -10\n"
"#AR_PREV_HOLD seek -120\n"
"#AR_MENU show-progress\n"
"#AR_MENU_HOLD cycle mute\n"
"#AR_VUP add volume 2\n"
"#AR_VUP_HOLD add chapter 1\n"
"#AR_VDOWN add volume -2\n"
"#AR_VDOWN_HOLD add chapter -1\n"
"\n"
"#\n"
"# Legacy bindings (may or may not be removed in the future)\n"
"#\n"
"#! add chapter -1                       # skip to previous chapter\n"
"#\100 add chapter 1                        #         next\n"
"\n"
"#\n"
"# Not assigned by default\n"
"# (not an exhaustive list of unbound commands)\n"
"#\n"
"\n"
"# ? add sub-scale +0.1                  # increase subtitle font size\n"
"# ? add sub-scale -0.1                  # decrease subtitle font size\n"
"# ? sub-step -1                         # immediately display next subtitle\n"
"# ? sub-step +1                         #                     previous\n"
"# ? cycle angle                         # switch DVD/Bluray angle\n"
"# ? add balance -0.1                    # adjust audio balance in favor of left\n"
"# ? add balance 0.1                     #                                  right\n"
"# ? cycle sub-forced-only               # toggle DVD forced subs\n"
"# ? cycle program                       # cycle transport stream programs\n"
"# ? stop                                # stop playback (quit or enter idle mode)\n"
