include ../config.mak

LIBNAME_MPLAYER = libmenu.a

SRCS_MPLAYER = menu.c \
               vf_menu.c \
               menu_cmdlist.c  \
               menu_pt.c \
               menu_list.c  \
               menu_filesel.c \
               menu_txt.c \
               menu_console.c \
               menu_param.c \

SRCS_MPLAYER-$(DVBIN) += menu_dvbin.c

include ../mpcommon.mak
