.\" MPlayer (C) 2000-2002 Arpad Gereoffy <sendmail@to.mplayer-users>
.\" English version and hungarian translation by Gabucino
.\"
.TH MPlayer
.SH NAME
mplayer \- Filmlejátszó Linuxra
.SH VÁZLAT
.B mplayer
.RB [ \-gui ]
.RB [ \-v ]
.RB [ \-help / -h / --help ]
.RB [ \-quiet ]
.RB [ \-vo\ <meghajtó>[:<egység>] ]
.RB [ \-ao\ <meghajtó>[:<egység>] ]
.RB [ \-vcd\ <sáv> ]
.RB [ \-cdrom-pathname\ <útvonal> ]
.RB [ \-sb\ <byte\ pozíció> ]
.RB [ \-nosound ]
.RB [ \-audiofile\ <filenév> ]
.RB [ \-abs\ <byte-ok> ]
.RB [ \-delay\ <másodperc> ]
.RB [ \-nobps ]
.RB [ \-aid\ <id> ]
.RB [ \-vid\ <id> ]
.RB [ \-fps\ <ráta> ]
.RB [ \-mc\ <másodperc/5kocka> ]
.RB [ \-fs ]
.RB [ \-dr ]
.RB [ \-vm ]
.RB [ \-zoom ]
.RB [ \-x\ <x> ]
.RB [ \-y\ <y> ]
.RB [ \-sws\ <szoftveres\ skálázó\ minõsége> ]
.RB [ \-xy\ <faktor> ]
.RB [ \-pp\ <minõség> ]
.RB [ \-include\ <config\ file> ]
.RB [ \-lircconf\ <config\ file> ]
.RB [ \-ffactor\ <szám> ]
.RB [ \-sub\ <file> ]
.RB [ \-subfps\ <ráta> ]
.RB [ \-subdelay\ <másodperc> ]
.RB [ \-vobsub\ <vobsub\ file\ kiterjesztés\ nélkül> ]
.RB [ \-vobsubid\ <vobsub\ felirat\ id> ]
.RB [ \-ifo\ <vobsub\ ifo\ file> ]
.RB [ \-z\ <0-8> ]
.RB [ \-idx ]
.RB [ \-noidx ]
.RB [ \-forceidx ]
.RB [ \-nodshow ]
.RB [ \-noxv ]
.RB [ \-forcexv ]
.RB [ \-ss\ <másodperc> ]
.RB [ \-dumpaudio ]
.RB [ \-dumpvideo ]
.RB [ \-dumpstream ]
.RB [ \-noframedrop ]
.RB [ \-framedrop ]
.RB [ \-nodouble ]
.RB [ \-double ]
.RB [ \-stereo\ <mód> ]
.RB [ \-channels\ <n> ]
.RB [ \-srate\ <Hz> ]
.RB [ \-osdlevel\ <fokozat> ]
.RB [ \-config\ <file> ]
.RB [ \-display\ <név> ]
.RB [ \-xineramascreen\ <képernyõ\ száma> ]
.RB [ \-wid\ <ablak\ id> ]
.RB [ \-unicode ]
.RB [ \-utf8 ]
.RB [ \-fsmode\ <mód> ]
.RB [ \-vc\ <video\ codec\ neve> ]
.RB [ \-ac\ <audio\ codec\ neve> ]
.RB [ \-vfm\ <video\ codec\ család> ]
.RB [ \-afm\ <audio\ codec\ család> ]
.RB [ \-frames\ <szám> ]
.RB [ \-autoq\ <minõség> ]
.RB [ \-fb\ <egység> ]
.RB [ \-fbmode\ <módnév> ]
.RB [ \-fbmodeconfig\ <filenév> ]
.RB [ \-monitor_hfreq\ <horizontális\ frekvencia\ tartomány> ]
.RB [ \-monitor_vfreq\ <vertikális\ frekvencia\ tartomány> ]
.RB [ \-monitor_dotclock\ <dotclock\ (vagy\ pixelclock)\ tartomány> ]
.RB [ \-benchmark ]
.RB [ \-dvd\ <cím> ]
.RB [ \-dvd-device\ <útvonal> ]
.RB [ \-chapter\ fejezet ]
.RB [ \-dvdangle\ szög ]
.RB [ \-alang\ <audio\ stream\ nyelve> ]
.RB [ \-slang\ felirat\ nyelve ]
.RB [ \-sid\ <id> ]
.RB [ \-dvdkey\ <kulcs> ]
.RB [ \-skin\ <skin\ neve> ]
.RB [ \-aspect\ <ratio> ]
.RB [ \-monitoraspect <ratio> ]
.RB [ \-subcp\ <kódlap> ]
.RB [ \-dumpmpsub ]
.RB [ \-dumpfile ]
.RB [ \-dumpsub ]
.RB [ \-screenw\ <pixel> ]
.RB [ \-screenh\ <pixel> ]
.RB [ \-cache\ <kbyte> ]
.RB [ \-bpp\ <mélység> ]
.RB [ \-flip ]
.RB [ \-playlist\ <file> ]
.RB [ \-slave ]
.RB [ \-loop\ <num> ]
.RB [ \-mixer\ <eszköz> ]
.RB [ \-tv\ <alopciók> ]
.RB [ \-dapsync ]
.RB [ \-softsleep ]
.RB [ \-rootwin ]
.RB [ \-font\ <útvonal\ a\ font.desc\ file-hoz> ]
.RB [ \-conf\ <útvonal\ az\ input.conf\ file-hoz> ]
.RB [ \-input\ <parancsok> ]
.RB [ \-nojoystick ]
.RB [ \-nolirc ]
.RB [ \-demuxer\ <szám> ]
.RB [ \-audio-demuxer\ <szám> ]
.RB [ \-sub-demuxer\ <szám> ]
.RB [ \-hr-mp3-seek ]
.I < - | file | URL | eszköz >
.PP
.SH LEÍRÁS
.I mplayer
Az MPlayer egy LINUXON mûködõ videolejátszó (fut sok más Unix-on és akár
nem-x86 processzorokon is. Lásd a 6-os fejezetet). Le tudja játszani a legtöbb
MPEG, AVI, MOV/QT és ASF/WMV file-t, valamint felsorakoztat jónéhány natív és
Win32 codecet. Nézhetsz vele VideoCD-t, SVCD-t, DVD-t, és még DivX-et is
(ezutóbbihoz egyáltalán nincs szükség az avifile csomagra!).

A másik óriási tulajdonsága az MPlayernek a megjelenítési módok széles
választéka. Mûködik X11, Xv, DGA, OpenGL, SVGAlib, fbdev, AAlib, DirectFB, GGI, SDL
(beleértve ezáltal a GGI és SDL drivereit is), VESA, és néhány alacsonyszintû
kártyaspecifikus driver (Matrox/3dfx/Radeon) is használható! Legtöbbjük támogat
szoftveres vagy hardveres nagyítást, így a teljesképernyõs mód is elérhetõ.

Sok felirattipus támogatott (jelenleg 9!), és ezek szép antialiasolt
fontokkal kerülnek megjelenítésre. Természetesen az ISO 8859-1,2 fontok
támogatva vannak.
.LP
.SH "GUI OPCIÓK"
.I MEGJEGYZÉS:
A GUI kód lefordítását *külön* engedélyezni kell, a részletekhez lásd
a dokumentációt.
.TP
.B \-gui
MPlayer indítása GUI módban.
.TP
.B \-skin skin directory
a megadott könyvtárban található skin használata (útvonal NÉLKÜL!).
Például a '-skin fittyfene' ezeket próbálja végig :

    /usr/local/share/mplayer/Skin/fittyfene
    ~/.mplayer/Skin/fittyfene
.LP
.SH "DVD OPCIÓK"
.I MEGJEGYZÉS:
Ezek az opciók csak a DVD támogatás befordítása után elérhetõek. A részletekhez
lásd a dokumentációt.
.B \-dvd\ <cím>
megadja hogy az MPlayer a DVD-n található mely filmeket (amiket számokkal
jelölnek) játssza le. Például az 1-esek általában elõzetesek, és a 2 az
igazi film.
.TP
.B \-dvd-device\ <útvonal>
az alapértelmezett /dev/dvd helyett más egység használata
.TP
.B \-sid\ <id>
Bekapcsolja a DVD feliratok megjelenítését. Szükséges egy DVD feliratazonosító
(0-31) szám megadása. A lehetséges nyelvek listája az ennek és a -v opciónak
az együttes használata során lesz olvasható a kimenetben.
.TP
.B \-chapter\ <fejezet>
megadja hogy melyik fejezetnél kezdõdjön a lejátszás. Meg lehet azt is adni,
hogy melyiknél fejezõdjön be. Példákat lásd lent.
.TP
.B \-dvdangle\ <szög>
néhány DVD lemez olyan jeleneteket tartalmaz, amelyeket más kameraállásból
is meg lehet tekinteni. Itt lehet megadni az MPlayernek hogy melyik
kameraállást használja. Példákat lásd lent.
.TP
.B \-alang\ <audio\ stream\ nyelve>
DVD lemezek lejátszásánál használatos. Kétbetûs országkódot illetve kódokat
fogad el paraméterként, és mindig az adott kódnak megfeleló audio stream-et
próbálja lejátszani. Például: -alang hu,en mindig elõször magyar, vagy ha
az nincs akkor angol hanggal játszik le DVD-t.
.TP
.B \-slang\ <felirat\ nyelve>
Lásd az elõzõ opciót, de ez egy kétbetûs országkódot fogad el paraméterként.
Például a -slang hu,en opció mindig magyar, vagy ha az nincs akkor angol
feliratokat fog kiválasztani, ha lehetséges.
.LP
.SH "ÁLTALÁNOS OPCIÓK"
.TP
.I MEGJEGYZÉS
Minden paraméter nélküli opciónak megvan az ellenpárja, például az "-fs"-nek
"-nofs"
.TP
.B \-vo\ <meghajtó>[:<eszköz>]
a video kimeneti meghajtó és opcionálisan az eszköz kiválasztása.
Az "eszköz" az SDL-nél és GGI-nél az almeghajtókat jelöli. (pl: -vo sdl:aalib).

A rendelkezésre álló meghajtók listáját a következõ opcióval lehet
lekérni :
.I mplayer -vo help

.TP
.B \-ao\ <meghajtó>[:<eszköz>]
az audio kimeneti meghajtó és opcionálisan az eszköz kiválasztása.
Az "eszköz" az SDL-nél az almeghajtókat jelöli. (pl: -vo sdl:esd).

OSS használatakor a használni kívánt eszközt lehet megadni :
-ao oss:/dev/dsp1

A rendelkezésre álló meghajtók listáját a következõ opcióval lehet
lekérni :
.I mplayer -ao help

.TP
.B \-vcd\ <sáv>
Video CD sáv lejátszása file helyett
.TP
.B \-cdrom-device\ <útvonal>
az alapértelmezett /dev/cdrom helyett más egység használata
.TP
.B \-nosound
hang nélküli lejátszás
.TP
.B \-audiofile <filenév>
audio film melletti lejátszása külsõ fileból (MP3, AC3, Vorbis, stb)
.TP
.B \-fs
teljesképernyõs lejátszás (középre helyezi a filmet, és fekete sávokat
tesz köré). Ki/bekapcsolható az 'f' billentyûvel (nem mindegyik video
kimenet támogatja).
.TP
.B \-dr
direct rendering bekapcsolása (nem minden codec illetve video kimenet
támogatja). Alapállapotban ki van kapcsolva.
.TP
.B \-vm
megpróbál videomódot váltani. A dga2, x11 (XF86VidMode) és sdl meghajtóknál
használható.
.TP
.B \-zoom
szoftveres nagyítás használata, ahol rendelkezésre áll (-nofs kell). svga, x11,
vesa kimenetek támogatják.
.TP
.B \-flip
kép megfordítása (hasznos például a régi Indeo codec-eknél). Csak(?) az
'sdl' és 'x11' kimenetek támogatják.
.TP
.B \-x\ <x>
kép nagyítása x pixel szélességûre [ha a meghajtó támogatja!]
.TP
.B \-y\ <y>
kép nagyítása y pixel magasságúra [ha a meghajtó támogatja!]
.TP
.B \-sws\ <szoftveres\ skálázó\ minõsége>
ez az opció a -zoom opcióval bekapcsolható szoftveres skálázó minõségét (és
ezzel együtt a sebességét is) befolyásolja, például x11 vagy más, hardveres
gyorsítással nem rendelkezõ kimenetek használatának esetén. A lehetséges
beállítások :

    0 - gyors bilinear (alapértelmezett)
    1 - bilinear
    2 - bicubic (legjobb minõség)
    3 - ?
    4 - nearest neighbor (rossz minõség)
    5 - area averageing scaling support

.TP
.B \-xy\ <factor>
a kép nagyítása <factor>-szorosra
.TP
.B \-autoq\ <minõség>
a képjavítás mértékének dinamikus változtatása, a rendelkezésre álló
processzoridõ függvényében. Ugyanazok a beállításai mint a -pp-nek. A
szám amit megadsz az számít a maximumnak. Általában egy megfelelõen
magas szám megadása az ajánlott. Nem lehet a -pp-vel együtt használni!
.TP
.B \-ffactor\ <szám>
a betûk körvonalának beállítása. Lehetséges beállítások:

        0    körvonal nélkül
        0.75 nagyon vékony fekete körvonal [alap]
        1    vékony fekete körvonal
        10   vastag fekete körvonal
.TP
.B \-sub\ <felirat\ file>
a megadott feliratfile használata
.TP
.B \-subfps\ <ráta>
a feliratfile képkocka/másodperc értékének megadása (CSAK képkocka-alapú
fileoknál lehetséges!) Alapállapot: a film kk/mp értéke.
.TP
.B \-subdelay\ <másodperc>
a feliratok kezdõidejének késleltetése a megadott idõtartammal. Lehet
negatív is.
.TP
.B \-vobsub\ <vobsub\ file\ kiterjesztés\ nélkül>
vobsub tipusú felirat használata esetén itt adandók meg a feliratot tartalmazó
file-ok. Kiterjesztések (.idx, .ifo, .sub) nélkül kell megadni !
.TP
.B \-vobsub\ <vobsub\ felirat\ id>
amennyiben a vobsub-ban több felirat is van, itt lehet kiválasztani hogy
melyik legyen használva (0-31).
.TP
.B \-ifo <vobsub ifo file>
az itt megadott file-ban találhatõ paletta és frameméret adatok lesznek
használva a VOBSUB feliratok megjelenítésénél.
.TP
.B \-osdlevel\ <fokozat>
megadja hogy az OSD milyen módban induljon (0 : nincs, 1 : keresõ, 2: keresõ+timer)
(alap = 2)
.TP
.B \-lircconf\ <config\ file>
LIRC konfigurációs file megadása (lásd http://www.lirc.org), ha a ~/.lircrc-tõl
eltérõ helyen van
.TP
.B \-v
bõvebb kimenet bekapcsolása (minél több -v, annál részletesebb)
.TP
.B \-quiet
kevesebb kimenet bekapcsolása
.TP
.B \-benchmark
a -nosound-dal, és -vo null-lal használatos, sebességmérésre
.TP
.B \-aspect <ratio>
a film aspektusarányának beállítása. MPEG file-oknál detektálódik,
de AVI-knál nem. Példák:

    -aspect 4:3  vagy -aspect 1.3333
    -aspect 16:9 vagy -aspect 1.7777

.TP
.B \-monitoraspect <ratio>
a képernyõ aspektusarányának beállítása. Példák:

    -monitoraspect 4:3  vagy 1.3333
    -monitoraspect 16:9 vagy 1.7777

.TP
.B \-playlist <file>
az itt megadott fileban található fileok lejátszása (1 file/sor vagy ASX
illetve Winamp formátum).
.TP
.B \-ss\ <idõ>
lejátszás kezdése a megadott idõponttól. Például:

    -ss 56
    -ss 01:10:00

.TP
.B -loop\ <num>
Többszörös lejátszás. A 0-ás érték végtelenített lejátszást eredményez.
.TP
.B \-mixer\ <eszköz>
Ezzel az opcióval lehet megadni az MPlayer-nek hogy a /dev/mixer helyett
más eszközt használjon.
.TP
.B \-master
Már nem használt opció, használd helyette a Szoftveres audio mixer plugint
(lásd DOCS).
.IP
.B \-tv\ <alopciók>
Ez az opció TV-nézõ üzemmódba kapcsolja az MPlayer-t. A további dokumentáció
a documentation.html file 2.5-ös fejezetében található.
.TP
.B \-rootwin
új ablak megnyitása helyett a desktop hátterében (root window) történik a
lejátszás. Csak az xv és xmga meghajtókkal mûködik.
.TP
.B \-font\ <útvonal\ a\ font.desc\ file-hoz>
az alapértelmezettõl eltérõ betûtipus használata (alap:
~/.mplayer/font/font.desc).
Például:

    -font ~/.mplayer/arial-14/font.desc
.TP
.B \-font\ <útvonal\ az\ input.conf\ file-hoz>
az alapértelmezettõl eltérõ helyen lévõ input.conf betöltése (alap:
~/.mplayer/input.conf).
.IP
.SH "HALADÓSZINTÛ OPCIÓK"
.TP
.I MEGJEGYZÉS
Ezek az opciók jó eséllyel megoldást jelenthetnek esetleges lejátszási
gondjaidra.. Továbbá, olvasd el a dokumentációt !
.TP
.B \-vc <név>
a megadott video codec használata, a codecs.conf-ban szereplõ név szerint,
például :

    -vc divx       VFW DivX codec
    -vc divxds     DirectShow DivX codec
    -vc ffdivx     libavcodec DivX codec
    -vc ffmpeg12   libavcodec MPEG1/2 codec
    -vc divx4      ProjectMayo DivX codec

Teljes listát a '-vc help' ad !
.TP
.B \-ac <name>
a megadott audio codec használata, a codecs.conf-ban szereplõ név szerint,
például :

    -ac mp3        libmp3 MP3 codec
    -ac mp3acm     l3codeca.acm MP3 codec
    -ac ac3        AC3 codec
    -ac hwac3      hardveres AC3 használata
                   (lásd dokumentáció)
    -ac vorbis     libvorbis
    -ac ffmp3      ffmpeg MP3 decoder (lassú)

Teljes listát az '-ac help' ad !

.B \-vfm <1-12>
megadott video codec CSALÁD használata, ha nem található benne megfelelõ
dekóder, akkor vissza az automatikus detektálásra. Példák :

    -vfm 2         VFW (Win32) codec-ek
    -vfm 3         OpenDivX/DivX4 codec-ek (YV12)
                   (ugyanaz mint -vc odivx, de lásd fent)
    -vfm 4         DirectShow (Win32) codec-ek
    -vfm 5         libavcodec codec-ek
    -vfm 7         DivX4 codec (YUY2)
    -vfm 10        XAnim codec-ek

Teljes listát a '-vc help' ad !

.I MEGJEGYZÉS:
ha a libdivxdecore támogatást is befordítottad, a 3-as és 7-es ugyanazt a DivX4
codec-et fogja tartalmazni, a különbségeket lásd a dokumentációban.
.TP
.B \-afm <1-12>
megadott audio formátum használata. Példák:

    -afm 1         libmp3 (mp2/mp3,
                   de nincs mp1)
    -afm 2         tömörítetlen PCM audio
    -afm 3         libac3
    -afm 4         megfelelõ Win32 codec
    -afm 5         aLaw/uLaw meghajtó
    -afm 10        libvorbis
    -afm 11        ffmpeg MP3 dekódere

Teljes listát az '-ac help' ad !
.TP
.B \-sb\ <pozíció>
lejátszás kezdése a megadott byte-tól
.TP
.B \-bpp\ <mélység>
a megadott színmélység használata, a detektált érték helyett. Nem minden
-vo meghajtó támogatja (fbdev, dga2, svga, vesa).
.TP
.B \-pp <minõség>
lásd az angol manpage-t.
.TP
.B \-slave
Ez az opció bekapcsolja a "slave" módot. Ez az üzemmód az MPlayernek más
programokkal való kommunikációját segíti elõ. A billentyûzet figyelése helyett
a stdin-rõl jövõ parancsokra fog reagálni a lejátszó. Lásd a
.B SLAVE MODE PROTOCOL
fejezetet.
.TP
.B \-abs\ <byte>
hangkártya audio bufferének mérete (byte-okban, alap: mérés)
.TP
.B \-delay\ <másodperc>
audio késleltetés, másodpercben megadva (lehet negatív)
.TP
.B \-nobps
másik módszer használata a hang/kép szinkronhoz (AVI)
.TP
.B \-aid\ <id>
másik audio csatorna választása [MPG: 0-31 AVI: 1-99 ASF: 0-127 VOB: 128-...]
.TP
.B \-vid\ <id>
másik video csatorna választása [MPG: 0-15  AVI:  -- ]
.TP
.B \-fps\ <érték>
képkocka/másodperc érték felülbírálása (ha a fejlécben rosszul szerepel)
.TP
.B \-mc\ <másodperc/5képkocka>
maximális szinkronkorrekció, 5 másodperc alatt (másodpercben)
.TP
.B \-ni
non-interleaved AVI feltételezése (hibás AVI-knál segíthet)
.TP
.B \-include configfile
az itt megadott konfigurációs file használata, az alapértelmezett file után
.TP
.B \-z\ <0-8>
a PNG kimenet tömörítési fokának megadása
          0 : nincs tömörítés
          8 : maximális tömörítés
.TP
.B \-idx
az AVI indexének újraépítése, ha a file nem tartalmaz. Hibásan/részlegesen
letöltött vagy rosszul létrehozott fileoknál használatos.
.TP
.B \-noidx
az AVI indexének figyelmen kívül hagyása. Hibás index-û (jele pl a hang/kép
deszinkronizáció) file-oknál használható. A seekelés NEM lesz lehetséges.
A MEncoder véglegesen tudja javítani az ilyen file-okat, lásd a dokumentációt.
.TP
.B \-forceidx
index ujraépítésének kényszerítése. Hibás index-û (jele pl a hang/kép
deszinkronizáció) file-oknál használható. A seekelés lehetséges.
A MEncoder véglegesen tudja javítani az ilyen file-okat,
lásd a dokumentációt.
.TP
.B \-nodshow
DirectShow codec-ek használatának tiltása
.TP
.B \-noxv (csak SDL-lel!)
XVideo hardveres gyorsítás kikapcsolása
.TP
.B \-forcexv (csak SDL-lel!)
XVideo használatának kényszerítése
.TP
.B \-dumpaudio
a file-ban található audio kimentése a ./stream.dump file-ba
(leginkább mpeg/ac3-mal használható)
.TP
.B \-dumpstream
az egész stream-et kiírja a ./stream.dump file-ba.
Hasznos például DVD rippelésnél.
.TP
.B \-noframedrop
képkockaeldobás kikapcsolása : minden képkocka lejátszásra kerül, igy az
audio és video szinkron elcsúszhat (alapértelmezés)
.TP
.B \-framedrop
képkockaeldobás : minden képkocka dekódolása, a kép ugorhat
.TP
.B \-nodouble
duplánbufferelés kikapcsolása.
A DGA meghajtónál ez kikapcsolja az OSD-t is, de gyorsabb lesz a lejátszás.
.TP
.B \-dvdkey kulcs
kulcs, a CSS-el kódolt fileokhoz szükséges. Például : -dvdkey F169072699
(NEM DVD lejátszáshoz !! Arra ott a -dvd opció!)
.TP
.B \-stereo mód
MP2/MP3 sztereó kimenet tipusának kiválasztása

        Sztereó        0
        Bal csatorna   1
        Jobb csatorna  2

.TP
.B \-channels n
kimeneti audio csatornák számának kiválasztása

        Sztereó        2
        Térhatás       4
        Teljes 5.1     6

Jelenleg ez az opció csak AC3 audióhoz használható.
.TP
.B \-srate <Hz>
audio lejátszása a megadott frekvencián. A lejátszás sebességére van
hatással.
.TP
.B \-config <config\ file>
megadja hogy hol van a konfigurációs file
.TP
.B \-display <név>
gépnév és display-szám megadása, ha távoli X szerveren kell a képet
megjeleníteni. Például : -display xtest.localdomain:0
.TP
.B \-xineramascreen <szám>
Xinerama beállításoknál (azaz amikor egyetlen desktop van elosztva
több képernyõn) ezzel az opcióval lehet megadni hogy a lejátszó
ablak melyiken jelenjen meg. Lehetséges értékek : 0 - ...
.TP
.B \-wid <window id>
Az MPlayer ezek opció hatására egy már meglévõ X11 ablakban játszik le. Hasznos
például böngészõbe integrálásnál (pl a plugger kiegészítéssel).
.TP
.B \-unicode
ennek hatására az MPlayer UNICODE-ként kezeli a feliratfile-t. Ellentéte :
-nounicode
.TP
.B \-utf8
ennek hatására az MPlayer UTF8-ként kezeli a feliratfile-t.
.TP
.B \-fsmode\ mód
Ezzel az opcióval ki lehet kerülni néhány problémát amely egyes
ablakkezelõkkel és a teljesképernyõs móddal adódhat. 0 és 7 között lehet
változtatni :

        -fsmode 0      új módszer (alap)
        -fsmode 1      ICCCWM patch
                       (KDE2/icewm-hez)
        -fsmode 2      régi módszer
        -fsmode 3      ICCCWM patch
                       plusz Motif módszer
.TP
.B \-frames\ szám
Megadott számú képkocka lejátszása, majd kilépés
.TP
.B \-fb\ <egység> (csak FBdev-vel vagy DirectFB-vel)
Megadott framebuffer egység használata. Alapállapotban /dev/fb0 .
.TP
.B \-fbmode\ <módnév> (csak FBdev-vel)
Videomód megváltoztatása az /etc/fb.modes fileban szereplõ módok valamelyikére.
.TP
.I MEGJEGYZÉS
A VESA framebuffer nem támogatja a módváltást.
.TP
.B \-fbmodeconfig\ <filenév> (csak FBdev-vel)
A megadott konfigurációs file használata az /etc/fb.modes helyett.
.TP
.B \-monitor_hfreq <horizontális frekvenciatartomány>  (csak FBdev-vel)
.TP
.B \-monitor_vfreq <vertikális frekvenciatartomány>  (csak FBdev-vel)
.TP
.B \-monitor_dotclock <dotclock\ (vagy\ pixelclock) tartomány>  (csak FBdev-vel)
Lásd example.conf, és DOCS/video.html.
.TP
.B \-subcp\ kódlap
Ha a rendszered támogatja az iconv(3)-ot, ezzel az opcióval megadhatod hogy
milyen kódlapban van a felirat. Példák:

        -subcp latin2
        -subcp cp1250

.TP
.B \-dumpmpsub
A -sub opcióval megadott felirat file-t átkonvertálja az MPlayer saját
feliratformátumába, az MPsub-ba. Egy dump.mpsub file-t ír ki a jelenlegi
könyvtárba.
.TP
.B \-screenw\ <pixel>
Ha olyan kimeneti meghajtót használsz ami nem tudja megállapítani a
képernyõ méreteit (fbdev/x11 és/vagy TV kimenet), itt adhatod meg a
szélességet.
.TP
.B \-screenh\ <pixel>
Ha olyan kimeneti meghajtót használsz ami nem tudja megállapítani a
képernyõ méreteit (fbdev/x11 és/vagy TV kimenet), itt adhatod meg a
magasságot.
.TP
.B \-cache\ <kbyte>
Ezzel az opcióval megadható, hogy mennyi memóriát használjon az MPlayer a
megadott file/URL cache-elésére. Különösen a lassú elérésû hordozókon
hasznos. Alapállapotban kikapcsolva.
.TP
.B \-softsleep
pontos szoftveres idõzítõ használata. Van olyan hatékony mint az RTC, nem kell
hozzá root jogosultság, viszont több CPU az igen.
.TP
.B \-input <parancsok>
ezzel az opcioval az input rendszer bizonyos részeit lehet konfigurálni.
        conf=<file> alternatív input.conf file
                    használata
        ar-delay    késleltetés mennyisége (msec)
                    autorepeatig
        ar-rate     hány lenyomás/másodperc
                    legyen autorepeat-ben
        keylist     kiírja az összes bindelhetõ input eszközt
        cmdlist     kiírja az összes bindelhetõ parancsot
.TP
.I MEGJEGYZÉS
Az autorepeat-et jelenleg csak joystick támogatja.
.TP
.B \-nojoystick
joystick támogatás kikapcsolása. Alapállapot: bekapcsolva, ha be van fordítva.
.TP
.B \-nolirc
LIRC támogatás kikapcsolása.
.TP
.B \-demuxer <szám>
demuxer tipusának kényszerítése. A demuxers.h file-ban megadott ID kell,
mint paraméter.
.TP
.B \-audio-demuxer <szám>
audio demuxer tipusának kényszerítése. A demuxers.h file-ban megadott ID kell,
mint paraméter.
.TP
.B \-hr-mp3-seek
pontos MP3 seekelés. Akkor van használva ha külsõ MP3 file-ból történik az
audio lejátszás, mivel ilyenkor nagyon pontosan kell seekelni hogy az A/V
szinkron megmaradjon. Ez lassú lehet visszafelé tekerésnél.
.IP
.SH "ALPHA/BETA ÁLLAPOTÚ FUNKCIÓK"
.TP
.I MEGJEGYZÉS
Ezek csupán a teljesség igényének szem elõtt tartása miatt kerültek be
ide! Ha nem tudod mik ezek, NINCS szükséged rájuk! Mindenesetre, kétszer
is olvasd el a dokumentációt !
.TP
.B \-dumpvideo
video stream kiírása a ./stream.dump file-ba (csak MPEG-PS-nél)
(nem túl használható)
.TP
.B \-dapsync
alternatív A/V szinkron rutin használata. Mire jó?
.TP
.B \-subfile <filenév>
jelenleg használhatatlan. Ugyanaz mint az -audiofile, csak felirat
streamekre. (OggDS?)
.TP
.B \-sub-demuxer <szám>
felirat demuxer tipusának kényszerítése, a -subfile opcióhoz.
.IP
.SH IRÁNYÍTÁS A BILLENTYÛZETRÕL
.TP
.I MEGJEGYZÉS
.TP
	  <-  v.  ->      hátra/elõre tekerés 10 másodperccel

up v. down      hátra/elõre tekerés   1 perccel

pgup/pgdown     hátra/elõre tekerés  10 perccel

p v. SPACE      pillanatállj

q v. ESC        kilépés

+ v. -          audio késleltetés változtatása +- 0.1 mp-cel

/ v. *          hangerõ csökkentése/növelése

f               teljes képernyõs mód ki/bekapcsolása

o               OSD választás: nincs / keresõ / keresõ+timer

m               master/pcm hangerõállítás között váltás

z v. x          felirat késleltetésének változtatása +- 0.1 mp-cel

(a következõk csak a -vo xv VAGY -vo [vesa|fbdev]:vidix VAGY -vo xvidix video
meghajtók, VAGY a lassú -vc divxds használatakor élnek)

1 v. 2          kontraszt állítása

3 v. 4          fényerõ állítása

5 v. 6          hue állítása

7 v. 8          szaturáció állítása

.IP
.SH SLAVE MODE PROTOCOL
Ha meg van adva a -slave opció, a lejátszás a következõ parancsokkal
befolyásolható:
.TP
       stop            pillanatállj

play            lejátszás folytatása

seek <NUM>      folytatás NUM másodperctõl

skip <NUM>      NUM másodperc átugrása (lehet negatív)

quit            kilépés

.IP
.SH FILE-OK ÉS KÖNYVTÁRAK
.TP
.I KONFIGURÁCIÓS FILE-OK
A beállítások rendszerszinten a /etc/mplayer.conf file-ban
tárolódnak, felhasználónként pedig a $HOME/.mplayer/config fileban.
A $HOME/.mplayer könyvtár és a benne lévõ 'config' file létrehozásra
kerül, ha nem létezik.
.TP
.I BETÛTIPUSOK
A betûtipusok helye a $HOME/.mplayer/font könyvtáron belül van.
Kell lennie ott egy font.desc file-nak, és .RAW kiterjesztésû
betûtipusoknak.
.TP
.I FELIRATFILEOK
Az MPlayer jelenleg 10 fajtát támogat : MicroDVD, SubRip, unnamed,
SAMI (smi), vplayer, RealMedia RT, ssa (Sub Station Alpha), AQT, VobSub, MPsub.
A fileokat ebben a sorrendben keresi : (például /mnt/cdrom/movie.avi)
    /mnt/cdrom/movie.sub
     (utf/UTF/sub/SUB/srt/SRT/smi/SMI/rt/RT/txt/TXT/ssa/SSA)
    $HOME/.mplayer/sub/movie.sub
     (utf/UTF/sub/SUB/srt/SRT/smi/SMI/rt/RT/txt/TXT/ssa/SSA)
    $HOME/.mplayer/default.sub
.IP
.SH "PÉLDÁK"
.B DVD lejátszás
mplayer -dvd 1
.TP
.B DVD lejátszás, csak 5, 6 és 7-es fejezeteket
mplayer -dvd 1 -chapter 5-7
.TP
.B DVD lejátszás más kameraállásból
mplayer -dvd 1 -dvdangle 2
.TP
.B Lejátszás más DVD egységrõl
mplayer -dvd 1 -dvd-device /dev/dvd2
.TP
.B HTTP-rõl lejátszás
mplayer http://mplayer.hq/example.avi
.TP
.B Felirat konvertálása MPsub formátumba (./dump.mpsub file-ba)
mplayer csali.avi -sub forras.sub -dumpmpsub
.LP
.SH HIBÁK
Biztos vannak. Lásd dokumentáció.

.LP
.SH KÉSZÍTÕK
Lásd dokumentáció.

MPlayer is (C) 2000-2002
.I Arpad Gereoffy <sendmail@to.mplayer-users>

Az angol manpage-t készítette
.I Gabucino.

A magyar fordítást készítette
.I Gabucino.
.LP
.SH FIGYELMEZTETÉS
A programból eredõ esetleges károkért a készítõk NEM vállalnak semmilyen
felelõsséget!
.\" end of file
