# Set if you are using your own HTML stylesheet...
#HTML_STYLESHEET = mystyle.css

# Change to yes to enable symlinking missing files to English master versions
USE_SYMLINKS = no

# Dependency information.
$(HTMLDIR)/index.html $(HTMLDIR)/MPlayer.html: $(wildcard *.xml)

include ../Makefile.inc
