.TH fbset 8 "July 1998" local "Linux frame buffer utils"
.SH NAME
fbset \- show and modify frame buffer device settings
.SH SYNOPSIS
.B fbset
.RI [ options ]
.RI [ mode ]
.SH DESCRIPTION
.B This documentation is out of date!!
.PP
.B fbset
is a system utility to show or change the settings of the frame buffer
device. The frame buffer device provides a simple and unique interface to
access different kinds of graphic displays.
.PP
Frame buffer devices are accessed via special device nodes located in the
/dev directory. The naming scheme for these nodes is always
.IR \fBfb < n >,
where
.I n
is the number of the used frame buffer device.
.PP
.B fbset
uses an own video mode database located in /etc/fb.modes. An unlimited
number of video modes can be defined in this database. For further
information see
.BR fb.modes (5).
.SH OPTIONS
If no option is given,
.B fbset
will display the current frame buffer settings.
.sp
General options:
.RS
.TP
.BR \-\-help ",\ " \-h
display an usage information
.TP
.BR \-\-now ",\ " \-n
change the video mode immediately. If no frame buffer device is given via
.B \-fb
, then this option is activated by default
.TP
.BR \-\-show ",\ " \-s
display the video mode settings. This is default if no further option or
only a frame buffer device via
.B \-fb
is given
.TP
.BR \-\-info ",\ " \-i
display all available frame buffer information
.TP
.BR \-\-verbose ",\ " \-v
display information what
.B fbset
is currently doing
.TP
.BR \-\-version ",\ " \-V
display the version information about
.B fbset
.TP
.BR \-\-xfree86 ",\ "  \-x
display the timing information as it's needed by XFree86
.RE
.PP
Frame buffer device nodes:
.RS
.TP
.BR \-fb "\ <" \fIdevice >
.I device
gives the frame buffer device node. If no device via
.B \-fb
is given, 
.I /dev/fb0
is used
.TP
.RE
.PP
Video mode database:
.RS
.TP
.BR \-db "\ <" \fIfile >
set an alternative video mode database file (default is 
.IR /etc/fb.modes ),
see also
.BR fb.modes (5)
.RE
.PP
Display geometry:
.RS
.TP
.BR \-xres "\ <" \fIvalue >
set visible horizontal resolution (in pixels)
.TP
.BR \-yres "\ <" \fIvalue >
set visible vertical resolution (in pixels)
.TP
.BR \-vxres "\ <" \fIvalue >
set virtual horizontal resolution (in pixels)
.TP
.BR \-vyres "\ <" \fIvalue >
set virtual vertical resolution (in pixels)
.TP
.BR \-depth "\ <" \fIvalue >
set display depth (in bits per pixel)
.TP
.BR \-\-geometry ",\ " \-g "\ ..."
set all geometry parameters at once in the order
.RI < xres >
.RI < yres >
.RI < vxres >
.RI < vyres >
.RI < depth >,
e.g.
.B \-g
.I 640 400 640 400 4
.TP
.BR \-match "\ \ \ \ \ \ "
make the physical resolution match the virtual resolution
.RE
.PP
Display timings:
.RS
.TP
.BR \-pixclock "\ <" \fIvalue >
set the length of one pixel (in picoseconds). Note that the frame buffer
device may only support some pixel lengths
.TP
.BR \-left "\ <" \fIvalue >
set left margin (in pixels)
.TP
.BR \-right "\ <" \fIvalue >
set right margin (in pixels)
.TP
.BR \-upper "\ <" \fIvalue >
set upper margin (in pixel lines)
.TP
.BR \-lower "\ <" \fIvalue >
set lower margin (in pixel lines)
.TP
.BR \-hslen "\ <" \fIvalue >
set horizontal sync length (in pixels)
.TP
.BR \-vslen "\ <" \fIvalue >
set vertical sync length (in pixel lines)
.TP
.BR \-\-timings ",\ " \-t "\ ..."
set all timing parameters at once in the order
.RI < pixclock >
.RI < left >
.RI < right >
.RI < upper >
.RI < lower >
.RI < hslen >
.RI < vslen >,
e.g.
.B \-g
.I 35242 64 96 35 12 112 2
.RE
.PP
Display flags:
.RS
.TP
.IR \fB\-hsync "\ {" low | high }
set the horizontal sync polarity
.TP
.IR \fB\-vsync "\ {" low | high }
set the vertical sync polarity
.TP
.IR \fB\-csync "\ {" low | high }
set the composite sync polarity
.TP
.IR \fB\-extsync "\ {" false | true }
enable or disable external resync. If enabled the sync timings are not
generated by the frame buffer device and must be provided externally
instead. Note that this option may not be supported by every frame buffer
device
.TP
.IR \fB\-bcast "\ {" false | true }
enable or disable broadcast modes. If enabled the frame buffer generates the
exact timings for several broadcast modes (e.g. PAL or NTSC). Note that
this option may not be supported by every frame buffer device
.TP
.IR \fB\-laced "\ {" false | true }
enable or disable interlace. If enabled the display will be split in two
frames, each frame contains only even and odd lines respectively. These two
frames will be displayed alternating, this way twice the lines can be
displayed and the vertical frequency for the monitor stays the same, but the
visible vertical frequency gets halved
.TP
.IR \fB\-double "\ {" false | true }
enable or disable doublescan. If enabled every line will be displayed twice
and this way the horizontal frequency can easily be doubled, so that the
same resolution can be displayed on different monitors, even if the
horizontal frequency specification differs. Note that this option may not be
supported by every frame buffer device
.RE
.PP
Display positioning:
.RS
.TP
.IR \fB\-move "\ {" left | right | up | down }
move the visible part of the display in the specified direction
.TP
.BR \-step "\ <" \fIvalue >
set step size for display positioning (in pixels or pixel lines), if
.B \-step
is not given display will be moved 8 pixels horizontally or 2 pixel lines
vertically
.RE
.SH EXAMPLE
To set the used video mode for
.B X
insert the following in rc.local:
.RS
.sp
.B fbset
-fb
.I /dev/fb0
vga
.sp
.RE
and make the used frame buffer device known to
.BR X :
.RS
.sp
.B export
.RI FRAMEBUFFER= /dev/fb0
.RE
.SH FILES
.I /dev/fb*
.br
.I /etc/fb.modes
.SH SEE ALSO
.BR fb.modes "(5), " fbdev (4)
.SH AUTHORS
.TP
Geert Uytterhoeven <Geert.Uytterhoeven@cs.kuleuven.ac.be>
.TP
Roman Zippel <zippel@fh-brandenburg.de>
.br
man files
