#!/bin/sh

if [ "x$TARGET" != "xx86_64-w64-mingw32" ]; then
  # trigger build only on one of the matrix nodes
  exit;
fi

if [ "x$TRAVIS_BRANCH" != "xmaster" ]; then
  # only rebuild website with pushes to master
  exit;
fi

TRAVIS_COMMIT_RANGE=${TRAVIS_COMMIT_RANGE:-HEAD^..}
if git diff --quiet --name-only --exit-code "$TRAVIS_COMMIT_RANGE" DOCS/ VERSION; then
  exit;
fi

body='{
"request": {
  "branch":"master"
}}'

curl -s -X POST \
-H "Content-Type: application/json" \
-H "Accept: application/json" \
-H "Travis-API-Version: 3" \
-H "Authorization: token $WEBSITE_TRAVIS_TOKEN" \
-d "$body" \
https://api.travis-ci.org/repo/mpv-player%2Fmpv.io/requests
