
LIBNAME = libvorbisidec.a

include ../config.mak

SRCS	= bitwise.c \
          block.c \
          codebook.c \
          floor0.c \
          floor1.c \
          framing.c \
          info.c \
          mapping0.c \
          mdct.c \
          registry.c \
          res012.c \
          sharedbook.c \
          synthesis.c \
          window.c \

CFLAGS  = $(TREMOR_FLAGS)

include ../mpcommon.mak
