
.\" This manpage was/is done by Gabucino
.\" 
.TH "MPlayer" "1" "2002-04-18"

.SH "NAME"
mplayer \- Movie Player for Linux

.SH "SYNOPSIS"
.B mplayer
.RB [options]\ [\fIfile\fP\ |\ \fIURL\fP\ |\ \fIplaylist\fP\ |\ \-\ |\ ...]
.br
.B mplayer
.RB [global\ options]\ \fIfile1\fP\ [specific\ options]\ [file2]\ [specific\ options]\ ...
.br
.B mplayer
.RB [global\ options]\ {\fIgroup\ of\ files\ and\ options\fP}\ [group\ specific\ options]\ ...
.br
.B mplayer
.RB [dvd|vcd|tv]://[title]\ [options]
.br
.B mplayer
.RB [mms|http]://URL[:port]\ [options]

.SH "DESCRIPTION"
.B mplayer
is a movie player for LINUX (runs on many other Unices, and non\-x86
CPUs, see section 6). It plays most MPEG, VOB, AVI, VIVO, ASF/WMV, QT/MOV, FLI,
RM, NuppelVideo, yuv4mpeg, FILM, RoQ files, supported by many native, XAnim, and
Win32 DLL codecs. You can watch VideoCD, SVCD, DVD, 3ivx, DivX 3/4/5 and even WMV movies too
(and you don't need the avifile library at all!).

Another big feature of mplayer is the wide range of supported output drivers.
It works with X11, Xv, DGA, OpenGL, SVGAlib, fbdev, AAlib, DirectFB, but you can use
GGI and SDL (and this way all their drivers) and some lowlevel card-specific drivers
(for Matrox G-series, 3Dfx Banshee/Voodoo3 and ATI cards) too!
.br
Most of them supports software or hardware scaling, so you can enjoy movies in fullscreen.
MPlayer supports displaying through some hardware MPEG decoder boards, such as the Siemens DVB and
DXR3/Hollywood+!

Nice big antialiased shaded subtitles with european/ISO 8859-1,2 (hungarian, english, czech, 
etc), cyrillic, korean fonts are supported (10 supported subtitle formats: MicroDVD, SubRip, 
SubViewer, SAMI (smi), vplayer, RealMedia RT, ssa (Sub Station Alpha), AQT, VobSub, and our 
own: MPsub).

.SH "GUI OPTIONS"
.I NOTE:
The GUI code has to be compiled in *explicitly* (see documentation).
.br
.I NOTE:
The GUI code is STILL exterimental, it is under heavy development, parts of it (for example: playlist) not yet implemented.
.TP 
.B \-gui
Start MPlayer in GUI mode.
.TP 
.B \-skin <skin\ directory>
Load skin from this directory (WITHOUT path name!). For example '\-skin fittyfene' tries these:

    /usr/local/share/mplayer/Skin/fittyfene
    ~/.mplayer/Skin/fittyfene

.SH "DVD OPTIONS"
.I NOTE:
These options are valid only with DVD support compiled in (see documentation).
.br
.I NOTE:
DVD playback sometimes requires deinterlacing: see '\-pp 0x20000' or '\-npp lb' options.
.TP 
.B \-alang\ <audio\ stream\ language>
Used when playing DVD disks. Expects a two\-letter country code(s) as
parameter, and always tries to play back audio streams those language
matches the given code. For example: \-alang hu,en will always try to play
hungarian or if it's non\-existant then english audio streams if there are any.
.TP 
.B \-chapter\ <chapter\ id>[-<end chapter id>]
Specify which chapter to start playing at. Optionally specify which chapter to
end playing at. Examples can be found below.
.TP 
.B \-csslib <filename>
(old-style DVD option) This option is used to override the default location of libcss.so
.TP 
.B \-dvd\ <title\ id>
Tell MPlayer which movies (marked with titleid) to play. For example
sometimes '1' are trailers, and '2' is the real movie.
.TP 
.B \-dvd\-device\ <path\ to\ device>
Override default DVD device name /dev/dvd
.TP 
.B \-dvdangle\ <angle\ id>
Some DVD discs contain scenes that can be viewed from multiple angles.
Here you can tell MPlayer which angles to use. Examples can be found below.
.TP 
.B \-dvdauth <DVD\ device>
(old-style DVD option) Turns on DVD authentication using the given device.
.TP 
.B \-dvdkey <CSS\ key>
(old-style DVD option) When decoding from non-DVD, this option gives the CSS key needed 
to crack the DVD (the key is printed when authenticating with DVD).
.TP 
.B \-dvdnav 
Force usage of libdvdnav.
.TP 
.B \-sid\ <id>
Turns on DVD subtitle displaying. Also, you MUST specify a number which
corresponds to a DVD subtitle language (0\-31). For the list of available
subtitles, use with the \-v switch and look at the output.
.br
.I NOTE:
Use \-slang to define the subtitle language by name.
.TP 
.B \-skipopening
Skip dvd opening (dvdnav only).
.TP 
.B \-slang\ <subtitle\ language>
See the \-sid option, but this one needs a two\-letter parameter, a country code.
Like: \-slang hu,en will always select hungarian or if it's non existant then
english subtitles, if there are any. For the list of available subtitles, use
with the \-v switch and look at the output.
 
.SH "GENERAL OPTIONS"
.I NOTE:
Every "flag" option has "noflag" pair, e.g. \-fs opposite is \-nofs
.TP 
.B \-ao\ <driver>[:<device>]
Select audio output driver and optinaly device. "device" is valid with
SDL too, it means sub\-driver then (for example: \-vo sdl:esd).
If using OSS, you can specify which sound device to use like this:

    \-ao oss:/dev/dsp1     (replaces the old \-dsp option)

You can get the list of available drivers executing
.I mplayer \-ao help
.TP 
.B \-aspect <ratio>
Set aspect ratio of movies. It's autodetected on MPEG files, and can't be
autodetected on AVI files. Examples:

    \-aspect 4:3  or \-aspect 1.3333
    \-aspect 16:9 or \-aspect 1.7777
.TP 
.B \-audiofile\ <filename>
Play audio from an external file (WAV, MP3 or Vorbis)
.TP 
.B \-autoq\ <quality>
Dynamically changes the level of postprocess, depending on spare CPU time
available. The number you specify will be the maximum level used. Usually you
can use some big number. You may not use together with \-pp but it's ok with
\-npp!
.TP 
.B \-benchmark
Prints some statistics on CPU usage and dropped frames at the end.
Used in combination with \-nosound and \-vo null for benchmarking only video codec.
.TP 
.B \-cdrom\-device\ <path\ to\ device>
Override default CDROM drive name /dev/cdrom
.TP 
.B \-dr
Turns on direct rendering (not supported by all codecs and video outputs)
(default is off).
.TP 
.B \-ffactor\ <number>
Resample alphamap of the font. Can be:

    0    plain white fonts
    0.75 very narrow black outline [default]
    1    narrow black outline
    10   bold black outline
.TP 
.B \-font\ <path\ to\ font.desc\ file>
Search for the OSD/SUB fonts in an alternative directory (default:
~/.mplayer/font/font.desc). For example:

    \-font ~/.mplayer/arial\-14/font.desc
.TP 
.B \-fs
Fullscreen playing (centers movie, and makes black
bands around it). Toggle it with the 'f' key (not all video
outputs support it).
.TP
.B \-h, --help
Show short summary of options
.TP 
.B \-ifo <vobsub\ ifo\ file>
Indicate the file that will be used to load palette and frame size for VOBSUB
subtitles.
.TP 
.B \-lircconf\ <config\ file>
Specifies a configfile for LIRC (see http://www.lirc.org) if you don't like the default ~/.lircrc
.TP 
.B \-loop\ <num>
Loops movie playback <num> times. 0 means forever.
.TP
.B \-mf\ <multifile\ options>
Used when decoding from multiple PNG or JPEG files. The sub\-options are separated by ":"
(see documentation). They are:

    on            turns on multifile support
    w=<value>     width of the output
    h=<value>     height of the output
    fps=<value>   fps of the output
    type=<value>  type of input files (available types : jpeg, png)
.TP 
.B \-mixer\ <device>
This option will tell MPlayer to use a different device for mixing than
/dev/mixer.
.TP 
.B \-monitoraspect <ratio>
Set aspect ratio of your screen. Examples:

    \-monitoraspect 4:3  or 1.3333
    \-monitoraspect 16:9 or 1.7777
.TP 
.B \-noautosub
Turns off automatic subtitles
.TP 
.B \-nosound
Don't play sound
.TP 
.B \-osdlevel\ <level>
Specifies which mode the OSD should start in (0: none, 1: seek, 2: seek+timer)
(default = 2)
.TP 
.B \-playlist <file>
Play files according to this filelist (1 file/row or Winamp or ASX format).
.TP 
.B \-quiet
Display less output, status messages.
.TP 
.B \-rootwin
Play movie in the root window (desktop background) instead of opening
a new one. Works only with the xv and xmga drivers.
.TP 
.B \-ss\ <time> (see \-sb option too!)
Seek to given time position. For example:

    \-ss 56         seeks to 56 seconds
    \-ss 01:10:00   seeks to 1 hour 10 min
.TP 
.B \-sub\ <subtitle\ file>
Use/display this subtitle file
.TP 
.B \-subdelay\ <sec>
Delays subtitles by <sec> seconds. Can be negative.
.TP 
.B \-subfps\ <rate>
Specify frame/sec rate of subtitle file (float number)
(ONLY for frame\-based SUB files, i.e. NOT MicroDVD format!)
(default: the same fps as the movie)
.TP 
.B \-subpos <0 \- 100>
Specify the position of subtitles on screen
.TP 
.B \-sws\ <software\ scaler\ type>
This option sets the quality (and speed, respectively) of the software scaler,
with the \-zoom option. For example with x11 or other outputs which lack
hardware acceleration. Possible settings are:

    0 \- fast bilinear (default)
    1 \- bilinear
    2 \- bicubic (best quality)
    3 \- ?
    4 \- nearest neighbor (bad quality)
    5 \- area averageing scaling support
.TP 
.B \-tv\ <sub\-options>
This option enables the TV grabbing feature of MPlayer. The sub\-options are separated
by ":" (see documentation). They are:

    on                use TV input
    noaudio           no sound
    driver=<value>    available: dummy, v4l
    device=<value>    specify other device than the default /dev/video0
    input=<value>     available: television, s-video, composite, etc
    freq=<value>      specify the frequency to set the tuner (e.g. 511.250)
    outfmt=<value>    output format of the tuner (rgb32, rgb24, yv12, uyvy, i420)
    width=<value>     the width of the output window
    height=<value>    the height of the output window
    norm=<value>      available: PAL, SECAM, NTSC
    channel=<value>   set the tuner to the given channel
    chanlist=<value>  available: us-bcast, us-cable, europe-west, europe-east, etc
.TP 
.B \-v
Enable verbose output (more \-v means more verbosity)
.TP 
.B \-vcd\ <track>
Play video cd track from device instead of plain file
.TP 
.B \-vm
Try to change to a different video mode. dga2, x11 (XF86VidMode) and sdl
output drivers support it.
.TP 
.B \-vo\ <driver>[:<device>]
Select video output driver and optinally device. "device" is valid with
SDL and GGI too, it means sub\-driver then (for example: \-vo sdl:aalib).

You can get the list of available drivers executing
.I mplayer \-vo help
.TP
.B \-vobsub\ <vobsub\ file\ without\ extention>
Specify the VobSub files that are to be used for subtitle. This is
the full pathname without extensions, i.e. without the ".idx", ".ifo"
or ".sub".
.TP 
.B \-vobsubid\ <vobsub\ subtitle\ id>
Specify the VobSub subtitle id. Valid values range from 0 to 31.

.SH "ADVANCED OPTIONS"
.I NOTE:
These options can help you solve your particular problem (see documentation too!) or help in fine-tuning codec/driver parameters.
.TP
.B \-aa*
Used for \-vo aa. You can get a list and an explanation of available options executing
.I mplayer \-aahelp
.TP 
.B \-ac <name>
Force usage of a specific audio codec, according to its name in codecs.conf,
for example:

    \-ac mp3        use libmp3 MP3 codec
    \-ac mp3acm     use l3codeca.acm MP3 codec
    \-ac ac3        use AC3 codec
    \-ac hwac3      enable Hardware AC3 passthrough (see documentation)
    \-ac vorbis     use libvorbis
    \-ac ffmp3      use ffmpeg's MP3 decoder (SLOW)

See '\-ac help' for FULL list!
.TP 
.B \-aid\ <id>
Select audio channel [MPG: 0\-31 AVI: 1\-99 ASF: 0\-127 VOB: 128\-...]
.br
.I NOTE:
Use \-alang to define the language by name.
.TP
.B \-aofile <filename>
Filename for \-ao pcm.
.TP
.B \-aop\ <sub\-options>
Specify audio plugin(s) and their options (see documentation!!).
.TP 
.B \-audio\-demuxer <number>
Force audio demuxer type for \-audiofile. Give the demuxer ID as defined in
demuxers.h.
.TP
.B \-blue_intensity <\-1000\ \-\ 1000>
Adjust intensity of blue component of video signal (default 0).
.TP 
.B \-bpp\ <depth>
Use different color depth than autodetect. Not all \-vo drivers support
it (fbdev, dga2, svga, vesa).
.TP
.B \-brightness <\-1000\ \-\ 1000>
Adjust brightness of video output (default 0). It changes intensity of 
RGB components of video signal from black to white screen.
.TP 
.B \-cache\ <kbytes>
This option specifies how much memory to use when precaching a file/URL.
Especially useful on slow media (default is \-nocache).
.TP 
.B \-channels <n>
Select number of audio output channels to be used

    Stereo         2
    Surround       4
    Full 5.1       6

Currently this option is only honoured for AC3 audio.
.TP 
.B \-contrast <\-1000\ \-\ 1000>
Adjust contrast of video output (default 0). Works in similar manner as brightness.
.TP 
.B \-delay\ <secs>
Audio delay in seconds (may be +/\- float value)
.TP 
.B \-demuxer <number>
Force demuxer type. Give the demuxer ID as defined in demuxers.h.
.TP 
.B \-display <name>
Specify the hostname and display number of the X server you want
to display on. For example: \-display xtest.localdomain:0
.TP 
.B \-dumpaudio
Writes audio stream of the file to ./stream.dump (mostly usable
with mpeg/ac3)
.TP
.B \-dumpfile <filename>
Specify to which file MPlayer should dump to. Should be used together 
with \-dumpaudio/\-dumpvideo.
.TP 
.B \-dumpmpsub
Convert the given subtitle (specified with the \-sub switch) to MPlayer's
subtitle format, MPsub. Creates a dump.mpsub file in current directory.
.TP 
.B \-dumpstream
Dumps the file to ./stream.dump . Useful for example
when ripping from DVD.
.TP 
.B \-fb\ <device> (FBdev or DirectFB only)
Specifies the framebuffer device to use. By default it uses /dev/fb0.
.TP 
.B \-fbmode\ <modename> (FBdev only)
Change videomode to the one that is labelled as <modename> in /etc/fb.modes.
.br
.I NOTE:
VESA framebuffer doesn't support mode changing.
.TP 
.B \-fbmodeconfig\ <filename> (FBdev only)
Use this config file instead of the default /etc/fb.modes.
Only valid for the fbdev driver.
.TP 
.B \-flip
Flip image upside-down.
.TP 
.B \-forceidx
Force rebuilding of INDEX. Useful for files with broken index (desyncs, etc).
Seeking will be possible. You can fix the index permanently with
MEncoder (see the documentation).
.TP 
.B \-forcexv (SDL only)
Force using XVideo
.TP 
.B \-fps\ <value>
Force frame rate (if value is wrong in the header) (float number)
.TP 
.B \-framedrop (see \-hardframedrop option too!)
Frame dropping: decode all (except B) frames, video may skip. Usefull for playback on slow VGA card/bus.
.TP 
.B \-frames\ <number>
MPlayer plays <number> frames, then quits.
.TP 
.B \-fsmode\ <mode>
This option workarounds some problems when using specific windowmanagers and
fullscreen mode. If you experience fullscreen problems, try changing this
value between 0 and 7.

    \-fsmode 0      new method
    \-fsmode 1      ICCCWM patch
                   (for KDE2/icewm)
    \-fsmode 2      old method
    \-fsmode 3      ICCCWM patch
                   plus Motif method
.TP
.B \-green_intensity <\-1000\ \-\ 1000>
Adjust intensity of green component of video signal (default 0).
.TP
.B \-hardframedrop
More intense frame dropping (breaks decoding). Leads to image disortion!
.TP 
.B \-hr\-mp3\-seek
Hi\-res mp3 seeking. Default is: enabled when playing from external MP3 file, as
we need to seek to the very exact position to keep A/V sync. It can be slow
especially when seeking backwards \- it has to rewind to the beginning to find
the exact frame.
.TP
.B \-hue <\-1000\ \-\ 1000>
Adjust hue of video signal (default 0). You can get colored negative
of image with this option.
.TP 
.B \-idx (see \-forceidx option too!)
Rebuilds INDEX of the AVI, thus allowing seeking. Useful with broken/incomplete
downloads, or badly created AVIs.
.TP 
.B \-include <configfile>
Specify config file to be parsed after the default
.TP 
.B \-input <commands>
This option can be used to configure certain parts of the input system.
        conf=<file> read alternative input.conf.
                    If given without pathname,
                    $HOME/.mplayer is assumed.
        ar\-delay    delay in msec before we start
                    to autorepeat a key
                    (0 to disable)
        ar\-rate     how many keypress/second when
                    we autorepeat
        keylist     prints all keys that can be
                    bound to
        cmdlist     prints all commands that can
                    be bound
        js-dev      specifies the joystick device
                    to use 
                    (default is /dev/input/js0)

.I NOTE:
Autorepeat is currently only supported by joysticks.
.TP 
.B \-mc\ <seconds/frame>
Maximum A-V sync correction per frame (in seconds)
.TP 
.B \-monitor_dotclock <dotclock\ (or\ pixelclock) range>  (FBdev only)
Look into etc/example.conf for further information and in DOCS/video.html.
.TP 
.B \-monitor_hfreq <horizontal frequency range>  (FBdev only)
.TP 
.B \-monitor_vfreq <vertical frequency range>  (FBdev only)
.TP 
.B \-ni
Force usage of non\-interleaved AVI parser (fixes playing
of some bad AVI files).
.TP 
.B \-nobps
Don't use avg. byte/sec value for A\-V sync (AVI). Helps with some AVI files with broken header.
.TP 
.B \-double
enables doublebuffering. Fixes flicker by storing two frames in memory, and
displaying one while decoding another. Can effect OSD. Needs twice the memory
than a single buffer, so it won't work on cards with very few video memory.
.TP 
.B \-nojoystick
Turns off joystick support. Default is on, if compiled in.
.TP 
.B \-nolirc
Turns off lirc support.
.TP
.B \-nortc
Turns off usage of /dev/rtc (real-time clock)
.TP
.B \-noslices
Disable the use of draw_slice by codecs.
.TP
.B \-nowaveheader  (-ao pcm only)
Don't include wave header. Used for RAW PCM.
.TP 
.B \-npp\ <options>
This option allows to give more litterate options for postprocessing, 
and is another way of calling it (not with \-pp).

.I EXAMPLE:
    '\-pp 0x2007f' <=> '\-npp hb,vb,dr,al,lb'
    '\-pp 0x7f'    <=> '\-npp hb,vb,dr,al'

The options for \-npp are a coma separated list you can get by executing
.I mplayer \-npp help
.br
These keywords accept a '\-' prefix to disable the option.

.I EXAMPLE:
    '\-npp de,\-al' means 'default filters without brightness/contrast correction'

A ':' followed by a letter may be appended to the option to indicate its 
scope:
    a : automatically switches the filter off if the cpu is too slow
    c : do chrominance filtering too
    y : do not do chrominance filtering (that is only luminance filtering)

Each filter defaults to 'c' (chrominance).

.I EXAMPLE:
    '\-npp de,tn:1:2:3' means 'enable default filters & temporal denoiser'
    '\-npp hb:y,vb:a \-autoq 6' means 'deblock horizontal only luminance, and
    automatically switch vertical deblocking on/off depending on available 
    cpu time'
.TP 
.B \-pp\ <quality> (see \-npp option too!)
Apply postprocess filter on decoded image

Postprocessing effect depends on the codec and works only for MPEG1/2,
libavcodec codecs (ff*). It doesn't work for Win32/XAnim codecs.

This is the numerical mode to use postprocessing. The '\-npp' option described
below has the same effects but with letters. To have several filters at the
same time, simply add the hexadecimal values.

.I EXAMPLE:
The following values are known to give good results:
    \-pp 0x20000 <=> \-npp lb (deinterlacing \- for DVD/MPEG2 playback e.g.)
    \-pp 0x7f    <=> \-npp hb,vb,dr,al (smooth the images)
.TP
.B \-red_intensity <\-1000\ \-\ 1000>
Adjust intensity of red component of video signal (default 0).
.TP
.B \-saturation <\-1000\ \-\ 1000>
Adjust saturation of video output (default 0). You can get grayscale output 
with this option.
.TP 
.B \-sb\ <byte\ position> (see \-ss option too!)
Seek to byte position. Useful for playback from cdrom images / vob files with junk at the beginning.
.TP 
.B \-screenw\ <pixels> \-screenh\ <pixels>
If you use an output driver which can't know the resolution of the screen
(fbdev/x11 and/or TVout) this is where you can specify the horizontal and vertical
resolution.
.TP 
.B \-slave
This option switches on slave mode. This is intended for use
of MPlayer as a backend to other programs. Instead of intercepting keyboard
events, MPlayer will read simplistic command lines from its stdin.
See section
.B SLAVE MODE PROTOCOL
For the syntax.
.TP 
.B \-softsleep
Uses high quality software timers. Efficient as the RTC, doesn't need root,
but requires more CPU.
.TP 
.B \-srate <Hz>
Specifies Hz to playback audio on. Has effect on playback speed!
.TP 
.B \-stereo <mode>
Select type of MP2/MP3 stereo output.

        Stereo         0
        Left channel   1
        Right channel  2
.TP 
.B \-subcp\ codepage
If your system supports iconv(3), you can use this option to
specify codepage of the subtitle. Examples:

        \-subcp latin2
        \-subcp cp1250
.TP 
.B \-unicode
Tells MPlayer to handle the subtitle file as UNICODE.
.TP 
.B \-utf8
Tells MPlayer to handle the subtitle file as UTF8.
.TP 
.B \-vc <name>
Force usage of a specific video codec, according to its name in codecs.conf,
for example:

    \-vc divx       use VFW DivX codec
    \-vc divxds     use DirectShow DivX codec
    \-vc ffdivx     use libavcodec's DivX codec
    \-vc ffmpeg12   use libavcodec's MPEG1/2 codec
    \-vc divx4      use ProjectMayo's DivX codec

See '\-vc help' for FULL list!
.TP 
.B \-vid\ <id>
Select video channel [MPG: 0\-15  ASF:  0\-255 ]
.TP 
.B \-vop <filter>
Activate video filters (see documentation!).
.TP
.B \-vsync
Enables VBI for vesa
.TP 
.B \-wid\ <window\ id>
This tells MPlayer to use a X11 window, which is useful to embed MPlayer in a
browser (with the plugger extension for instance)
.TP 
.B \-xineramascreen <screen\ number>
In Xinerama configurations (i.e. a single desktop that spans across multiple
displays) this option tells MPlayer which screen to display movie on. Range 0 \- ...
.TP 
.B \-x\ <x>
Scale image to x width (if sw/hw scaling available). Disables aspect calcs.
.TP 
.B \-xy\ <x>
x<=8: Scale image by factor <x>
x>8:  Set width to <x> and calculate height to keep correct aspect ratio
.TP 
.B \-y\ <y>
Scale image to y height (if sw/hw scaling available). Disables aspect calcs.
.TP 
.B \-zoom
Allow software scaling, where available. Could be used to force scaling with -vop scale
(-vop scale will IGNORE options -x/-y/-xy/-fs/-aspect without -zoom)
.TP 
.B \-z\ <0\-9>
Specifies compression level for PNG output (-vo png)
          0 : no compression
          9 : max compression
.TP
.B \-zr*
Used for \-vo zr. You can get a list and an explanation of available options executing
.I mplayer \-zrhelp

.SH "ALPHA/BETA CODE"
.I NOTE:
These are included in this manpage just for completeness! These may or may NOT
work! If you don't know what are these, you DON'T need these! In either case,
double\-check the documentation!
.TP 
.B \-dumpvideo
Dump raw compressed video stream to ./stream.dump (not very usable)
.TP 
.B \-ssf <mode>
.TP 
.B \-sub\-demuxer <number>
Force subtitle demuxer type for \-subfile.
.TP 
.B \-subfile <filename>
Currently useless. Same as \-audiofile, but for subtitle streams. (OggDS?)
.TP 
.B \-vivo <sub\-options>
Force audio parameters for the .vivo demuxer (for debugging purposes)

.SH "OBSOLETE OPTIONS"
.I NOTE:
These options are obsoleted and may be removed in future.
.TP 
.B \-afm <1\-12>
Force usage of a specific audio format. For example:

    \-afm 1         use libmp3 (mp2/mp3, but not mp1)
    \-afm 2         suppose raw PCM audio
    \-afm 3         use libac3
    \-afm 4         use a matching Win32 codec
    \-afm 5         use aLaw/uLaw driver
    \-afm 10        use libvorbis
    \-afm 11        use ffmpeg's MP3 decoder (even mp1)

See \-ac help for FULL list!
.TP 
.B \-dapsync
Use alternative A/V sync method.
.TP 
.B \-vfm <1\-12>
Force usage of a specific codec FAMILY, and FALLBACK to default if failed.
For example:

    \-vfm 2         use VFW (Win32) codecs
    \-vfm 3         use OpenDivX/DivX4 codec (YV12)
                   (same as \-vc odivx but fallback)
    \-vfm 4         use DirectShow (Win32) codecs
    \-vfm 5         use libavcodec codecs
    \-vfm 7         use DivX4 codec (YUY2)
                   (same as \-vc divx4 but fallback)
    \-vfm 10        use XAnim codecs

See \-vc help for FULL list!

.I NOTE:
If libdivxdecore support was compiled in, then type 3 and 7 now contains
just the same DivX4 codec, but different APIs to reach it. For difference
between them and when to use which, check the DivX4 section in the
documentation.

.SH "KEYBOARD CONTROL"
.I NOTE:
Use the new input system to change the default keys (edit input.conf).
There is support for Joystick and LIRC too (see documentation).
.br
.I NOTE:
These keys may/may not work, depending on your video output driver.
.TP 
.B general control
<\-  and  \->     seek backward/forward  10 seconds
.br
up and down     seek backward/forward   1 minute
.br
pgup and pgdown seek backward/forward  10 minutes
.br
< and >		 previous/next file
.br
p / SPACE       pause movie (press any key)
.br
q / ESC         stop playing and quit program
.br
+ and \-         adjust audio delay by +/\- 0.1 second
.br
/ and *         decrease/increase volume
.br
f               toggle fullscreen
.br
o               toggle OSD: none / seek / seek+timer
.br
d               toggle frame dropping
.br
z and x         adjust subtitle delay by +/\- 0.1 second
.br
r and t         adjust subtitle position

(The following keys are valid only when using \-vo xv or \-vo [vesa|fbdev]:vidix
or \-vo xvidix or \-vc divxds (slow).)

1 and 2         adjust contrast
.br
3 and 4         adjust brightness
.br
5 and 6         adjust hue
.br
7 and 8         adjust saturation
.TP 
.B GUI keyboard control
gray \- and +    decrease/increase volume
.br
ENTER           start playing
.br
s               stop playing
.br
a               about
.br
l               load file
.br
b               skin browser
.br
e               toggle equalizer
.br
p               toggle playlist
.TP
.B TV input control
h and l         select previous/next channel
.br
n               change norm
.br
b               change channel list
.TP
.B DVDNAV input control
K,J,H,L         browse up/down/left/right
.br
M               jump to main menu
.br
S               select

.SH "SLAVE MODE PROTOCOL"
If the \-slave switch is given, playback is controlled by a 
line\-based protocol. If the new input is enabled (default)
each line must contain one command otherwise one of the 
following tokens:
.TP 
       stop            pause playback
.br
play            resume playback
.br
seek <num>      continue at second NUM
.br
skip <num>      skip NUM seconds (may be negative)
.br
quit            exit MPlayer

.SH "FILES"
.BR /etc/mplayer.conf\ \ \ \ \ 
System\-wide settings
.br
.BR ~/.mplayer/config\ \ \ \ \ 
User settings
.br
.BR ~/.mplayer/input.conf\ 
Input bindings
.br
.BR ~/.mplayer/font/\ \ \ \ \ \ 
Font directory. There must be a font.desc file and files with .RAW extension.
.br

.I Subtitles
(utf/UTF/sub/SUB/srt/SRT/smi/SMI/rt/RT/txt/TXT/ssa/SSA)
.br
Sub files are searched in this priority (for example /mnt/movie/movie.avi):
.br
    /mnt/cdrom/movie.sub
.br
    ~/.mplayer/sub/movie.sub 
.br
    ~/.mplayer/default.sub

.SH "EXAMPLES"
.B Quickstart DVD playing
mplayer \-dvd 1
.TP 
.B Play only chapters 5, 6, 7
mplayer \-dvd 1 \-chapter 5\-7
.TP 
.B Multiangle DVD playing
mplayer \-dvd 1 \-dvdangle 2
.TP 
.B Playing from a different DVD device
mplayer \-dvd 1 \-dvd\-device /dev/dvd2
.TP 
.B Stream from HTTP
mplayer http://mplayer.hq/example.avi
.TP 
.B Convert subtitle to MPsub (to ./dump.mpsub)
mplayer dummy.avi \-sub source.sub \-dumpmpsub
.TP
.B Input from standard V4L
mplayer \-tv on:driver=v4l:width=640:height=480:outfmt=i420 \-vc rawi420 \-vo xv

.SH "BUGS"
Probably. PLEASE, double-check the documentation (especially bugreports.html),
the FAQ and the mail archive before !

Send your complete bugreports to the MPlayer-users mailing list at
<mplayer-users@mplayerhq.hu>. We love complete bugreports :)

.SH "AUTHORS"
Check documentation!

MPlayer is (C) 2000\-2002
.I Arpad Gereoffy <sendmail@to.mplayer\-users>

This manpage is written and maintained by
.I Gabucino <sendmail@to.mplayer\-users>.

.SH "STANDARD DISCLAIMER"
Use only at your own risk! There may be errors and inaccuracies that could
be damaging to your system or your eye. Proceed with caution, and although
this is highly unlikely, the author doesn't take any responsibility for that!
.\" end of file
